/** POS電子ジャーナル（LZH/LH5 + ESC/POS + CP932）の解析・月次集約。 */
import { extractLhaArchive } from "./pos_journal_lha.ts";

export const POS_JOURNAL_STORE_CODE_MAP: Readonly<
  Record<string, {
    storeKey: string;
    storeName: string;
  }>
> = {
  "1015": { storeKey: "bistrocavacava", storeName: "Bistro CAVACAVA" },
  // 2025年分の既存POS原本で使われていた旧コード。1015と同じ店舗。
  "1020": { storeKey: "bistrocavacava", storeName: "Bistro CAVACAVA" },
  // マルゴエスの実POS電子ジャーナル。DBのpos_journal_store_codesにも同じ割当を持つ。
  "1022": { storeKey: "marugos", storeName: "マルゴエス" },
};

export type PosJournalReceiptItem = {
  code: string;
  name: string;
  unit: number;
  qty: number;
  amount: number;
  /** 大分類(コード由来)または細分類(手動割当)。集約は posJournalPrimaryCategory を通す。 */
  category?: string;
  isCharge?: boolean;
};

export const POS_JOURNAL_ADJUSTMENT_ITEM_CODE = "__journal_adjustment__";

export function isPosJournalAdjustmentItem(
  item: unknown,
): boolean {
  return !!item && typeof item === "object" &&
    String((item as { code?: unknown }).code ?? "") ===
      POS_JOURNAL_ADJUSTMENT_ITEM_CODE;
}

export type PosJournalReceipt = {
  no: string;
  time: string;
  pay: string;
  total: number | null;
  guests: number | null;
  table_no?: string;
  /** 取引変更で取り消す元会計No.。VOIDレコード自身と参照先を日計明細から除外する。 */
  void_ref?: string;
  /** 会計内の支払方法別純額。複数決済を「複数」1件へ潰さず保持する。 */
  payment_breakdown?: Record<string, number>;
  items: PosJournalReceiptItem[];
};

export type PosJournalDay = Record<string, unknown> & {
  business_date: string;
  receipts: PosJournalReceipt[];
  source: string;
  /** LZHの精算レポートを最後まで解析済み。売上0円・会計0件の日も未解析と区別する。 */
  parsed_complete?: boolean;
};

export type PosJournalSummary = {
  meta: Record<string, unknown>;
  totals: Record<string, number>;
  payment_breakdown: Record<string, { count: number; amount: number }>;
  item_ranking: Array<
    { code: string; name: string; qty: number; amount: number }
  >;
  days: PosJournalDay[];
};

export type JournalSavedReportSaleItem = {
  code: string;
  name: string;
  qty: number;
  amount: number;
  /** 大分類(コード由来)または細分類(手動割当)。集約は posJournalPrimaryCategory を通す。 */
  category: string;
  isCharge: boolean;
  known: boolean;
  byCode: boolean;
  needsReview: boolean;
};

export type JournalSavedReportSale = {
  no: string;
  date: string;
  weekday: string;
  hour: number;
  minute: number;
  hasAccountingTime: boolean;
  mealPeriod: "ランチ" | "ディナー" | "";
  time: string;
  total: number;
  tax: number;
  points: number;
  groups: number;
  customers: number;
  customerCountReliable: boolean;
  isSplitFragment: boolean;
  tableNo: string;
  method: string;
  change: number;
  weather: string;
  tempC: number | null;
  payments: {
    byMethod: Record<string, number>;
    total: number;
    change: number;
    details: Array<{ label: string; method: string; amount: number }>;
  };
  items: JournalSavedReportSaleItem[];
  itemTotal: number;
};

export type JournalSavedReportData = {
  id: string;
  title: string;
  period: string;
  createdAt: string;
  salesCount: number;
  total: number;
  totalSales: number;
  foodTotal: number;
  drinkTotal: number;
  roomTotal: number;
  otherTotal: number;
  /** 割り当てられた粒度ごとの内訳。細分類の切替表示に使う。合計は上の4項目が正。 */
  categoryBreakdown?: Record<string, number>;
  chargeTotal: number;
  lunchTotal: number;
  dinnerTotal: number;
  lunchCustomers: number;
  dinnerCustomers: number;
  lunchFoodTotal: number;
  lunchDrinkTotal: number;
  dinnerFoodTotal: number;
  dinnerDrinkTotal: number;
  totalCustomers: number;
  totalGroups: number;
  topProducts: Array<{
    name: string;
    qty: number;
    amt: number;
    category: string;
  }>;
  weekdayBreakdown: Array<{
    weekday: string;
    totalSales: number;
    transactionCount: number;
    customerCount: number;
    avgSpend: number;
  }>;
  hourlyBreakdown: Array<{
    hour: number;
    totalSales: number;
    count: number;
    customers: number;
  }>;
  dailyBreakdown: Array<{
    date: string;
    total: number;
    food: number;
    drink: number;
    groups: number;
    customers: number;
  }>;
  parserVersion: string;
  verificationVersion: string;
  categoryVersion: string;
  mealPeriodVersion: string;
  sourceMonths: string[];
  journalIds: number[];
  weatherByDate: Record<string, { weather: string; tempC: number | null }>;
  posJournalDays: PosJournalDay[];
  sales: JournalSavedReportSale[];
  autoGeneratedFromPosJournal: boolean;
  autoGeneratedAt: string;
};

type JournalReportSaleLike = Record<string, unknown> & {
  date?: unknown;
  no?: unknown;
  time?: unknown;
  total?: unknown;
  tax?: unknown;
  groups?: unknown;
  customers?: unknown;
  guests?: unknown;
  isSplitFragment?: unknown;
  tableNo?: unknown;
  table_no?: unknown;
  method?: unknown;
  pay?: unknown;
  payments?: unknown;
  items?: unknown;
  weather?: unknown;
  tempC?: unknown;
  temp_c?: unknown;
};

type JournalReportDataLike = Record<string, unknown> & {
  sales?: unknown;
  posJournalDays?: unknown;
  sourceMonths?: unknown;
  weatherByDate?: unknown;
  createdAt?: unknown;
};

const HEADER_RE =
  /^\s*(\d{4}-\d{2})\s+No\.(\d+)\s+(\d{4})年\s*(\d+)月\s*(\d+)日\((.)\)\s*(\d+)時(\d+)分/;
const ITEM_CODE_RE = /^\s{2}(\d{13})\s+(\S.*?)\s*$/;
const ITEM_PRICE_RE =
  /@\s*([\d,]+)\s*x\s*(-?[\d,]+)\s+[\\¥]?\s*(-?[\d,]+)/;
export const POS_JOURNAL_REPORT_PARSER_VERSION = "2026-08-30-v22";
export const POS_JOURNAL_REPORT_VERIFICATION_VERSION =
  "split-bill-reconcile-v3";
export const POS_JOURNAL_REPORT_CATEGORY_VERSION =
  "pos-food-drink-room-bycode-v3";
export const POS_JOURNAL_REPORT_MEAL_PERIOD_VERSION =
  "lunch-before-1600-v1";
/**
 * 商品コードから決まる大分類。ここは従来どおり4つのまま変えない。
 * 集計・グラフ・AIの前提がこの4分類で組まれており、過去レポートとの比較も
 * この粒度で行うため。
 */
export const POS_JOURNAL_PRIMARY_CATEGORIES = [
  "フード",
  "飲料",
  "室料",
  "その他",
] as const;
type PosJournalPrimaryCategory = typeof POS_JOURNAL_PRIMARY_CATEGORIES[number];

/**
 * 手動分類でだけ使える細分類と、その集約先。
 * コードからは自動で付かない。運用側が商品ごとに割り当てる。
 */
export const POS_JOURNAL_SUB_CATEGORY_PARENTS: Readonly<
  Record<string, PosJournalPrimaryCategory>
> = {
  "アラカルト": "フード",
  "コース": "フード",
  "デザート": "フード",
  "ワインボトル": "飲料",
  "グラスワイン": "飲料",
  "ソフトドリンク": "飲料",
  "その他ドリンク": "飲料",
};

/** 手動分類で選べる全カテゴリ（大分類＋細分類）。 */
export const POS_JOURNAL_REPORT_CATEGORIES = [
  ...POS_JOURNAL_PRIMARY_CATEGORIES,
  ...Object.keys(POS_JOURNAL_SUB_CATEGORY_PARENTS),
] as const;
type PosJournalReportCategory = string;

/**
 * どのカテゴリでも大分類へ寄せる。細分類が入っていても
 * フード計・飲料計が従来どおりの意味を保つようにするための唯一の入口。
 */
export function posJournalPrimaryCategory(
  value: unknown,
): PosJournalPrimaryCategory {
  const text = String(value ?? "").trim();
  const parent = POS_JOURNAL_SUB_CATEGORY_PARENTS[text];
  if (parent) return parent;
  return (POS_JOURNAL_PRIMARY_CATEGORIES as readonly string[]).includes(text)
    ? text as PosJournalPrimaryCategory
    : "その他";
}
const POS_JOURNAL_FOOD_RANGES: ReadonlyArray<[number, number]> = [[100, 199]];
const POS_JOURNAL_DRINK_RANGES: ReadonlyArray<[number, number]> = [
  [23, 29],
  [2100, 2199],
  [8100, 8199],
  [9000, 9399],
];
const POS_JOURNAL_ROOM_CODES = new Set([2]);
const POS_JOURNAL_CHARGE_CODES = new Set([1]);

export type PosJournalWeatherCacheDay = {
  temp: number | null;
  rain?: number | null;
  code?: number | null;
};

export function posJournalWeatherText(value: unknown): string {
  return String(value ?? "").trim();
}

/** 未入力・空文字・天候なしの 0℃ は欠落とみなす（Number(null) === 0 の化け防止）。 */
export function parsePosJournalTempC(
  value: unknown,
  weather: unknown = "",
): number | null {
  if (value == null) return null;
  if (typeof value === "string" && value.trim() === "") return null;
  const n = Number(value);
  if (!Number.isFinite(n)) return null;
  if (n === 0 && !posJournalWeatherText(weather)) return null;
  return n;
}

export function posJournalDayNeedsWeather(day: {
  weather?: unknown;
  temp_c?: unknown;
  tempC?: unknown;
}): boolean {
  const weather = posJournalWeatherText(day?.weather);
  const temp = parsePosJournalTempC(day?.temp_c ?? day?.tempC, weather);
  return !weather || temp == null;
}

export function posJournalWeatherLabelFromCache(
  day: PosJournalWeatherCacheDay | null | undefined,
): string {
  if (!day) return "";
  const code = day.code == null ? NaN : Number(day.code);
  if (Number.isFinite(code)) {
    if (code === 0 || code === 1 || code === 2) return "晴れ";
    if (code === 3) return "曇り";
    if (code >= 45 && code <= 48) return "霧";
    if (code >= 51 && code <= 57) return "霧雨";
    if (code >= 61 && code <= 67) return code >= 65 ? "大雨" : "雨";
    if (code >= 71 && code <= 77) return "雪";
    if (code >= 80 && code <= 82) return "にわか雨";
    if (code >= 85 && code <= 86) return "雪";
    if (code >= 95) return "雷雨";
  }
  if (day.rain != null && Number(day.rain) > 0.5) return "雨";
  if (day.temp != null && Number.isFinite(Number(day.temp))) return "晴れ";
  return "";
}

export function applyCachedWeatherToPosJournalDays(
  days: PosJournalDay[],
  weatherByDate: Record<string, PosJournalWeatherCacheDay>,
): PosJournalDay[] {
  const cache = weatherByDate && typeof weatherByDate === "object"
    ? weatherByDate
    : {};
  return (Array.isArray(days) ? days : []).map((day) => {
    const weather = posJournalWeatherText(day.weather);
    const temp = parsePosJournalTempC(day.temp_c ?? day.tempC, weather);
    if (weather && temp != null) return day;
    const cached = cache[day.business_date];
    const filledWeather = weather || posJournalWeatherLabelFromCache(cached);
    const filledTemp = temp != null
      ? temp
      : (cached && cached.temp != null && Number.isFinite(Number(cached.temp))
        ? Math.round(Number(cached.temp))
        : null);
    if (filledWeather === weather && filledTemp === temp) {
      return { ...day, weather, temp_c: temp };
    }
    return { ...day, weather: filledWeather, temp_c: filledTemp };
  });
}
const FULLWIDTH_MAP: Readonly<Record<string, string>> = {
  "０": "0",
  "１": "1",
  "２": "2",
  "３": "3",
  "４": "4",
  "５": "5",
  "６": "6",
  "７": "7",
  "８": "8",
  "９": "9",
  "，": ",",
  "．": ".",
  "％": "%",
  "／": "/",
  "－": "-",
};

function normalizeWide(value: string): string {
  return String(value || "").replace(
    /[０-９，．％／－]/g,
    (char) => FULLWIDTH_MAP[char] ?? char,
  );
}

function normalizedCodeNumber(value: unknown): number | null {
  const digits = String(value ?? "").normalize("NFKC").replace(/\D/g, "");
  if (!digits) return null;
  const n = Number(digits);
  return Number.isFinite(n) ? n : null;
}

function numberInRanges(
  value: number | null,
  ranges: ReadonlyArray<[number, number]>,
): boolean {
  return value != null &&
    ranges.some(([from, to]) => value >= from && value <= to);
}

/**
 * 店舗ごとのコード範囲。画面の入力欄と同じテキスト仕様を解釈した結果を持つ。
 * 行の無い店舗では null を渡し、コード内の既定値へフォールバックする。
 */
export type PosJournalCategoryRules = {
  food: ReadonlyArray<CodeSpec>;
  drink: ReadonlyArray<CodeSpec>;
  room: ReadonlyArray<CodeSpec>;
  charge: ReadonlyArray<CodeSpec>;
};

type CodeSpec =
  | { kind: "range"; start: number; end: number }
  | { kind: "code"; digits: string; number: number };

/**
 * '0100-0199, 0250' 形式を解釈する。
 * 画面側 parseCategorySpecs と同じ規則にすること。ここがずれると、
 * 同じ設定でも画面と保存レポートで分類が食い違う。
 */
export function parsePosJournalCodeSpecs(spec: unknown): CodeSpec[] {
  return String(spec ?? "")
    .split(/[\s,、;；]+/)
    .map((token) => token.trim())
    .filter(Boolean)
    .map((token): CodeSpec | null => {
      const range = token.match(/^(\d+)\s*[-〜～]\s*(\d+)$/);
      if (range) {
        const start = Number(range[1]);
        const end = Number(range[2]);
        if (!Number.isFinite(start) || !Number.isFinite(end)) return null;
        return {
          kind: "range",
          start: Math.min(start, end),
          end: Math.max(start, end),
        };
      }
      const digits = String(token).normalize("NFKC").replace(/[^0-9]/g, "");
      if (!digits) return null;
      return { kind: "code", digits, number: Number(digits) };
    })
    .filter((spec): spec is CodeSpec => spec !== null);
}

/** DBの1行から解釈済みの範囲を作る。全欄が空なら null(=既定値を使う)。 */
export function buildPosJournalCategoryRules(
  row: Record<string, unknown> | null | undefined,
): PosJournalCategoryRules | null {
  if (!isRecord(row)) return null;
  const rules: PosJournalCategoryRules = {
    food: parsePosJournalCodeSpecs(row.food_codes),
    drink: parsePosJournalCodeSpecs(row.drink_codes),
    room: parsePosJournalCodeSpecs(row.room_codes),
    charge: parsePosJournalCodeSpecs(row.charge_codes),
  };
  const configured = rules.food.length + rules.drink.length + rules.room.length +
    rules.charge.length;
  return configured ? rules : null;
}

function codeSpecMatches(
  specs: ReadonlyArray<CodeSpec>,
  digits: string,
  number: number | null,
): boolean {
  return specs.some((spec) =>
    spec.kind === "code"
      ? (spec.digits === digits || (number != null && spec.number === number))
      : (number != null && number >= spec.start && number <= spec.end)
  );
}

export function classifyPosJournalReportItem(
  code: unknown,
  overrides: Record<string, unknown> = {},
  name: unknown = "",
  /** 店舗ごとのコード範囲。null なら従来どおりコード内の既定値を使う。 */
  rules: PosJournalCategoryRules | null = null,
): {
  category: PosJournalReportCategory;
  isCharge: boolean;
  known: boolean;
  byCode: boolean;
  byOverride: boolean;
  needsReview: boolean;
} {
  const codeText = String(code ?? "").normalize("NFKC").trim();
  const nameText = String(name ?? "").normalize("NFKC").replace(/\s+/g, " ")
    .trim();
  const overrideKey = `${codeText}|${nameText}`;
  const override = String(overrides[overrideKey] ?? "").trim();
  const number = normalizedCodeNumber(codeText);
  const digits = codeText.replace(/[^0-9]/g, "");
  // 店舗設定があればそちらを正とする。無ければ従来の定数。
  const isCharge = rules
    ? codeSpecMatches(rules.charge, digits, number)
    : (number != null && POS_JOURNAL_CHARGE_CODES.has(number));
  if (
    (POS_JOURNAL_REPORT_CATEGORIES as readonly string[]).includes(override)
  ) {
    return {
      category: override as PosJournalReportCategory,
      isCharge,
      known: true,
      byCode: false,
      byOverride: true,
      needsReview: false,
    };
  }
  const matchesFood = rules
    ? codeSpecMatches(rules.food, digits, number)
    : numberInRanges(number, POS_JOURNAL_FOOD_RANGES);
  const matchesDrink = rules
    ? codeSpecMatches(rules.drink, digits, number)
    : numberInRanges(number, POS_JOURNAL_DRINK_RANGES);
  const matchesRoom = rules
    ? codeSpecMatches(rules.room, digits, number)
    : (number != null && POS_JOURNAL_ROOM_CODES.has(number));
  // チャージだけに当たった商品はフードの内数として扱う（画面側と同じ規則）。
  if (matchesFood || isCharge) {
    return {
      category: "フード",
      isCharge,
      known: true,
      byCode: true,
      byOverride: false,
      needsReview: false,
    };
  }
  if (matchesDrink) {
    return {
      category: "飲料",
      isCharge: false,
      known: true,
      byCode: true,
      byOverride: false,
      needsReview: false,
    };
  }
  if (matchesRoom) {
    return {
      category: "室料",
      isCharge: false,
      known: true,
      byCode: true,
      byOverride: false,
      needsReview: false,
    };
  }
  return {
    category: "その他",
    isCharge: false,
    known: true,
    byCode: false,
    byOverride: false,
    needsReview: true,
  };
}

export function applyPosJournalCategoryOverrides(
  days: PosJournalDay[],
  overrides: Record<string, unknown> = {},
  rules: PosJournalCategoryRules | null = null,
): PosJournalDay[] {
  return (Array.isArray(days) ? days : []).map((day) => ({
    ...day,
    receipts: (Array.isArray(day.receipts) ? day.receipts : []).map(
      (receipt) => ({
        ...receipt,
        items: (Array.isArray(receipt.items) ? receipt.items : []).map(
          (item) => {
            const classified = classifyPosJournalReportItem(
              item.code,
              overrides,
              item.name,
              rules,
            );
            const existing = String(item.category ?? "").trim();
            const keepExisting =
              !classified.byOverride &&
              (POS_JOURNAL_REPORT_CATEGORIES as readonly string[]).includes(
                existing,
              );
            return {
              ...item,
              category: keepExisting
                ? existing as PosJournalReportCategory
                : classified.category,
              isCharge: classified.isCharge || item.isCharge === true,
            };
          },
        ),
      }),
    ),
  }));
}

function stripEscPos(raw: Uint8Array): string {
  const output: number[] = [];
  for (let index = 0; index < raw.length;) {
    const byte = raw[index];
    if (byte === 0x1b || byte === 0x1c) {
      index += 3;
      continue;
    }
    output.push(byte);
    index += 1;
  }
  return new TextDecoder("shift-jis", { fatal: false }).decode(
    Uint8Array.from(output),
  );
}

function amount(value: string): number | null {
  const match = normalizeWide(value).match(/\\\s*([\d,]+)/);
  return match ? Number(match[1].replace(/,/g, "")) : null;
}

function firstInt(value: string, unit: string): number | null {
  const match = normalizeWide(value).match(new RegExp(`([\\d,]+)\\s*${unit}`));
  return match ? Number(match[1].replace(/,/g, "")) : null;
}

type JournalRecord = {
  no: string;
  y: number;
  mo: number;
  d: number;
  wd: string;
  hh: number;
  mi: number;
  lines: string[];
};

function splitRecords(text: string): JournalRecord[] {
  const records: JournalRecord[] = [];
  let current: JournalRecord | null = null;
  for (const line of text.split(/\r?\n|\r/g)) {
    const match = line.match(HEADER_RE);
    if (match) {
      if (current) records.push(current);
      current = {
        no: match[2],
        y: Number(match[3]),
        mo: Number(match[4]),
        d: Number(match[5]),
        wd: match[6],
        hh: Number(match[7]),
        mi: Number(match[8]),
        lines: [],
      };
    } else if (current) current.lines.push(line);
  }
  if (current) records.push(current);
  return records;
}

function valueNear(lines: string[], index: number, look = 2): number | null {
  for (
    let cursor = index;
    cursor < Math.min(index + look + 1, lines.length);
    cursor += 1
  ) {
    const value = amount(lines[cursor]);
    if (value != null) return value;
  }
  return null;
}

function parseSettlement(record: JournalRecord): Record<string, unknown> {
  const lines = record.lines;
  const output: Record<string, unknown> = {};
  for (const line of lines) {
    const match = normalizeWide(line).match(
      /営業日付[：:]\s*(\d{4})年\s*(\d+)月\s*(\d+)日/,
    );
    if (match) {
      output.business_date = `${Number(match[1]).toString().padStart(4, "0")}-${
        Number(match[2]).toString().padStart(2, "0")
      }-${Number(match[3]).toString().padStart(2, "0")}`;
      break;
    }
  }
  const amountLabels: Readonly<Record<string, string>> = {
    net_sales: "純 売 上",
    tax: "消 費 税",
    gross_sales: "総 売 上",
    avg_spend: "客単価",
    discount_total: "★割引合計",
    pay_total: "★支払合計",
    tax_out: " 外税",
    tax_in: " 内税",
  };
  for (let index = 0; index < lines.length; index += 1) {
    const line = lines[index];
    for (const [key, label] of Object.entries(amountLabels)) {
      if (!(key in output) && line.includes(label)) {
        const value = amount(line) ?? valueNear(lines, index, 1);
        if (value != null) output[key] = value;
      }
    }
    if (line.includes("会計組数・客数")) {
      for (
        let cursor = index;
        cursor < Math.min(index + 3, lines.length);
        cursor += 1
      ) {
        const groups = firstInt(lines[cursor], "組");
        const guests = firstInt(lines[cursor], "名");
        if (groups != null) output.groups = groups;
        if (guests != null) output.guests = guests;
      }
    }
    if (line.includes("店内飲食売上")) {
      for (
        let cursor = index;
        cursor < Math.min(index + 3, lines.length);
        cursor += 1
      ) {
        const items = firstInt(lines[cursor], "点");
        const sales = amount(lines[cursor]);
        if (items != null) output.dinein_items = items;
        if (sales != null) output.dinein_sales = sales;
      }
    }
  }
  const paymentBlock = (label: string): { count: number; amount: number } => {
    for (let index = 0; index < lines.length; index += 1) {
      if (!lines[index].includes(label)) continue;
      let count = 0;
      let value = 0;
      for (
        let cursor = index;
        cursor < Math.min(index + 3, lines.length);
        cursor += 1
      ) {
        const foundCount = firstInt(lines[cursor], "回");
        const foundAmount = amount(lines[cursor]);
        if (foundCount != null) count = foundCount;
        if (foundAmount != null) value = foundAmount;
      }
      return { count, amount: value };
    }
    return { count: 0, amount: 0 };
  };
  output.pay_cash = paymentBlock("現計");
  output.pay_credit = paymentBlock("クレジット計");
  output.pay_tabelog = paymentBlock("食べログ");
  output.pay_ikyu = paymentBlock("一休");
  output.pay_gurunavi = paymentBlock("ぐるなび");
  return output;
}

function parseWeather(record: JournalRecord): Record<string, unknown> {
  const output: Record<string, unknown> = {};
  for (const line of record.lines) {
    const weather = line.match(/天候\s*([^\s　]+)/);
    if (weather && !line.includes("入力") && weather[1] !== "入力") {
      output.weather = weather[1].trim();
    }
    const temperature = normalizeWide(line).match(/気温\s*(\d+)/);
    if (temperature) output.temp_c = Number(temperature[1]);
  }
  return output;
}

function normalizeSalePaymentLabel(value: unknown): string {
  const label = String(value ?? "").normalize("NFKC").trim();
  if (!label) return "";
  if (/^現計/.test(label)) return "現金";
  if (/クレジット/.test(label)) return "クレジット";
  if (/食べログ/.test(label)) return "食べログ";
  if (/一休/.test(label)) return "一休";
  if (/ぐるなび/.test(label)) return "ぐるなび";
  if (/QR\s*コード/i.test(label)) return "QRコード";
  if (/電子\s*マネ/.test(label)) return "電子マネー";
  if (/東京\s*ドーム\s*利/.test(label)) return "東京ドーム利用券";
  if (/ドーム\s*シティ\s*食事/.test(label)) return "ドームシティ食事券";
  if (/FOOD\s*STADIUM/i.test(label)) return "FOODSTADIUM利用券";
  if (/TD\s*ポイント/i.test(label)) return "TDポイントチケット";
  if (/^掛(?:計|支払|売)/.test(label)) return "掛売";
  return label.replace(/[\s　]+/g, " ").replace(/計$/, "").slice(0, 30);
}

function parseSale(record: JournalRecord): PosJournalReceipt | null {
  const text = record.lines.join("\n");
  const normalizedText = normalizeWide(text).normalize("NFKC");
  if (/オーダーキャンセル|未会計オーダー取消|取引中止/.test(normalizedText)) {
    return null;
  }
  const paymentBreakdown: Record<string, number> = {};
  for (const line of record.lines) {
    // 実POSは店舗ごとの任意支払区分（QR・電子マネー・商品券等）を
    // 「計N 支払名 \\金額」で出す。既知5種だけに限定すると会計全体が欠落する。
    const paymentLine = normalizeWide(line).normalize("NFKC").match(
      /^\s*計\d+\s+(.+?)\s+[\\¥￥]\s*(-?[\d,]+)\s*$/,
    );
    if (!paymentLine) continue;
    const method = normalizeSalePaymentLabel(paymentLine[1]);
    const paymentAmount = Number(paymentLine[2].replace(/,/g, ""));
    if (method && Number.isFinite(paymentAmount)) {
      paymentBreakdown[method] =
        (paymentBreakdown[method] || 0) + paymentAmount;
    }
  }
  const paymentMethods = Object.keys(paymentBreakdown).filter((method) =>
    paymentBreakdown[method] !== 0
  );
  const detectedPay = paymentMethods.length === 1
    ? paymentMethods[0]
    : (paymentMethods.length > 1 ? "複数" : "");
  const items: PosJournalReceiptItem[] = [];
  for (let index = 0; index < record.lines.length; index += 1) {
    const item = record.lines[index].match(ITEM_CODE_RE);
    if (!item || index + 1 >= record.lines.length) continue;
    const price = normalizeWide(record.lines[index + 1]).match(ITEM_PRICE_RE);
    if (!price) continue;
    items.push({
      code: item[1],
      name: item[2].trim(),
      unit: Number(price[1].replace(/,/g, "")),
      qty: Number(price[2].replace(/,/g, "")),
      amount: Number(price[3].replace(/,/g, "")),
    });
    index += 1;
  }
  for (let index = 0; index < record.lines.length; index += 1) {
    const label = normalizeWide(record.lines[index]).normalize("NFKC").trim();
    if (label !== "割引" && label !== "値引") continue;
    for (let next = index + 1; next < record.lines.length; next += 1) {
      const adjustmentLine = normalizeWide(record.lines[next]).normalize("NFKC")
        .trim();
      if (!adjustmentLine) continue;
      const adjustment = adjustmentLine.match(/[\\¥]?\s*(-?[\d,]+)\s*$/);
      if (adjustment) {
        const adjustmentAmount = Number(adjustment[1].replace(/,/g, ""));
        if (Number.isFinite(adjustmentAmount) && adjustmentAmount !== 0) {
          items.push({
            code: POS_JOURNAL_ADJUSTMENT_ITEM_CODE,
            name: label,
            unit: adjustmentAmount,
            qty: 1,
            amount: adjustmentAmount,
            category: "その他",
            isCharge: false,
          });
        }
      }
      break;
    }
  }
  if (!items.length) return null;
  let total: number | null = null;
  let guests: number | null = null;
  let tableNo = "";
  let change = 0;
  for (const line of record.lines) {
    const normalized = String(line || "").normalize("NFKC");
    if (/合\s*計\s/.test(line)) total = amount(line) ?? total;
    if (/お[\s　]*釣/.test(normalized)) change = amount(line) ?? change;
    guests = firstInt(line, "名") ?? guests;
    const table = normalized.match(
      /(?:伝票\s*No\.?\s*[^\s]+\s+)?テーブル\s*No\.?\s*([^\s]+)/,
    );
    if (table) {
      const tbl = String(table[1] || "").trim();
      if (tbl && !/^保留/.test(tbl) && tbl !== ".") tableNo = tbl;
    }
  }
  if (!detectedPay && total == null) return null;
  const pay = detectedPay || "支払情報なし";
  if (change && paymentBreakdown["現金"] != null) {
    paymentBreakdown["現金"] -= change;
  }
  if (!Object.keys(paymentBreakdown).length && total != null && total > 0) {
    paymentBreakdown["支払情報なし"] = total;
  }
  const voidRef = text.normalize("NFKC").match(
    /★\s*VOID\s+No\.?\s*(\d+)/i,
  )?.[1] ?? "";
  return {
    no: record.no,
    time: `${String(record.hh).padStart(2, "0")}:${
      String(record.mi).padStart(2, "0")
    }`,
    pay,
    total,
    guests,
    ...(tableNo ? { table_no: tableNo } : {}),
    ...(voidRef ? { void_ref: voidRef } : {}),
    payment_breakdown: paymentBreakdown,
    items,
  };
}

/** 取引変更のVOID控え自身と、参照された直前の元会計だけを除外する。 */
export function removeVoidedPosJournalReceipts(
  receipts: readonly PosJournalReceipt[],
): PosJournalReceipt[] {
  const list = Array.isArray(receipts) ? [...receipts] : [];
  const active = list.map(() => true);
  for (let index = 0; index < list.length; index += 1) {
    const voidRef = safeText(list[index]?.void_ref, 30);
    if (!voidRef) continue;
    active[index] = false;
    for (let prior = index - 1; prior >= 0; prior -= 1) {
      if (!active[prior]) continue;
      if (safeText(list[prior]?.no, 30) !== voidRef) continue;
      active[prior] = false;
      break;
    }
  }
  return list.filter((_receipt, index) => active[index]);
}

export function parsePosJournalLzh(
  bytes: Uint8Array,
  sourceFileName: string,
): PosJournalDay {
  const entries = extractLhaArchive(bytes);
  const texts = entries
    .filter((entry) => /\.jnl$/i.test(entry.fileName))
    .map((entry) => stripEscPos(entry.data));
  return parsePosJournalTexts(texts, sourceFileName);
}

function parsePosJournalTexts(
  texts: string[],
  sourceFileName: string,
): PosJournalDay {
  let settlement: Record<string, unknown> | null = null;
  let weather: Record<string, unknown> = {};
  const receipts: PosJournalReceipt[] = [];
  for (const text of texts) {
    for (const record of splitRecords(text)) {
      const body = record.lines.join("\n");
      if (body.includes("日計精算レポート") && !settlement) {
        settlement = parseSettlement(record);
      } else if (body.includes("天候入力")) {
        weather = { ...weather, ...parseWeather(record) };
      } else {
        const sale = parseSale(record);
        if (sale) receipts.push(sale);
      }
    }
  }
  if (!settlement || typeof settlement.business_date !== "string") {
    throw new Error("日計精算レポートまたは営業日付を読み取れませんでした。");
  }
  const activeReceipts = removeVoidedPosJournalReceipts(receipts);
  return {
    ...settlement,
    ...weather,
    business_date: String(settlement.business_date),
    payment_breakdown: aggregatePosJournalReceiptPayments(activeReceipts),
    receipts: activeReceipts,
    source: sourceFileName,
    parsed_complete: true,
    parser_version: POS_JOURNAL_REPORT_PARSER_VERSION,
  };
}

/** Tests and trusted import tools may parse already-decoded journal text. */
export function parsePosJournalText(
  text: string,
  sourceFileName: string,
): PosJournalDay {
  return parsePosJournalTexts([String(text ?? "")], sourceFileName);
}

export function detectPosJournalStoreCode(fileName: string): string {
  const match = String(fileName || "").match(/^(\d{4})/);
  return match?.[1] ?? "";
}

export function resolvePosJournalStore(
  storeCode: string,
): { storeKey: string; storeName: string } | null {
  return POS_JOURNAL_STORE_CODE_MAP[String(storeCode || "").trim()] ?? null;
}

const POS_JOURNAL_REPORT_WEEKDAYS = [
  "日",
  "月",
  "火",
  "水",
  "木",
  "金",
  "土",
] as const;

function journalWeekday(date: string): string {
  const match = date.match(/^(\d{4})-(\d{2})-(\d{2})$/);
  if (!match) return "";
  const parsed = new Date(
    Date.UTC(Number(match[1]), Number(match[2]) - 1, Number(match[3])),
  );
  return POS_JOURNAL_REPORT_WEEKDAYS[parsed.getUTCDay()] ?? "";
}

function safeIsoTimestamp(value: unknown): string {
  const s = String(value ?? "").trim();
  const d = s ? new Date(s) : new Date();
  return Number.isNaN(d.getTime()) ? new Date().toISOString() : d.toISOString();
}

function dateRangeLabel(days: PosJournalDay[]): string {
  if (!days.length) return "";
  return days.length === 1
    ? days[0].business_date
    : `${days[0].business_date} 〜 ${days[days.length - 1].business_date}`;
}

function journalReportId(
  storeKey: string,
  month: string,
  kind: "daily" | "monthly",
): string {
  return `pos_journal_auto_${String(storeKey || "").toLowerCase()}_${
    month.replace("-", "")
  }_${kind}`;
}

function paymentMethodRecord(
  day: PosJournalDay,
): Record<string, number> {
  const out: Record<string, number> = {};
  if (isRecord(day.payment_breakdown)) {
    for (const [rawLabel, rawBlock] of Object.entries(day.payment_breakdown)) {
      const label = normalizeSalePaymentLabel(rawLabel) || safeText(rawLabel, 30);
      const block = isRecord(rawBlock) ? rawBlock : {};
      const amount = safeNumber(block.amount);
      if (!label || !amount) continue;
      out[label] = (out[label] || 0) + amount;
    }
    if (Object.keys(out).length) return out;
  }
  const blocks: Array<[string, unknown]> = [
    ["現金", day.pay_cash],
    ["クレジット", day.pay_credit],
    ["食べログ", day.pay_tabelog],
    ["一休", day.pay_ikyu],
    ["ぐるなび", day.pay_gurunavi],
  ];
  for (const [label, raw] of blocks) {
    const block = isRecord(raw) ? raw : {};
    const amount = safeNumber(block.amount);
    if (amount) out[label] = amount;
  }
  return out;
}

function reconcilePosJournalReceipts(
  day: PosJournalDay,
): PosJournalReceipt[] {
  const receipts = removeVoidedPosJournalReceipts(
    Array.isArray(day.receipts) ? day.receipts : [],
  );
  if (!receipts.length) return []
  // VOIDの明示参照以外の近接・同内容heuristicは使わない。
  // 正常な別会計を誤って落とさず、合計不一致は上位の共通gateで日全体を除外する。
  return [...receipts].sort((a, b) =>
    safeText(a.time, 8).localeCompare(safeText(b.time, 8)) ||
    safeText(a.no, 30).localeCompare(safeText(b.no, 30))
  );
}

export type PosJournalDetailReconciliation = {
  /** 日計総売上・会計合計・各会計の商品合計が一致し、明細分析へ利用できる。 */
  detailComplete: boolean;
  reason:
    | "matched"
    | "gross_mismatch"
    | "item_mismatch"
    | "gross_and_item_mismatch";
  grossSales: number;
  rawReceiptCount: number;
  rawReceiptTotal: number;
  rawItemTotal: number;
  reconciledReceiptCount: number;
  reconciledReceiptTotal: number;
  reconciledItemTotal: number;
  itemMismatchReceiptCount: number;
  receipts: PosJournalReceipt[];
};

/**
 * 1営業日の会計明細を日計総売上へ照合する共通の安全境界。
 * 保存月報・商品インデックス・live商品検索・cohort比較は必ずこの結果だけを使う。
 * 一致できない元明細は監査用parsed_dataに残すが、確定明細としては返さない。
 */
export function reconcilePosJournalDayDetail(
  day: PosJournalDay,
): PosJournalDetailReconciliation {
  const rawReceipts = Array.isArray(day.receipts) ? day.receipts : [];
  const rawReceiptTotal = rawReceipts.reduce(
    (sum, receipt) => sum + safeNumber(receipt.total),
    0,
  );
  const rawItemTotal = rawReceipts.reduce(
    (sum, receipt) => sum + (Array.isArray(receipt.items)
      ? receipt.items.reduce(
        (itemSum, item) => itemSum + safeNumber(item.amount),
        0,
      )
      : 0),
    0,
  );
  const grossSales = safeNumber(day.gross_sales);
  const reconciled = reconcilePosJournalReceipts(day);
  const reconciledReceiptTotal = reconciled.reduce(
    (sum, receipt) => sum + safeNumber(receipt.total),
    0,
  );
  const reconciledItemTotal = reconciled.reduce(
    (sum, receipt) => sum + (Array.isArray(receipt.items)
      ? receipt.items.reduce(
        (itemSum, item) => itemSum + safeNumber(item.amount),
        0,
      )
      : 0),
    0,
  );
  const grossMatched = reconciledReceiptTotal === grossSales;
  const itemMismatchReceiptCount = reconciled.reduce((count, receipt) => {
    const items = Array.isArray(receipt.items) ? receipt.items : [];
    const itemTotal = items.reduce(
      (sum, item) => sum + safeNumber(item.amount),
      0,
    );
    return count + (items.length > 0 && itemTotal === safeNumber(receipt.total)
      ? 0
      : 1);
  }, 0);
  const itemsMatched = itemMismatchReceiptCount === 0;
  const detailComplete = grossMatched && itemsMatched;
  const reason = grossMatched
    ? (itemsMatched ? "matched" : "item_mismatch")
    : (itemsMatched ? "gross_mismatch" : "gross_and_item_mismatch");
  return {
    detailComplete,
    reason,
    grossSales,
    rawReceiptCount: rawReceipts.length,
    rawReceiptTotal,
    rawItemTotal,
    reconciledReceiptCount: detailComplete ? reconciled.length : 0,
    reconciledReceiptTotal,
    reconciledItemTotal,
    itemMismatchReceiptCount,
    receipts: detailComplete ? reconciled : [],
  };
}

function allocateDayPaymentsToSales(
  day: PosJournalDay,
  sales: JournalSavedReportSale[],
): void {
  if (!sales.length) return;
  const alreadyComplete = sales.every((sale) => {
    const byMethod = isRecord(sale.payments?.byMethod)
      ? sale.payments.byMethod
      : {};
    const allocated = Object.values(byMethod).reduce(
      (sum, amount) => sum + safeNumber(amount),
      0,
    );
    return Object.keys(byMethod).length > 0 && allocated === sale.total;
  });
  if (alreadyComplete) return;
  const targets = paymentMethodRecord(day);
  const targetEntries = Object.entries(targets).filter(([, amount]) =>
    amount !== 0
  );
  const targetTotal = targetEntries.reduce((sum, [, amount]) => sum + amount, 0);
  const salesTotal = sales.reduce((sum, sale) => sum + sale.total, 0);
  if (!targetEntries.length || targetTotal !== salesTotal) return;
  const remaining = new Map(targetEntries);
  for (const sale of sales) {
    let need = sale.total;
    const allocation: Record<string, number> = {};
    const order = [
      sale.method,
      ...targetEntries.map(([method]) => method).filter((method) =>
        method !== sale.method
      ),
    ];
    for (const method of order) {
      const available = remaining.get(method) || 0;
      if (!available || !need) continue;
      const amount = Math.min(available, need);
      allocation[method] = (allocation[method] || 0) + amount;
      remaining.set(method, available - amount);
      need -= amount;
    }
    if (need) allocation["その他"] = (allocation["その他"] || 0) + need;
    const methods = Object.keys(allocation).filter((method) =>
      allocation[method] !== 0
    );
    sale.method = methods.length === 1 ? methods[0] : "併用";
    sale.payments = {
      byMethod: allocation,
      total: sale.total,
      change: 0,
      details: methods.map((method) => ({
        label: method,
        method,
        amount: allocation[method],
      })),
    };
  }
}

function allocateDayTaxToSales(
  day: PosJournalDay,
  sales: JournalSavedReportSale[],
): void {
  if (!sales.length) return;
  const dayTax = safeNumber(day.tax);
  const total = sales.reduce((sum, sale) => sum + sale.total, 0);
  let assigned = 0;
  sales.forEach((sale, index) => {
    const tax = index === sales.length - 1
      ? dayTax - assigned
      : total
      ? Math.round(dayTax * sale.total / total)
      : 0;
    sale.tax = tax;
    assigned += tax;
  });
}

export function buildJournalSavedReportsFromPosDays(params: {
  storeKey: string;
  storeName: string;
  storeCode: string;
  month: string;
  days: PosJournalDay[];
  journalIds?: number[];
  categoryOverrides?: Record<string, unknown>;
  /** 店舗ごとのコード範囲。未指定ならコード内の既定値を使う。 */
  categoryRules?: PosJournalCategoryRules | null;
  createdAt?: string;
}): Array<{
  id: string;
  title: string;
  period: string;
  data: JournalSavedReportData;
}> {
  const month = String(params.month ?? "").trim();
  if (!/^\d{4}-(0[1-9]|1[0-2])$/.test(month)) return [];
  const dayMap = new Map<string, PosJournalDay>();
  for (const day of Array.isArray(params.days) ? params.days : []) {
    if (
      !/^\d{4}-\d{2}-\d{2}$/.test(day.business_date) ||
      day.business_date.slice(0, 7) !== month
    ) continue;
    dayMap.set(day.business_date, day);
  }
  const days = [...dayMap.values()].sort((a, b) =>
    a.business_date.localeCompare(b.business_date)
  );
  if (!days.length) return [];

  const overrides = isRecord(params.categoryOverrides)
    ? params.categoryOverrides
    : {};
  const sales: JournalSavedReportSale[] = [];
  const reportDays: PosJournalDay[] = [];
  const weatherByDate: Record<
    string,
    { weather: string; tempC: number | null }
  > = {};
  for (const day of days) {
    const daySaleStart = sales.length;
    const weather = safeText(day.weather, 30);
    const temperature = parsePosJournalTempC(day.temp_c, weather);
    if (weather || temperature != null) {
      weatherByDate[day.business_date] = {
        weather,
        tempC: temperature,
      };
    }
    const dayPayments = paymentMethodRecord(day);
    const detail = reconcilePosJournalDayDetail(day);
    const reconciledReceipts = detail.receipts;
    const targetDayTotal = detail.grossSales;
    // 日計と会計合計を一致させられない日は、誤った明細を確定値として保存しない。
    // 日計サマリー1件へ安全に退避し、元の生解析はpos_journal_filesに保持する。
    for (let index = 0; index < reconciledReceipts.length; index += 1) {
      const receipt = reconciledReceipts[index];
      const timeMatch = String(receipt.time ?? "").match(
        /^([01]?\d|2[0-3]):([0-5]\d)$/,
      );
      const hour = timeMatch ? Number(timeMatch[1]) : -1;
      const minute = timeMatch ? Number(timeMatch[2]) : -1;
      const hasAccountingTime = hour >= 0 && minute >= 0;
      const mealPeriod = hasAccountingTime
        ? ((hour * 60 + minute < 16 * 60) ? "ランチ" : "ディナー")
        : "";
      const items: JournalSavedReportSaleItem[] = (receipt.items || []).map(
        (item) => {
        const classification = classifyPosJournalReportItem(
          item.code,
          overrides,
          item.name,
          params.categoryRules ?? null,
        );
        return {
          code: safeText(item.code, 24),
          name: safeText(item.name, 120),
          qty: safeNumber(item.qty),
          amount: safeNumber(item.amount),
          ...classification,
        };
      }).filter((item) => item.name && (item.qty !== 0 || item.amount !== 0));
      const total = receipt.total == null
        ? items.reduce((sum, item) => sum + item.amount, 0)
        : safeNumber(receipt.total);
      const itemTotalBeforeAdjustment = items.reduce(
        (sum, item) => sum + item.amount,
        0,
      );
      const itemAdjustment = total - itemTotalBeforeAdjustment;
      if (itemAdjustment) {
        items.push({
          code: "__journal_adjustment__",
          name: "会計値調整",
          qty: 1,
          amount: itemAdjustment,
          category: "その他",
          isCharge: false,
          known: true,
          byCode: false,
          needsReview: false,
        });
      }
      const guests = receipt.guests == null ? 0 : safeNumber(receipt.guests);
      const byMethod = resolvePosJournalReceiptPayments(receipt);
      const methods = Object.keys(byMethod);
      const pay = methods.length === 1 ? methods[0] : "併用";
      const paymentAmount = Object.values(byMethod).reduce(
        (sum, amount) => sum + amount,
        0,
      );
      sales.push({
        no: safeText(receipt.no, 30) ||
          `${day.business_date.replace(/-/g, "")}-${index + 1}`,
        date: day.business_date,
        weekday: journalWeekday(day.business_date),
        hour,
        minute,
        hasAccountingTime,
        mealPeriod,
        time: hasAccountingTime
          ? `${String(hour).padStart(2, "0")}:${
            String(minute).padStart(2, "0")
          }`
          : "",
        total,
        tax: 0,
        points: 0,
        groups: 1,
        customers: guests,
        customerCountReliable: guests > 0,
        isSplitFragment: false,
        tableNo: safeText(receipt.table_no, 50),
        method: pay,
        change: 0,
        weather,
        tempC: Number.isFinite(temperature) ? temperature : null,
        payments: {
          byMethod,
          total: paymentAmount,
          change: 0,
          details: methods.map((method) => ({
            label: method,
            method,
            amount: byMethod[method],
          })),
        },
        items,
        itemTotal: items.reduce((sum, item) => sum + item.amount, 0),
      });
    }
    let daySales = sales.slice(daySaleStart);
    if (daySales.length) {
      // 日計サマリーを客数・組数・税の正本にする。割勘控え等で
      // レシート件数と組数が一致しない場合も、保存レポートは日計値へ合わせる。
      daySales.forEach((sale) => {
        sale.tax = 0;
        sale.groups = 0;
      });
      daySales[0].tax = safeNumber(day.tax);
      const targetGroups = Math.max(0, Math.round(safeNumber(day.groups)));
      for (
        let index = 0;
        index < Math.min(targetGroups, daySales.length);
        index += 1
      ) {
        daySales[index].groups = 1;
      }
      if (targetGroups > daySales.length) {
        daySales[0].groups += targetGroups - daySales.length;
      }
      const targetGuests = Math.max(0, Math.round(safeNumber(day.guests)));
      let guestDiff = targetGuests -
        daySales.reduce((sum, sale) => sum + sale.customers, 0);
      if (guestDiff > 0) {
        daySales[0].customers += guestDiff;
      } else if (guestDiff < 0) {
        let remaining = -guestDiff;
        for (const sale of daySales) {
          const take = Math.min(sale.customers, remaining);
          sale.customers -= take;
          remaining -= take;
          if (!remaining) break;
        }
      }
      daySales.forEach((sale) => {
        sale.customerCountReliable = sale.customers > 0;
      });
      allocateDayTaxToSales(day, daySales);
      allocateDayPaymentsToSales(day, daySales);
    }
    // 会計明細が無いプレースホルダでも、日計値は共有スナップショットに残す。
    if (!daySales.length && safeNumber(day.gross_sales) > 0) {
      const total = safeNumber(day.gross_sales);
      const paymentEntries = Object.entries(dayPayments);
      const pay = paymentEntries.length === 1
        ? paymentEntries[0][0]
        : paymentEntries.length > 1
        ? "併用"
        : "その他";
      sales.push({
        no: `summary-${day.business_date}`,
        date: day.business_date,
        weekday: journalWeekday(day.business_date),
        hour: -1,
        minute: -1,
        hasAccountingTime: false,
        mealPeriod: "",
        time: "",
        total,
        tax: safeNumber(day.tax),
        points: 0,
        groups: safeNumber(day.groups),
        customers: safeNumber(day.guests),
        customerCountReliable: safeNumber(day.guests) > 0,
        isSplitFragment: false,
        tableNo: "",
        method: pay,
        change: 0,
        weather,
        tempC: Number.isFinite(temperature) ? temperature : null,
        payments: {
          byMethod: paymentEntries.length ? dayPayments : { その他: total },
          total: paymentEntries.length
            ? paymentEntries.reduce((sum, [, value]) => sum + value, 0)
            : total,
          change: 0,
          details: paymentEntries.map(([label, amount]) => ({
            label,
            method: label,
            amount,
          })),
        },
        items: [],
        itemTotal: 0,
      });
    }
    daySales = sales.slice(daySaleStart);
    reportDays.push({
      business_date: day.business_date,
      source: safeText(day.source, 180) || "pos_journal_upload",
      net_sales: safeNumber(day.net_sales),
      tax: safeNumber(day.tax),
      gross_sales: safeNumber(day.gross_sales),
      groups: safeNumber(day.groups),
      guests: safeNumber(day.guests),
      avg_spend: safeNumber(day.avg_spend),
      pay_cash: isRecord(day.pay_cash)
        ? {
          count: safeNumber(day.pay_cash.count),
          amount: safeNumber(day.pay_cash.amount),
        }
        : { count: 0, amount: 0 },
      pay_credit: isRecord(day.pay_credit)
        ? {
          count: safeNumber(day.pay_credit.count),
          amount: safeNumber(day.pay_credit.amount),
        }
        : { count: 0, amount: 0 },
      pay_tabelog: isRecord(day.pay_tabelog)
        ? {
          count: safeNumber(day.pay_tabelog.count),
          amount: safeNumber(day.pay_tabelog.amount),
        }
        : { count: 0, amount: 0 },
      pay_ikyu: isRecord(day.pay_ikyu)
        ? {
          count: safeNumber(day.pay_ikyu.count),
          amount: safeNumber(day.pay_ikyu.amount),
        }
        : { count: 0, amount: 0 },
      pay_gurunavi: isRecord(day.pay_gurunavi)
        ? {
          count: safeNumber(day.pay_gurunavi.count),
          amount: safeNumber(day.pay_gurunavi.amount),
        }
        : { count: 0, amount: 0 },
      payment_breakdown: aggregatePosJournalReceiptPayments(
        daySales.map((sale) => ({
          no: sale.no,
          time: sale.time,
          pay: sale.method,
          total: sale.total,
          guests: sale.customers,
          payment_breakdown: sale.payments.byMethod,
          items: [],
        })),
      ),
      weather: safeText(day.weather, 30),
      temp_c: Number.isFinite(Number(day.temp_c)) ? Number(day.temp_c) : null,
      receipts: daySales.map((sale) => ({
        no: sale.no,
        time: sale.time,
        pay: sale.method,
        total: sale.total,
        guests: sale.customers,
        payment_breakdown: { ...sale.payments.byMethod },
        ...(sale.tableNo ? { table_no: sale.tableNo } : {}),
        items: sale.items.map((item) => ({
          code: item.code,
          name: item.name,
          unit: item.qty ? Math.round(item.amount / item.qty) : 0,
          qty: item.qty,
          amount: item.amount,
        })),
      })),
    });
  }
  sales.sort((a, b) =>
    a.date.localeCompare(b.date) ||
    a.time.localeCompare(b.time) ||
    a.no.localeCompare(b.no)
  );

  const total = days.reduce((sum, day) => sum + safeNumber(day.gross_sales), 0);
  const tax = days.reduce((sum, day) => sum + safeNumber(day.tax), 0);
  const totalCustomers = days.reduce(
    (sum, day) => sum + safeNumber(day.guests),
    0,
  );
  const totalGroups = days.reduce((sum, day) => sum + safeNumber(day.groups), 0);
  const categoryTotals: Record<PosJournalPrimaryCategory, number> = {
    "フード": 0,
    "飲料": 0,
    "室料": 0,
    "その他": 0,
  };
  // 画面の切替表示用。実際に割り当てられた粒度(細分類が付いていれば細分類)で
  // 積む。大分類の合計は上の categoryTotals が正で、こちらは内訳にすぎない。
  const categoryBreakdown: Record<string, number> = {};
  const mealCategoryTotals = {
    lunchTotal: 0,
    dinnerTotal: 0,
    lunchCustomers: 0,
    dinnerCustomers: 0,
    lunchFoodTotal: 0,
    lunchDrinkTotal: 0,
    dinnerFoodTotal: 0,
    dinnerDrinkTotal: 0,
  };
  let chargeTotal = 0;
  const productMap = new Map<
    string,
    { name: string; qty: number; amt: number; category: string }
  >();
  const weekdayMap = new Map<
    string,
    { totalSales: number; transactionCount: number; customerCount: number }
  >();
  const hourlyMap = new Map<
    number,
    { totalSales: number; count: number; customers: number }
  >();
  const dailyMap = new Map<
    string,
    { total: number; food: number; drink: number; groups: number; customers: number }
  >();
  for (const sale of sales) {
    const daily = dailyMap.get(sale.date) ??
      { total: 0, food: 0, drink: 0, groups: 0, customers: 0 };
    daily.total += sale.total;
    daily.groups += sale.groups;
    daily.customers += sale.customers;
    for (const item of sale.items) {
      // 細分類が入っていても、合計は必ず大分類へ寄せる。
      const primary = posJournalPrimaryCategory(item.category);
      categoryTotals[primary] += item.amount;
      const assigned = String(item.category ?? "").trim() || primary;
      categoryBreakdown[assigned] = (categoryBreakdown[assigned] ?? 0) +
        item.amount;
      if (primary === "フード") daily.food += item.amount;
      if (primary === "飲料") daily.drink += item.amount;
      if (item.isCharge) chargeTotal += item.amount;
      if (!isPosJournalAdjustmentItem(item)) {
        const product = productMap.get(item.name) ??
          { name: item.name, qty: 0, amt: 0, category: item.category };
        product.qty += item.qty;
        product.amt += item.amount;
        productMap.set(item.name, product);
      }
      if (sale.mealPeriod === "ランチ") {
        if (primary === "フード") {
          mealCategoryTotals.lunchFoodTotal += item.amount;
        } else if (primary === "飲料") {
          mealCategoryTotals.lunchDrinkTotal += item.amount;
        }
      } else if (sale.mealPeriod === "ディナー") {
        if (primary === "フード") {
          mealCategoryTotals.dinnerFoodTotal += item.amount;
        } else if (primary === "飲料") {
          mealCategoryTotals.dinnerDrinkTotal += item.amount;
        }
      }
    }
    dailyMap.set(sale.date, daily);
    if (sale.mealPeriod === "ランチ") {
      mealCategoryTotals.lunchTotal += sale.total;
      mealCategoryTotals.lunchCustomers += sale.customers;
    } else if (sale.mealPeriod === "ディナー") {
      mealCategoryTotals.dinnerTotal += sale.total;
      mealCategoryTotals.dinnerCustomers += sale.customers;
    }
    const weekday = sale.weekday || journalWeekday(sale.date);
    const weekdayRow = weekdayMap.get(weekday) ??
      { totalSales: 0, transactionCount: 0, customerCount: 0 };
    weekdayRow.totalSales += sale.total;
    weekdayRow.transactionCount += 1;
    weekdayRow.customerCount += sale.customers;
    weekdayMap.set(weekday, weekdayRow);
    if (sale.hour >= 0) {
      const hourly = hourlyMap.get(sale.hour) ??
        { totalSales: 0, count: 0, customers: 0 };
      hourly.totalSales += sale.total;
      hourly.count += 1;
      hourly.customers += sale.customers;
      hourlyMap.set(sale.hour, hourly);
    }
  }
  const categorized = Object.values(categoryTotals).reduce(
    (sum, value) => sum + value,
    0,
  );
  if (categorized !== total) {
    categoryTotals["その他"] += total - categorized;
  }
  const reportMonthLabel = `${Number(month.slice(0, 4))}年${
    Number(month.slice(5, 7))
  }月`;
  const createdAt = safeIsoTimestamp(params.createdAt);
  const journalIds = [...new Set(
    (params.journalIds || []).map(Number).filter((id) =>
      Number.isSafeInteger(id) && id > 0
    ),
  )];
  const topProducts = [...productMap.values()]
    .filter((item) => item.qty > 0 && item.amt >= 0)
    .sort((a, b) =>
      b.amt - a.amt || b.qty - a.qty || a.name.localeCompare(b.name, "ja")
    ).slice(0, 30);
  const weekdayBreakdown = [...weekdayMap.entries()]
    .map(([weekday, value]) => ({
      weekday,
      ...value,
      avgSpend: value.customerCount
        ? Math.round(value.totalSales / value.customerCount)
        : 0,
    }))
    .sort((a, b) =>
      POS_JOURNAL_REPORT_WEEKDAYS.indexOf(
        a.weekday as typeof POS_JOURNAL_REPORT_WEEKDAYS[number],
      ) -
      POS_JOURNAL_REPORT_WEEKDAYS.indexOf(
        b.weekday as typeof POS_JOURNAL_REPORT_WEEKDAYS[number],
      )
    );
  const hourlyBreakdown = [...hourlyMap.entries()].map(([hour, value]) => ({
    hour,
    ...value,
  })).sort((a, b) => a.hour - b.hour);
  const dailyBreakdown = [...dailyMap.entries()].map(([date, value]) => ({
    date,
    ...value,
  })).sort((a, b) => a.date.localeCompare(b.date));
  const period = dateRangeLabel(days);
  const baseData: Omit<JournalSavedReportData, "id" | "title"> = {
    period,
    createdAt,
    salesCount: sales.length,
    total,
    totalSales: total,
    categoryBreakdown,
    foodTotal: categoryTotals["フード"],
    drinkTotal: categoryTotals["飲料"],
    roomTotal: categoryTotals["室料"],
    otherTotal: categoryTotals["その他"],
    chargeTotal,
    ...mealCategoryTotals,
    totalCustomers,
    totalGroups,
    topProducts,
    weekdayBreakdown,
    hourlyBreakdown,
    dailyBreakdown,
    parserVersion: POS_JOURNAL_REPORT_PARSER_VERSION,
    verificationVersion: POS_JOURNAL_REPORT_VERIFICATION_VERSION,
    categoryVersion: POS_JOURNAL_REPORT_CATEGORY_VERSION,
    mealPeriodVersion: POS_JOURNAL_REPORT_MEAL_PERIOD_VERSION,
    sourceMonths: [month],
    journalIds,
    weatherByDate,
    posJournalDays: reportDays,
    sales,
    autoGeneratedFromPosJournal: true,
    autoGeneratedAt: createdAt,
  };
  return (["daily", "monthly"] as const).map((kind) => {
    const id = journalReportId(params.storeKey, month, kind);
    const title = kind === "daily"
      ? `日別売上レポート（${reportMonthLabel}）`
      : `月間売上レポート（${reportMonthLabel}）`;
    return {
      id,
      title,
      period,
      data: { ...baseData, id, title },
    };
  });
}

function sumDays(days: PosJournalDay[], key: string): number {
  return days.reduce((sum, day) => sum + (Number(day[key]) || 0), 0);
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return !!value && typeof value === "object" && !Array.isArray(value);
}

function safeNumber(value: unknown): number {
  const n = Number(value);
  return Number.isFinite(n) ? n : 0;
}

function safeText(value: unknown, maxLength = 180): string {
  return String(value ?? "").normalize("NFKC").replace(
    /[\u0000-\u001f\u007f]/g,
    " ",
  ).replace(/\s+/g, " ").trim().slice(0, maxLength);
}

/**
 * 会計内の支払方法別純額を検算して返す。
 * 旧解析版で「複数」へ潰れている場合は推測で配分せず、未捕捉として保持する。
 */
export function resolvePosJournalReceiptPayments(
  receipt: Pick<PosJournalReceipt, "pay" | "total" | "payment_breakdown">,
): Record<string, number> {
  const total = safeNumber(receipt.total);
  if (total <= 0) return {};
  const normalized: Record<string, number> = {};
  if (isRecord(receipt.payment_breakdown)) {
    for (const [rawLabel, rawAmount] of Object.entries(
      receipt.payment_breakdown,
    )) {
      const label = normalizeSalePaymentLabel(rawLabel) || safeText(rawLabel, 30);
      const amount = safeNumber(rawAmount);
      if (!label || amount <= 0) continue;
      normalized[label] = (normalized[label] || 0) + amount;
    }
  }
  const normalizedTotal = Object.values(normalized).reduce(
    (sum, amount) => sum + amount,
    0,
  );
  if (Object.keys(normalized).length && normalizedTotal === total) {
    return normalized;
  }
  const fallback = normalizeSalePaymentLabel(receipt.pay) ||
    safeText(receipt.pay, 30);
  if (
    fallback &&
    !/^(?:複数|併用|その他|不明)$/.test(fallback)
  ) {
    return { [fallback]: total };
  }
  return { "支払明細未捕捉": total };
}

function aggregatePosJournalReceiptPayments(
  receipts: readonly PosJournalReceipt[],
): Record<string, { count: number; amount: number }> {
  const output: Record<string, { count: number; amount: number }> = {};
  for (const receipt of receipts) {
    for (const [method, amount] of Object.entries(
      resolvePosJournalReceiptPayments(receipt),
    )) {
      const current = output[method] ?? { count: 0, amount: 0 };
      current.count += 1;
      current.amount += amount;
      output[method] = current;
    }
  }
  return output;
}

function paymentNameFromJournalReportSale(sale: JournalReportSaleLike): string {
  const byMethod = isRecord(sale.payments) && isRecord(sale.payments.byMethod)
    ? sale.payments.byMethod
    : {};
  const positive = Object.entries(byMethod)
    .filter(([, amount]) => safeNumber(amount) > 0)
    .sort((a, b) => safeNumber(b[1]) - safeNumber(a[1]));
  if (positive.length === 1) return safeText(positive[0][0], 30) || "不明";
  if (positive.length > 1) return "併用";
  return safeText(sale.method ?? sale.pay, 30) || "不明";
}

function journalReportReceipt(
  value: unknown,
  index: number,
): PosJournalReceipt | null {
  if (!isRecord(value)) return null;
  const sale = value as JournalReportSaleLike;
  const items = (Array.isArray(sale.items) ? sale.items : [])
    .map((item) => {
      if (!isRecord(item)) return null;
      const name = safeText(item.name, 120);
      if (!name) return null;
      const categoryText = safeText(item.category, 20);
      const category =
        (POS_JOURNAL_REPORT_CATEGORIES as readonly string[]).includes(
            categoryText,
          )
          ? categoryText as PosJournalReportCategory
          : undefined;
      return {
        code: safeText(item.code, 24),
        name,
        unit: safeNumber(item.unit) ||
          (safeNumber(item.qty) ? Math.round(safeNumber(item.amount) / safeNumber(item.qty)) : 0),
        qty: safeNumber(item.qty),
        amount: safeNumber(item.amount),
        ...(category ? { category } : {}),
        ...(item.isCharge === true ? { isCharge: true } : {}),
      };
    })
    .filter((item): item is PosJournalReceiptItem => item !== null);
  const rawTotal = Number(sale.total);
  const rawGuests = Number(sale.customers ?? sale.guests);
  const tableNo = safeText(sale.tableNo ?? sale.table_no, 50);
  const rawByMethod = isRecord(sale.payments) &&
      isRecord(sale.payments.byMethod)
    ? sale.payments.byMethod
    : isRecord(sale.payment_breakdown)
    ? sale.payment_breakdown
    : {};
  const paymentBreakdown: Record<string, number> = {};
  for (const [rawLabel, rawAmount] of Object.entries(rawByMethod)) {
    const label = normalizeSalePaymentLabel(rawLabel) || safeText(rawLabel, 30);
    const amount = safeNumber(rawAmount);
    if (label && amount > 0) {
      paymentBreakdown[label] = (paymentBreakdown[label] || 0) + amount;
    }
  }
  return {
    no: safeText(sale.no, 30) || `shared-${index + 1}`,
    time: safeText(sale.time, 8),
    pay: paymentNameFromJournalReportSale(sale),
    total: Number.isFinite(rawTotal) ? rawTotal : null,
    guests: Number.isFinite(rawGuests) ? rawGuests : null,
    ...(tableNo ? { table_no: tableNo } : {}),
    ...(Object.keys(paymentBreakdown).length
      ? { payment_breakdown: paymentBreakdown }
      : {}),
    items,
  };
}

/**
 * Journal Report の保存済みレポート（saved_reports.data）を
 * POS電子ジャーナル画面が扱う日次形式へ変換する。
 *
 * 原本LZHを複製せず、認証済み admin-api 内で共有参照するための変換。
 * 月間レポートは同じ月の全伝票を持つため、新しい保存行から日付ごとに
 * 初出の伝票だけを採用し、日別・月間の重複を二重計上しない。
 */
export function buildPosJournalDaysFromSavedReports(
  reports: Array<{ id?: unknown; data?: unknown; created_at?: unknown }>,
  month: string,
): PosJournalDay[] {
  if (!/^\d{4}-(0[1-9]|1[0-2])$/.test(month)) return [];
  const dayMap = new Map<string, PosJournalDay>();
  const rows = [...(Array.isArray(reports) ? reports : [])].sort((a, b) =>
    String(b.created_at ?? "").localeCompare(String(a.created_at ?? ""))
  );
  for (const row of rows) {
    const data = isRecord(row.data) ? row.data as JournalReportDataLike : {};
    const sharedDays = Array.isArray(data.posJournalDays)
      ? data.posJournalDays
      : [];
    for (const value of sharedDays) {
      if (!isRecord(value)) continue;
      const date = String(value.business_date ?? "").slice(0, 10);
      if (
        !/^\d{4}-\d{2}-\d{2}$/.test(date) ||
        date.slice(0, 7) !== month ||
        dayMap.has(date)
      ) {
        continue;
      }
      const receipts = (Array.isArray(value.receipts) ? value.receipts : [])
        .map(journalReportReceipt)
        .filter((receipt): receipt is PosJournalReceipt => receipt !== null);
      const paymentBlock = (
        key: string,
      ): { count: number; amount: number } => {
        const block = isRecord(value[key]) ? value[key] : {};
        return {
          count: safeNumber(block.count),
          amount: safeNumber(block.amount),
        };
      };
      dayMap.set(date, {
        business_date: date,
        source: safeText(value.source, 180) ||
          `saved_report:${safeText(row.id, 120) || "shared"}`,
        net_sales: safeNumber(value.net_sales),
        tax: safeNumber(value.tax),
        gross_sales: safeNumber(value.gross_sales),
        groups: safeNumber(value.groups),
        guests: safeNumber(value.guests),
        avg_spend: safeNumber(value.avg_spend),
        pay_cash: paymentBlock("pay_cash"),
        pay_credit: paymentBlock("pay_credit"),
        pay_tabelog: paymentBlock("pay_tabelog"),
        pay_ikyu: paymentBlock("pay_ikyu"),
        pay_gurunavi: paymentBlock("pay_gurunavi"),
        payment_breakdown: isRecord(value.payment_breakdown)
          ? value.payment_breakdown
          : aggregatePosJournalReceiptPayments(receipts),
        weather: safeText(value.weather, 30),
        temp_c: parsePosJournalTempC(
          value.temp_c ?? value.tempC,
          value.weather,
        ),
        receipts,
      });
    }
    const sales = Array.isArray(data.sales) ? data.sales : [];
    if (!sales.length) continue;
    const byDate = new Map<string, JournalReportSaleLike[]>();
    for (const sale of sales) {
      if (!isRecord(sale)) continue;
      const date = String(sale.date ?? "").slice(0, 10);
      if (!/^\d{4}-\d{2}-\d{2}$/.test(date) || date.slice(0, 7) !== month) {
        continue;
      }
      const list = byDate.get(date) ?? [];
      list.push(sale as JournalReportSaleLike);
      byDate.set(date, list);
    }
    const weatherByDate = isRecord(data.weatherByDate) ? data.weatherByDate : {};
    for (const [date, daySales] of byDate) {
      if (dayMap.has(date)) continue;
      const receipts = daySales.map(journalReportReceipt).filter(
        (receipt): receipt is PosJournalReceipt => receipt !== null,
      );
      const gross = daySales.reduce((sum, sale) => sum + safeNumber(sale.total), 0);
      const tax = daySales.reduce((sum, sale) => sum + safeNumber(sale.tax), 0);
      const guests = daySales.reduce(
        (sum, sale) => sum + safeNumber(sale.customers ?? sale.guests),
        0,
      );
      const groups = daySales.reduce(
        (sum, sale) =>
          sum +
          (sale.groups != null
            ? safeNumber(sale.groups)
            : sale.isSplitFragment === true
            ? 0
            : 1),
        0,
      );
      const paymentTotals = new Map<string, { count: number; amount: number }>();
      for (const sale of daySales) {
        const payments = isRecord(sale.payments) && isRecord(sale.payments.byMethod)
          ? sale.payments.byMethod
          : null;
        if (payments) {
          for (const [name, value] of Object.entries(payments)) {
            const amount = safeNumber(value);
            if (!amount) continue;
            const current = paymentTotals.get(name) ?? { count: 0, amount: 0 };
            current.count += 1;
            current.amount += amount;
            paymentTotals.set(name, current);
          }
        } else {
          const name = paymentNameFromJournalReportSale(sale);
          const current = paymentTotals.get(name) ?? { count: 0, amount: 0 };
          current.count += 1;
          current.amount += safeNumber(sale.total);
          paymentTotals.set(name, current);
        }
      }
      const weatherRow = isRecord(weatherByDate[date]) ? weatherByDate[date] : {};
      const saleWeather = daySales.find((sale) => safeText(sale.weather, 30));
      const saleTemp = daySales.find((sale) =>
        parsePosJournalTempC(sale.tempC ?? sale.temp_c, sale.weather) != null
      );
      const day: PosJournalDay = {
        business_date: date,
        source: `saved_report:${safeText(row.id, 120) || "shared"}`,
        net_sales: Math.max(0, gross - tax),
        tax,
        gross_sales: gross,
        groups,
        guests,
        avg_spend: guests ? Math.round(gross / guests) : 0,
        pay_cash: paymentTotals.get("現金") ?? { count: 0, amount: 0 },
        pay_credit: paymentTotals.get("クレジット") ?? { count: 0, amount: 0 },
        pay_tabelog: paymentTotals.get("食べログ") ?? { count: 0, amount: 0 },
        pay_ikyu: paymentTotals.get("一休") ?? { count: 0, amount: 0 },
        pay_gurunavi: paymentTotals.get("ぐるなび") ?? { count: 0, amount: 0 },
        payment_breakdown: Object.fromEntries(paymentTotals),
        weather: safeText(weatherRow.weather ?? saleWeather?.weather, 30),
        temp_c: parsePosJournalTempC(
          weatherRow.tempC ?? weatherRow.temp_c,
          weatherRow.weather ?? saleWeather?.weather,
        ) ?? parsePosJournalTempC(
          saleTemp?.tempC ?? saleTemp?.temp_c,
          saleTemp?.weather,
        ),
        receipts,
      };
      dayMap.set(date, day);
    }
  }
  return [...dayMap.values()].sort((a, b) =>
    a.business_date.localeCompare(b.business_date)
  );
}

export function pickBestJournalSavedReportDays(
  reports: Array<{ id?: unknown; data?: unknown; created_at?: unknown }>,
  month: string,
): PosJournalDay[] {
  const reportList = Array.isArray(reports) ? reports : [];
  const candidates = reportList.map((report, index) => {
    const days = buildPosJournalDaysFromSavedReports([report], month);
    return {
      days,
      dayCount: days.length,
      gross: days.reduce((sum, day) => sum + safeNumber(day.gross_sales), 0),
      receipts: days.reduce(
        (sum, day) => sum + (Array.isArray(day.receipts) ? day.receipts.length : 0),
        0,
      ),
      index,
    };
  });
  const bestIndividual = candidates
    .filter((candidate) => candidate.dayCount > 0)
    .sort((a, b) =>
      b.dayCount - a.dayCount ||
      b.gross - a.gross ||
      b.receipts - a.receipts ||
      a.index - b.index
    )[0];
  // 月間レポートが無く、日別レポートが複数行に分かれている旧データも
  // 営業日単位で統合する。ただし既存の最広レポートと同じ日数なら、
  // 新しい部分断片で完全月の同一日を上書きしない。
  const mergedDays = buildPosJournalDaysFromSavedReports(reportList, month);
  if (mergedDays.length > (bestIndividual?.dayCount ?? 0)) {
    candidates.push({
      days: mergedDays,
      dayCount: mergedDays.length,
      gross: mergedDays.reduce(
        (sum, day) => sum + safeNumber(day.gross_sales),
        0,
      ),
      receipts: mergedDays.reduce(
        (sum, day) =>
          sum + (Array.isArray(day.receipts) ? day.receipts.length : 0),
        0,
      ),
      index: reportList.length,
    });
  }
  return candidates.filter((candidate) => candidate.dayCount > 0).sort((a, b) =>
    b.dayCount - a.dayCount ||
    b.gross - a.gross ||
    b.receipts - a.receipts ||
    a.index - b.index
  )[0]?.days ?? [];
}

/** primary（LZH原本）を同一営業日の正本として fallback（保存レポート）へ重ねる。 */
export function mergePosJournalDaysPreferPrimary(
  primary: PosJournalDay[],
  fallback: PosJournalDay[],
): PosJournalDay[] {
  const byDate = new Map<string, PosJournalDay>();
  for (const day of Array.isArray(fallback) ? fallback : []) {
    if (/^\d{4}-\d{2}-\d{2}$/.test(day.business_date)) {
      byDate.set(day.business_date, day);
    }
  }
  for (const day of Array.isArray(primary) ? primary : []) {
    if (/^\d{4}-\d{2}-\d{2}$/.test(day.business_date)) {
      const existing = byDate.get(day.business_date);
      const detail = reconcilePosJournalDayDetail(day);
      // 古いサーバー解析で取消行を落として商品明細だけ過大な場合、
      // 日計・決済・天候は原本を正とし、明細だけ既存保存レポートを維持する。
      byDate.set(
        day.business_date,
        existing && !detail.detailComplete
          ? { ...existing, ...day, receipts: existing.receipts }
          : { ...day, receipts: detail.receipts },
      );
    }
  }
  return [...byDate.values()].sort((a, b) =>
    a.business_date.localeCompare(b.business_date)
  );
}

export function buildJournalSavedReportHtml(
  report: { title: string; period: string; data: JournalSavedReportData },
): string {
  const escape = (value: unknown) =>
    String(value ?? "").replace(/[&<>"']/g, (char) =>
      ({
        "&": "&amp;",
        "<": "&lt;",
        ">": "&gt;",
        '"': "&quot;",
        "'": "&#39;",
      })[char] ?? char
    );
  const yen = (value: unknown) =>
    `¥${Math.round(safeNumber(value)).toLocaleString("ja-JP")}`;
  const dayRows = report.data.dailyBreakdown.map((day) =>
    `<tr><td>${escape(day.date)}</td><td>${yen(day.total)}</td><td>${
      escape(day.groups)
    }組</td><td>${escape(day.customers)}名</td></tr>`
  ).join("");
  const productRows = report.data.topProducts.slice(0, 30).map((product) =>
    `<tr><td>${escape(product.name)}</td><td>${escape(product.category)}</td><td>${
      escape(product.qty)
    }</td><td>${yen(product.amt)}</td></tr>`
  ).join("");
  return `<!doctype html><html lang="ja"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${
    escape(report.title)
  }</title><style>
body{font-family:-apple-system,BlinkMacSystemFont,"Hiragino Kaku Gothic ProN","Yu Gothic",sans-serif;color:#172033;background:#f5f7fa;margin:0;padding:28px}.report{max-width:1000px;margin:auto;background:#fff;border:1px solid #dce3eb;border-radius:14px;padding:28px}.r-title{margin:0 0 8px;font-size:26px}.r-meta{color:#637083}.kpis{display:grid;grid-template-columns:repeat(auto-fit,minmax(150px,1fr));gap:10px;margin:20px 0}.kpi{border:1px solid #dce3eb;border-radius:10px;padding:12px}.k-l{font-size:12px;color:#637083}.k-v{font-size:20px;font-weight:700;margin-top:4px}.day-section{margin-top:24px}.month-table{width:100%;border-collapse:collapse;margin:10px 0 22px}.month-table th,.month-table td{border-bottom:1px solid #e4e9ef;padding:8px;text-align:right}.month-table th:first-child,.month-table td:first-child{text-align:left}.rv-note{color:#637083;font-size:12px}
</style></head><body><div class="report"><h1 class="r-title">${
    escape(report.title)
  }</h1><p class="r-meta">対象期間 ${
    escape(report.period)
  } / ${report.data.salesCount}件 / 総売上 ${yen(report.data.total)}</p><div class="kpis"><div class="kpi"><div class="k-l">総売上</div><div class="k-v">${
    yen(report.data.total)
  }</div></div><div class="kpi"><div class="k-l">フード</div><div class="k-v">${
    yen(report.data.foodTotal)
  }</div></div><div class="kpi"><div class="k-l">飲料</div><div class="k-v">${
    yen(report.data.drinkTotal)
  }</div></div><div class="kpi"><div class="k-l">客数</div><div class="k-v">${
    escape(report.data.totalCustomers)
  }名</div></div></div><section class="day-section"><h2>日別集計</h2><table class="month-table"><thead><tr><th>日付</th><th>売上</th><th>組数</th><th>客数</th></tr></thead><tbody>${dayRows}</tbody></table><h2>商品別集計</h2><table class="month-table"><thead><tr><th>商品</th><th>カテゴリ</th><th>点数</th><th>売上</th></tr></thead><tbody>${productRows}</tbody></table><p class="rv-note">電子ジャーナル画面へのLZH登録から自動作成された保存済みレポートです。数値・伝票・商品明細は保存データにも保持されています。</p></section></div></body></html>`;
}

export function buildPosJournalSummary(params: {
  storeKey: string;
  storeName: string;
  storeCode: string;
  month: string;
  days: PosJournalDay[];
  fileCount: number;
  generatedAt?: string;
  categoryOverrides?: Record<string, unknown>;
}): PosJournalSummary {
  const dayMap = new Map<string, PosJournalDay>();
  for (const day of params.days) {
    if (!/^\d{4}-\d{2}-\d{2}$/.test(day.business_date)) continue;
    dayMap.set(day.business_date, day);
  }
  const days = applyPosJournalCategoryOverrides(
    Array.from(dayMap.values()).sort((a, b) =>
      a.business_date.localeCompare(b.business_date)
    ),
    params.categoryOverrides ?? {},
  );
  const detailDays = days.map((day) => ({
    ...day,
    receipts: reconcilePosJournalDayDetail(day).receipts,
  }));
  const itemMap = new Map<
    string,
    {
      code: string;
      name: string;
      qty: number;
      amount: number;
      category?: PosJournalReceiptItem["category"];
    }
  >();
  const paymentBreakdown: Record<string, { count: number; amount: number }> =
    {};
  for (const day of detailDays) {
    for (const receipt of day.receipts || []) {
      for (const [method, amount] of Object.entries(
        resolvePosJournalReceiptPayments(receipt),
      )) {
        const payment = paymentBreakdown[method] ?? { count: 0, amount: 0 };
        payment.count += 1;
        payment.amount += amount;
        paymentBreakdown[method] = payment;
      }
      for (const item of receipt.items || []) {
        if (isPosJournalAdjustmentItem(item)) continue;
        const key = `${item.code}\u0000${item.name}`;
        const current = itemMap.get(key) ?? {
          code: item.code,
          name: item.name,
          qty: 0,
          amount: 0,
          category: item.category,
        };
        current.qty += Number(item.qty) || 0;
        current.amount += Number(item.amount) || 0;
        if (item.category) current.category = item.category;
        itemMap.set(key, current);
      }
    }
  }
  const gross = sumDays(days, "gross_sales");
  const paymentTotal = Object.values(paymentBreakdown).reduce(
    (sum, payment) => sum + payment.amount,
    0,
  );
  const guests = sumDays(days, "guests");
  let foodAmount = 0;
  let drinkAmount = 0;
  let roomAmount = 0;
  let otherAmount = 0;
  let chargeAmount = 0;
  for (const day of detailDays) {
    for (const receipt of day.receipts || []) {
      for (const item of receipt.items || []) {
        const amount = Number(item.amount) || 0;
        const primary = posJournalPrimaryCategory(item.category);
        if (primary === "フード") foodAmount += amount;
        else if (primary === "飲料") drinkAmount += amount;
        else if (primary === "室料") roomAmount += amount;
        else otherAmount += amount;
        if (item.isCharge) chargeAmount += amount;
      }
    }
  }
  return {
    meta: {
      store_key: params.storeKey,
      store_name: params.storeName,
      store_code: params.storeCode,
      month: params.month,
      file_count: params.fileCount,
      day_count: days.length,
      generated_at: params.generatedAt ?? new Date().toISOString(),
    },
    totals: {
      net_sales: sumDays(days, "net_sales"),
      tax: sumDays(days, "tax"),
      gross_sales: gross,
      groups: sumDays(days, "groups"),
      guests,
      avg_spend: guests ? Math.round(gross / guests) : 0,
      cash_amount: paymentBreakdown["現金"]?.amount || 0,
      credit_amount: paymentBreakdown["クレジット"]?.amount || 0,
      tabelog_amount: paymentBreakdown["食べログ"]?.amount || 0,
      ikyu_amount: paymentBreakdown["一休"]?.amount || 0,
      gurunavi_amount: paymentBreakdown["ぐるなび"]?.amount || 0,
      payment_total: paymentTotal,
      unattributed_payment_amount: Math.max(0, gross - paymentTotal),
      food_amount: foodAmount,
      drink_amount: drinkAmount,
      room_amount: roomAmount,
      other_amount: otherAmount,
      charge_amount: chargeAmount,
    },
    payment_breakdown: paymentBreakdown,
    item_ranking: Array.from(itemMap.values())
      .filter((item) => item.qty > 0 && item.amount >= 0)
      .sort((a, b) =>
        b.amount - a.amount || b.qty - a.qty ||
        a.name.localeCompare(b.name, "ja")
      ),
    days: detailDays,
  };
}
