import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

const root = new URL("../", import.meta.url);
const adminApi = await readFile(
  new URL("supabase/functions/admin-api/index.ts", root),
  "utf8",
);
const page = await readFile(new URL("public/pos-journal.html", root), "utf8");
const journalReport = await readFile(
  new URL("public/jnm/jnl2txt.html", root),
  "utf8",
);

test("POS journal state shares Journal Report saved reports without double counting dates", () => {
  assert.match(adminApi, /fetchSharedJournalReportState/);
  assert.match(adminApi, /\.from\("saved_reports"\)/);
  assert.match(adminApi, /savedReportCandidateMatchesMonth/);
  assert.match(adminApi, /buildPosJournalDaysFromSavedReports/);
  assert.match(adminApi, /const storedDateSet = new Set/);
  assert.match(adminApi, /!storedDateSet\.has\(day\.business_date\)/);
  assert.match(adminApi, /storage_mode = rows\.length && sharedOnlyDays\.length/);
});

test("POS journal AI uses the same shared report merge as the screen", () => {
  const start = adminApi.indexOf("async function resolvePosJournalAiSummary(");
  assert.notEqual(start, -1);
  const body = adminApi.slice(start, start + 2500);
  assert.match(body, /fetchSharedJournalReportState/);
  assert.match(body, /const combinedDays = \[/);
  assert.match(body, /!storedDateSet\.has\(day\.business_date\)/);
  assert.match(body, /days: combinedDays/);
});

test("POS journal summary shows food/drink mix and daily majority icons", () => {
  assert.match(page, /function renderFoodDrinkMix\(/);
  assert.match(page, /function dayFoodDrinkMark\(/);
  assert.match(page, /フード \/ ドリンク \/ 室料 \/ その他/);
  assert.match(page, /share\.foodPct>0\.5/);
  assert.match(page, /share\.drinkPct>0\.5/);
  assert.match(page, /class="fd-mark food"/);
  assert.match(page, /class="fd-mark drink"/);
  assert.match(page, /function dayFoodDrinkCompare\(/);
  assert.match(page, /フード\/ドリンク/);
  assert.match(page, /colspan="13"/);
});

test("POS journal state applies Journal Report category overrides", () => {
  assert.match(adminApi, /const categoryOverrides = await fetchPosJournalCategoryOverrides/);
  assert.match(adminApi, /categoryOverrides,/);
});

test("POS journal page renders shared-only months and explains the source", () => {
  assert.match(page, /id="sharedRefNotice"/);
  assert.match(page, /function renderSharedReference\(state\)/);
  assert.match(page, /Journal Reportで登録した同店舗・同月の保存済みレポートを共有参照/);
  assert.match(page, /var sharedDays=state\.summary&&Array\.isArray\(state\.summary\.days\)/);
  assert.match(page, /if \(\(state\.files\|\|\[\]\)\.length \|\| sharedDays\) render/);
});

test("Journal Report preserves a shared day snapshot when large sales are omitted", () => {
  assert.match(journalReport, /function buildSharedPosJournalDays\(report\)/);
  assert.match(journalReport, /posJournalDays = buildSharedPosJournalDays\(r\)/);
  assert.match(journalReport, /if \(posJournalDays\.length\) data\.posJournalDays = posJournalDays/);
});

test("POS upload rebuilds deterministic Journal Report daily and monthly rows", () => {
  const candidateStart = adminApi.indexOf(
    "async function fetchSavedReportCandidatesForAutoBuild(",
  );
  assert.notEqual(candidateStart, -1);
  const candidateBody = adminApi.slice(candidateStart, candidateStart + 4500);
  assert.match(candidateBody, /sourceMonths:data->sourceMonths/);
  assert.match(candidateBody, /savedReportCandidateMatchesMonth\(row, month\)/);
  assert.match(candidateBody, /\.select\("id, data"\)/);
  assert.match(candidateBody, /\.in\("id", idChunk\)/);
  assert.doesNotMatch(candidateBody, /\.contains\("data"/);

  const start = adminApi.indexOf("async function upsertPosJournalAutoReports(");
  assert.notEqual(start, -1);
  const body = adminApi.slice(start, start + 9500);
  assert.match(body, /fetchPosJournalRows\(supabase, storeKey, month\)/);
  assert.match(body, /fetchSavedReportCandidatesForAutoBuild/);
  assert.match(body, /pickBestJournalSavedReportDays/);
  assert.match(body, /mergePosJournalDaysPreferPrimary/);
  assert.match(body, /buildJournalSavedReportsFromPosDays/);
  assert.match(body, /buildJournalSavedReportHtml/);
  assert.match(body, /POS_REPORT_HTML_BUCKET/);
  assert.match(body, /\.upsert\(payloads, \{ onConflict: "id" \}\)/);
  assert.match(body, /autoGeneratedFromPosJournal:\s*true/);
  assert.match(body, /isCanonicalSavedReportForMonth/);
  assert.match(
    adminApi,
    /function legacySavedReportIsSingleMonth\([\s\S]*?periodDates\.every\([\s\S]*?合算\|〜\|～\|から\|まで/,
  );
  assert.match(
    adminApi,
    /sourceMonths\.length === 1 && sourceMonths\[0\] === month/,
  );
  assert.match(
    adminApi,
    /legacySavedReportIsSingleMonth\(row, month\)/,
  );
  assert.match(
    adminApi,
    /function isCanonicalSavedReportForMonth\([\s\S]*?if \(\/合算\/\.test\(title\)\) return false/,
  );
  assert.match(body, /id: toSafeString\(existing\?\.id\) \|\| report\.id/);
  assert.match(body, /syncJournalSalesFromReport/);

  const uploadStart = adminApi.indexOf("async function uploadPosJournalFiles(");
  assert.notEqual(uploadStart, -1);
  const upload = adminApi.slice(uploadStart, uploadStart + 20000);
  assert.match(upload, /upsertPosJournalAutoReports/);
  assert.match(upload, /saved_reports:\s*savedReports/);
  assert.match(upload, /successes, \.\.\.repaired, \.\.\.duplicates/);
});

test("POS upload UI reports automatic daily monthly creation and failures", () => {
  assert.match(page, /保存済みレポート（日別・月間）も同じ月の全原本から自動作成・更新/);
  assert.match(page, /var reportTotals=\{created:0,updated:0,failed:0\}/);
  assert.match(page, /result\.saved_reports\|\|\{\}/);
  assert.match(page, /保存済みレポート '\+reportTotals\.created\+'件を自動作成/);
  assert.match(page, /保存済みレポート '\+reportTotals\.updated\+'件を更新/);
});
