import assert from "node:assert/strict"
import { readFile } from "node:fs/promises"
import test from "node:test"
import { parseScheduleFromText } from "../supabase/functions/_shared/mtalk_schedule_register.ts"

const root = new URL("..", import.meta.url)
const read = (relative: string) => readFile(new URL(relative, root), "utf8")

test("M-talk schedule page switches reservation and event tabs", async () => {
  const [html, chat, api, gmail] = await Promise.all([
    read("public/mtalk_schedule.html"),
    read("public/chat.html"),
    read("supabase/functions/admin-api/index.ts"),
    read("supabase/functions/gmail-alert-cron/index.ts"),
  ])

  assert.match(html, /data-tab="reservations"/)
  assert.match(html, /data-tab="events"/)
  assert.match(html, />予約</)
  assert.match(html, />予定</)
  assert.match(html, /cal-grid/)
  assert.match(html, /function renderCalendar/)
  assert.match(html, /dot resv/)
  assert.match(html, /dot evt/)
  assert.match(html, /function selectDay/)
  assert.match(html, /function scrollToSelectedDay/)
  assert.match(html, /window\.scrollTo/)
  assert.match(html, /id="themeToggleBtn"/)
  assert.match(html, /app-theme\.js/)
  assert.match(html, /html\[data-theme='light'\]/)
  assert.match(html, /--bg: #111/)
  assert.match(html, /--resv-text/)
  assert.match(html, /--allergy-text/)
  assert.match(html, /--birthday-text/)
  assert.match(html, /card-resv/)
  assert.match(html, /function notableAllergy/)
  assert.match(html, /function notableBirthday/)
  assert.match(html, /function reservationFlagsHtml/)
  assert.match(html, /function reservationDetailRows/)
  assert.match(html, /flag allergy/)
  assert.match(html, /flag birthday/)
  assert.match(html, /row\.note div/)
  assert.doesNotMatch(html, /\.card\.card-resv \.time/)
  assert.doesNotMatch(html, /\.card\.card-evt \.name \{ color: var\(--resv-text\)/)
  assert.doesNotMatch(html, /row\.plan div, \.row\.content div/)
  assert.match(html, /\/chat-schedule\?group_id=/)
  assert.match(html, /Authorization: 'Bearer '/)
  assert.match(html, /\?group='/)
  assert.match(chat, /function openReservationSchedule/)
  assert.match(chat, /mtalk_schedule\.html/)
  assert.match(chat, /onclick="openReservationSchedule\(\)"/)
  assert.match(html, /id="addBtn"/)
  assert.match(html, /function openEditForm/)
  assert.match(html, /function saveEditForm/)
  assert.match(html, /function cancelCurrentItem/)
  assert.match(html, /chat-schedule\/reservation/)
  assert.match(html, /chat-schedule\/event/)
  assert.match(html, /編集・日付変更/)
  const knowledge = await read("supabase/functions/chat-knowledge/index.ts")
  const webhook = await read("supabase/functions/line-webhook/index.ts")
  const settings = await read("public/room_settings.html")
  assert.match(knowledge, /tryAutoRegisterRoomSchedule/)
  assert.match(webhook, /tryAutoRegisterRoomSchedule/)
  assert.match(settings, /M-talkの予定カレンダー/)
  assert.match(api, /path === "\/chat-schedule"/)
  assert.match(api, /path === "\/chat-schedule\/reservation"/)
  assert.match(api, /path === "\/chat-schedule\/event"/)
  assert.match(api, /async function handleChatSchedule/)
  assert.match(api, /async function handleChatScheduleReservation/)
  assert.match(api, /async function handleChatScheduleEvent/)
  assert.match(api, /createManualReservationEvent/)
  assert.match(api, /updateReservationEvent/)
  assert.match(api, /authenticateChatMember\(req, supabase, groupId\)/)
  assert.match(api, /resolveMtalkRoomStoreKey/)
  assert.match(api, /fetchReservationCalendarState/)
  assert.match(api, /line_room_calendar_events/)
  assert.match(api, /slimChatScheduleReservation/)
  assert.match(api, /anniversary_label/)
  assert.match(api, /request_note_label/)
  assert.match(api, /dislikes_label/)
  assert.match(gmail, /requestNote = normalizeCalendarDetailText\(\s*reservation\?\.requestNote/)
  assert.doesNotMatch(api, /reservation_detail: item\.reservation_detail/)
  const roomConfigAt = api.indexOf('path === "/chat-room-config"')
  const scheduleAt = api.indexOf('path === "/chat-schedule"')
  const reservationWriteAt = api.indexOf('path === "/chat-schedule/reservation"')
  const eventWriteAt = api.indexOf('path === "/chat-schedule/event"')
  const adminAuthAt = api.lastIndexOf("const authResult = await authenticate(")
  assert.ok(roomConfigAt > 0 && scheduleAt > roomConfigAt)
  assert.ok(reservationWriteAt > 0 && reservationWriteAt < adminAuthAt)
  assert.ok(eventWriteAt > 0 && eventWriteAt < adminAuthAt)
  assert.ok(adminAuthAt > scheduleAt)
})

test("conversation schedule parser extracts JST datetime for M-talk calendar", () => {
  const now = new Date("2026-08-20T03:00:00.000Z")
  const parsed = parseScheduleFromText("明日15時から仕込み", now)
  assert.ok(parsed)
  assert.equal(parsed.title.includes("仕込み"), true)
  assert.equal(parsed.startsAt, "2026-08-21T06:00:00.000Z")
  const explicit = parseScheduleFromText("予定登録 2026-08-22 10:30 試飲会", now)
  assert.ok(explicit)
  assert.equal(explicit.title, "試飲会")
  assert.equal(explicit.startsAt, "2026-08-22T01:30:00.000Z")
  assert.equal(parseScheduleFromText("こんにちは", now), null)
})
