import {
  buildJournalSavedReportsFromPosDays,
  buildJournalSavedReportHtml,
  classifyPosJournalReportItem,
  mergePosJournalDaysPreferPrimary,
  pickBestJournalSavedReportDays,
  type PosJournalDay,
} from "../supabase/functions/_shared/pos_journal.ts";

function assertEquals(actual: unknown, expected: unknown): void {
  const a = JSON.stringify(actual);
  const e = JSON.stringify(expected);
  if (a !== e) {
    throw new Error(`assertEquals failed\nactual: ${a}\nexpected: ${e}`);
  }
}

function sampleDay(
  businessDate: string,
  total: number,
  source = `${businessDate}.lzh`,
): PosJournalDay {
  return {
    business_date: businessDate,
    source,
    net_sales: total - Math.round(total / 11),
    tax: Math.round(total / 11),
    gross_sales: total,
    groups: 2,
    guests: 4,
    weather: "晴",
    temp_c: 8,
    pay_cash: { count: 1, amount: total / 2 },
    pay_credit: { count: 1, amount: total / 2 },
    receipts: [
      {
        no: "1",
        time: "12:00",
        pay: "現金",
        total: total / 2,
        guests: 2,
        items: [
          {
            code: "0000000000101",
            name: "コース6品",
            unit: total / 4,
            qty: 2,
            amount: total / 2,
          },
        ],
      },
      {
        no: "2",
        time: "18:30",
        pay: "クレジット",
        total: total / 2,
        guests: 2,
        items: [
          {
            code: "0000000002100",
            name: "Bottle Wine",
            unit: total / 2,
            qty: 1,
            amount: total / 2,
          },
        ],
      },
    ],
  };
}

Deno.test("POS journal days build deterministic daily and monthly saved reports", () => {
  const reports = buildJournalSavedReportsFromPosDays({
    storeKey: "bistrocavacava",
    storeName: "Bistro CAVACAVA",
    storeCode: "1015",
    month: "2026-01",
    days: [
      sampleDay("2026-01-29", 20_000),
      sampleDay("2026-01-30", 30_000),
      // Duplicate date: latest input row wins before report construction.
      sampleDay("2026-01-30", 40_000, "replacement.lzh"),
      // Other months never leak into the requested month.
      sampleDay("2026-02-01", 99_000),
    ],
    journalIds: [3, 1, 3, 2],
    createdAt: "2026-08-12T12:00:00Z",
  });

  assertEquals(reports.length, 2);
  assertEquals(reports.map((report) => report.id), [
    "pos_journal_auto_bistrocavacava_202601_daily",
    "pos_journal_auto_bistrocavacava_202601_monthly",
  ]);
  assertEquals(reports.map((report) => report.title), [
    "日別売上レポート（2026年1月）",
    "月間売上レポート（2026年1月）",
  ]);
  for (const report of reports) {
    assertEquals(report.period, "2026-01-29 〜 2026-01-30");
    assertEquals(report.data.total, 60_000);
    assertEquals(report.data.salesCount, 4);
    assertEquals(report.data.foodTotal, 30_000);
    assertEquals(report.data.drinkTotal, 30_000);
    assertEquals(report.data.lunchTotal, 30_000);
    assertEquals(report.data.dinnerTotal, 30_000);
    assertEquals(report.data.totalCustomers, 8);
    assertEquals(report.data.totalGroups, 4);
    assertEquals(report.data.sourceMonths, ["2026-01"]);
    assertEquals(report.data.journalIds, [3, 1, 2]);
    assertEquals(report.data.posJournalDays.length, 2);
    assertEquals(report.data.autoGeneratedFromPosJournal, true);
  }
});

Deno.test("auto saved report item categories honor shared overrides and safe defaults", () => {
  assertEquals(
    classifyPosJournalReportItem(
      "0000000000101",
      { "0000000000101|コース6品": "飲料" },
      "コース6品",
    ),
    {
      category: "飲料",
      isCharge: false,
      known: true,
      byCode: false,
      needsReview: false,
    },
  );
  assertEquals(classifyPosJournalReportItem("0000000000001", {}, "チャージ料"), {
    category: "フード",
    isCharge: true,
    known: true,
    byCode: true,
    needsReview: false,
  });
  assertEquals(classifyPosJournalReportItem("9999999999999", {}, "未知商品"), {
    category: "その他",
    isCharge: false,
    known: true,
    byCode: false,
    needsReview: true,
  });
});

Deno.test("day summary remains the guest group and tax source of truth", () => {
  const day = sampleDay("2026-01-31", 55_000);
  day.groups = 1;
  day.guests = 5;
  day.tax = 5_000;
  day.receipts[0].guests = 4;
  day.receipts[1].guests = 4;

  const [daily] = buildJournalSavedReportsFromPosDays({
    storeKey: "bistrocavacava",
    storeName: "Bistro CAVACAVA",
    storeCode: "1015",
    month: "2026-01",
    days: [day],
  });

  assertEquals(daily.data.totalCustomers, 5);
  assertEquals(daily.data.totalGroups, 1);
  assertEquals(
    daily.data.sales.reduce((sum, sale) => sum + sale.customers, 0),
    5,
  );
  assertEquals(
    daily.data.sales.reduce((sum, sale) => sum + sale.groups, 0),
    1,
  );
  assertEquals(
    daily.data.sales.reduce((sum, sale) => sum + sale.tax, 0),
    5_000,
  );
});

Deno.test("duplicate payment-change receipt copies keep only the latest copy", () => {
  const day = sampleDay("2026-01-30", 64_000);
  const duplicatedItems = [
    { code: "0000000000102", name: "コース8品", unit: 10_000, qty: 2, amount: 20_000 },
    { code: "0000000002101", name: "ペアリング", unit: 5_000, qty: 2, amount: 10_000 },
    { code: "0000000000030", name: "プレート", unit: 2_000, qty: 1, amount: 2_000 },
  ];
  day.receipts = [
    {
      no: "6590",
      time: "22:09",
      pay: "クレジット",
      total: 32_000,
      guests: 2,
      items: [{ code: "0000000000101", name: "コース6品", unit: 16_000, qty: 2, amount: 32_000 }],
    },
    {
      no: "6591",
      time: "22:09",
      pay: "食べログ",
      total: 32_000,
      guests: 2,
      items: duplicatedItems,
    },
    {
      no: "6592",
      time: "22:12",
      pay: "クレジット",
      total: 32_000,
      guests: 2,
      items: duplicatedItems,
    },
  ];
  day.groups = 2;
  day.guests = 4;
  day.gross_sales = 64_000;
  day.net_sales = 58_182;
  day.tax = 5_818;

  const [daily] = buildJournalSavedReportsFromPosDays({
    storeKey: "bistrocavacava",
    storeName: "Bistro CAVACAVA",
    storeCode: "1015",
    month: "2026-01",
    days: [day],
  });

  assertEquals(daily.data.sales.map((sale) => sale.no), ["6590", "6592"]);
  assertEquals(daily.data.salesCount, 2);
  assertEquals(daily.data.total, 64_000);
  assertEquals(
    daily.data.sales.reduce((sum, sale) => sum + sale.total, 0),
    64_000,
  );
});

Deno.test("identical legitimate receipts remain when day totals already match", () => {
  const duplicatedItems = [
    {
      code: "0000000000031",
      name: "SPパン",
      unit: 350,
      qty: 2,
      amount: 700,
    },
  ];
  const day = sampleDay("2026-01-06", 1_400);
  day.receipts = [
    {
      no: "6322",
      time: "21:54",
      table_no: "2",
      pay: "クレジット",
      total: 700,
      guests: 1,
      items: duplicatedItems,
    },
    {
      no: "6323",
      time: "21:54",
      table_no: "1",
      pay: "クレジット",
      total: 700,
      guests: 1,
      items: duplicatedItems,
    },
  ];
  day.groups = 2;
  day.guests = 2;
  day.gross_sales = 1_400;
  day.net_sales = 1_273;
  day.tax = 127;

  const [daily] = buildJournalSavedReportsFromPosDays({
    storeKey: "bistrocavacava",
    storeName: "Bistro CAVACAVA",
    storeCode: "1015",
    month: "2026-01",
    days: [day],
  });

  assertEquals(daily.data.sales.map((sale) => sale.no), ["6322", "6323"]);
  assertEquals(daily.data.salesCount, 2);
  assertEquals(daily.data.totalGroups, 2);
  assertEquals(daily.data.totalCustomers, 2);
  assertEquals(
    daily.data.sales.reduce((sum, sale) => sum + sale.total, 0),
    1_400,
  );
});

Deno.test("matching day total preserves split receipts when receipt count differs from groups", () => {
  const day = sampleDay("2026-01-07", 1_400);
  const splitItems = [{
    code: "0000000000031",
    name: "SPパン",
    unit: 350,
    qty: 2,
    amount: 700,
  }];
  day.receipts = [
    {
      no: "split-1",
      time: "21:54",
      table_no: "1",
      pay: "クレジット",
      total: 700,
      guests: 1,
      items: splitItems,
    },
    {
      no: "split-2",
      time: "21:54",
      table_no: "1",
      pay: "クレジット",
      total: 700,
      guests: 1,
      items: splitItems,
    },
  ];
  day.groups = 1;
  day.guests = 2;
  day.gross_sales = 1_400;
  day.net_sales = 1_273;
  day.tax = 127;

  const [daily] = buildJournalSavedReportsFromPosDays({
    storeKey: "bistrocavacava",
    storeName: "Bistro CAVACAVA",
    storeCode: "1015",
    month: "2026-01",
    days: [day],
  });

  assertEquals(daily.data.sales.map((sale) => sale.no), [
    "split-1",
    "split-2",
  ]);
  assertEquals(daily.data.salesCount, 2);
  assertEquals(
    daily.data.sales.reduce((sum, sale) => sum + sale.groups, 0),
    1,
  );
  assertEquals(daily.data.totalGroups, 1);
  assertEquals(daily.data.totalCustomers, 2);
  assertEquals(
    daily.data.sales.reduce((sum, sale) => sum + sale.total, 0),
    1_400,
  );
});

Deno.test("partial LZH days replace matching dates without shrinking a full saved month", () => {
  const existingReports = [
    {
      id: "older-wide",
      created_at: "2026-08-01T00:00:00Z",
      data: {
        sales: [
          {
            no: "1",
            date: "2026-01-01",
            time: "18:00",
            total: 10_000,
            tax: 900,
            customers: 2,
            groups: 1,
            method: "現金",
            payments: { byMethod: { 現金: 10_000 } },
            items: [{ code: "0000000000101", name: "コース6品", qty: 1, amount: 10_000 }],
          },
          {
            no: "2",
            date: "2026-01-02",
            time: "18:00",
            total: 20_000,
            tax: 1_800,
            customers: 3,
            groups: 1,
            method: "現金",
            payments: { byMethod: { 現金: 20_000 } },
            items: [{ code: "0000000000101", name: "コース6品", qty: 2, amount: 20_000 }],
          },
          {
            no: "3",
            date: "2026-01-03",
            time: "18:00",
            total: 30_000,
            tax: 2_700,
            customers: 4,
            groups: 1,
            method: "現金",
            payments: { byMethod: { 現金: 30_000 } },
            items: [{ code: "0000000000101", name: "コース6品", qty: 3, amount: 30_000 }],
          },
        ],
      },
    },
    {
      id: "newer-short",
      created_at: "2026-08-02T00:00:00Z",
      data: {
        sales: [{
          no: "x",
          date: "2026-01-03",
          time: "18:00",
          total: 1_000,
          tax: 90,
          customers: 1,
          groups: 1,
          method: "現金",
          payments: { byMethod: { 現金: 1_000 } },
          items: [{ code: "0000000000101", name: "コース6品", qty: 1, amount: 1_000 }],
        }],
      },
    },
  ];
  const savedDays = pickBestJournalSavedReportDays(existingReports, "2026-01");
  const primary = [sampleDay("2026-01-03", 40_000, "new.lzh")];
  const merged = mergePosJournalDaysPreferPrimary(primary, savedDays);
  const [daily] = buildJournalSavedReportsFromPosDays({
    storeKey: "bistrocavacava",
    storeName: "Bistro CAVACAVA",
    storeCode: "1015",
    month: "2026-01",
    days: merged,
  });

  assertEquals(savedDays.map((day) => day.business_date), [
    "2026-01-01",
    "2026-01-02",
    "2026-01-03",
  ]);
  assertEquals(merged.map((day) => day.business_date), [
    "2026-01-01",
    "2026-01-02",
    "2026-01-03",
  ]);
  assertEquals(merged[2].gross_sales, 40_000);
  assertEquals(daily.data.total, 70_000);
  assertEquals(daily.period, "2026-01-01 〜 2026-01-03");
});

Deno.test("a newer high-value fragment does not override an equally wide baseline", () => {
  const reports = [
    {
      id: "older-wide",
      created_at: "2026-08-01T00:00:00Z",
      data: {
        sales: [
          {
            no: "1",
            date: "2026-01-01",
            total: 10_000,
            customers: 1,
            groups: 1,
            items: [],
          },
          {
            no: "2",
            date: "2026-01-02",
            total: 20_000,
            customers: 1,
            groups: 1,
            items: [],
          },
        ],
      },
    },
    {
      id: "newer-fragment",
      created_at: "2026-08-02T00:00:00Z",
      data: {
        sales: [{
          no: "bad",
          date: "2026-01-02",
          total: 999_999,
          customers: 1,
          groups: 1,
          items: [],
        }],
      },
    },
  ];

  const days = pickBestJournalSavedReportDays(reports, "2026-01");
  assertEquals(days.map((day) => day.business_date), [
    "2026-01-01",
    "2026-01-02",
  ]);
  assertEquals(days.map((day) => day.gross_sales), [10_000, 20_000]);
});

Deno.test("unreliable raw LZH items keep the existing saved-report detail for that date", () => {
  const fallback = [{
    business_date: "2026-01-31",
    source: "saved-report",
    gross_sales: 19_100,
    net_sales: 17_364,
    tax: 1_736,
    groups: 4,
    guests: 5,
    receipts: [{
      no: "saved",
      time: "22:20",
      pay: "クレジット",
      total: 19_100,
      guests: 5,
      items: [{
        code: "0000000000101",
        name: "保存済み純額",
        unit: 19_100,
        qty: 1,
        amount: 19_100,
      }],
    }],
  }] as PosJournalDay[];
  const raw = [{
    ...fallback[0],
    source: "raw-lzh",
    receipts: [{
      no: "raw",
      time: "22:20",
      pay: "クレジット",
      total: 19_100,
      guests: 5,
      items: [{
        code: "0000000000101",
        name: "取消行欠落で過大",
        unit: 19_700,
        qty: 1,
        amount: 19_700,
      }],
    }],
  }] as PosJournalDay[];
  const merged = mergePosJournalDaysPreferPrimary(raw, fallback);
  assertEquals(merged[0].source, "raw-lzh");
  assertEquals(merged[0].gross_sales, 19_100);
  assertEquals(merged[0].receipts[0].items[0].name, "保存済み純額");
  assertEquals(merged[0].receipts[0].items[0].amount, 19_100);
});

Deno.test("fragmented legacy daily reports combine into the widest month baseline", () => {
  const fragments = [
    {
      created_at: "2026-08-02T00:00:00Z",
      data: {
        sales: [{
          no: "2",
          date: "2026-01-02",
          time: "18:00",
          total: 20_000,
          customers: 2,
          groups: 1,
          method: "現金",
          payments: { byMethod: { 現金: 20_000 } },
          items: [],
        }],
      },
    },
    {
      created_at: "2026-08-01T00:00:00Z",
      data: {
        sales: [{
          no: "1",
          date: "2026-01-01",
          time: "18:00",
          total: 10_000,
          customers: 1,
          groups: 1,
          method: "現金",
          payments: { byMethod: { 現金: 10_000 } },
          items: [],
        }],
      },
    },
  ];
  const days = pickBestJournalSavedReportDays(fragments, "2026-01");
  assertEquals(days.map((day) => day.business_date), [
    "2026-01-01",
    "2026-01-02",
  ]);
  assertEquals(days.reduce((sum, day) => sum + Number(day.gross_sales), 0), 30_000);
});

Deno.test("auto generated report HTML is self-contained and has rebuild markers", () => {
  const [report] = buildJournalSavedReportsFromPosDays({
    storeKey: "bistrocavacava",
    storeName: "Bistro CAVACAVA",
    storeCode: "1015",
    month: "2026-01",
    days: [sampleDay("2026-01-29", 20_000)],
  });
  const html = buildJournalSavedReportHtml(report);
  if (!html.includes("<!doctype html>")) throw new Error("doctype missing");
  if (!html.includes("day-section")) throw new Error("day-section missing");
  if (!html.includes("month-table")) throw new Error("month-table missing");
  if (!html.includes("日別集計")) throw new Error("daily table missing");
});

Deno.test("empty or mismatched month data does not create empty reports", () => {
  assertEquals(
    buildJournalSavedReportsFromPosDays({
      storeKey: "bistrocavacava",
      storeName: "Bistro CAVACAVA",
      storeCode: "1015",
      month: "invalid",
      days: [],
    }),
    [],
  );
  assertEquals(
    buildJournalSavedReportsFromPosDays({
      storeKey: "bistrocavacava",
      storeName: "Bistro CAVACAVA",
      storeCode: "1015",
      month: "2026-01",
      days: [sampleDay("2026-02-01", 10_000)],
    }),
    [],
  );
});
