import {
  buildJournalSavedReportsFromPosDays,
  classifyPosJournalReportItem,
  type PosJournalDay,
} from "../supabase/functions/_shared/pos_journal.ts";

function assertEquals(actual: unknown, expected: unknown): void {
  const a = JSON.stringify(actual);
  const e = JSON.stringify(expected);
  if (a !== e) {
    throw new Error(`assertEquals failed\nactual: ${a}\nexpected: ${e}`);
  }
}

function sampleDay(
  businessDate: string,
  total: number,
  source = `${businessDate}.lzh`,
): PosJournalDay {
  return {
    business_date: businessDate,
    source,
    net_sales: total - Math.round(total / 11),
    tax: Math.round(total / 11),
    gross_sales: total,
    groups: 2,
    guests: 4,
    weather: "晴",
    temp_c: 8,
    pay_cash: { count: 1, amount: total / 2 },
    pay_credit: { count: 1, amount: total / 2 },
    receipts: [
      {
        no: "1",
        time: "12:00",
        pay: "現金",
        total: total / 2,
        guests: 2,
        items: [
          {
            code: "0000000000101",
            name: "コース6品",
            unit: total / 4,
            qty: 2,
            amount: total / 2,
          },
        ],
      },
      {
        no: "2",
        time: "18:30",
        pay: "クレジット",
        total: total / 2,
        guests: 2,
        items: [
          {
            code: "0000000002100",
            name: "Bottle Wine",
            unit: total / 2,
            qty: 1,
            amount: total / 2,
          },
        ],
      },
    ],
  };
}

Deno.test("POS journal days build deterministic daily and monthly saved reports", () => {
  const reports = buildJournalSavedReportsFromPosDays({
    storeKey: "bistrocavacava",
    storeName: "Bistro CAVACAVA",
    storeCode: "1015",
    month: "2026-01",
    days: [
      sampleDay("2026-01-29", 20_000),
      sampleDay("2026-01-30", 30_000),
      // Duplicate date: latest input row wins before report construction.
      sampleDay("2026-01-30", 40_000, "replacement.lzh"),
      // Other months never leak into the requested month.
      sampleDay("2026-02-01", 99_000),
    ],
    journalIds: [3, 1, 3, 2],
    createdAt: "2026-08-12T12:00:00Z",
  });

  assertEquals(reports.length, 2);
  assertEquals(reports.map((report) => report.id), [
    "pos_journal_auto_bistrocavacava_202601_daily",
    "pos_journal_auto_bistrocavacava_202601_monthly",
  ]);
  assertEquals(reports.map((report) => report.title), [
    "日別売上レポート（2026年1月）",
    "月間売上レポート（2026年1月）",
  ]);
  for (const report of reports) {
    assertEquals(report.period, "2026-01-29 〜 2026-01-30");
    assertEquals(report.data.total, 60_000);
    assertEquals(report.data.salesCount, 4);
    assertEquals(report.data.foodTotal, 30_000);
    assertEquals(report.data.drinkTotal, 30_000);
    assertEquals(report.data.lunchTotal, 30_000);
    assertEquals(report.data.dinnerTotal, 30_000);
    assertEquals(report.data.totalCustomers, 8);
    assertEquals(report.data.totalGroups, 4);
    assertEquals(report.data.sourceMonths, ["2026-01"]);
    assertEquals(report.data.journalIds, [3, 1, 2]);
    assertEquals(report.data.posJournalDays.length, 2);
    assertEquals(report.data.autoGeneratedFromPosJournal, true);
  }
});

Deno.test("auto saved report item categories honor shared overrides and safe defaults", () => {
  assertEquals(
    classifyPosJournalReportItem(
      "0000000000101",
      { "0000000000101|コース6品": "飲料" },
      "コース6品",
    ),
    {
      category: "飲料",
      isCharge: false,
      known: true,
      byCode: false,
      needsReview: false,
    },
  );
  assertEquals(classifyPosJournalReportItem("0000000000001", {}, "チャージ料"), {
    category: "フード",
    isCharge: true,
    known: true,
    byCode: true,
    needsReview: false,
  });
  assertEquals(classifyPosJournalReportItem("9999999999999", {}, "未知商品"), {
    category: "その他",
    isCharge: false,
    known: true,
    byCode: false,
    needsReview: true,
  });
});

Deno.test("day summary remains the guest group and tax source of truth", () => {
  const day = sampleDay("2026-01-31", 55_000);
  day.groups = 1;
  day.guests = 5;
  day.tax = 5_000;
  day.receipts[0].guests = 4;
  day.receipts[1].guests = 4;

  const [daily] = buildJournalSavedReportsFromPosDays({
    storeKey: "bistrocavacava",
    storeName: "Bistro CAVACAVA",
    storeCode: "1015",
    month: "2026-01",
    days: [day],
  });

  assertEquals(daily.data.totalCustomers, 5);
  assertEquals(daily.data.totalGroups, 1);
  assertEquals(
    daily.data.sales.reduce((sum, sale) => sum + sale.customers, 0),
    5,
  );
  assertEquals(
    daily.data.sales.reduce((sum, sale) => sum + sale.groups, 0),
    1,
  );
  assertEquals(
    daily.data.sales.reduce((sum, sale) => sum + sale.tax, 0),
    5_000,
  );
});

Deno.test("duplicate payment-change receipt copies keep only the latest copy", () => {
  const day = sampleDay("2026-01-30", 64_000);
  const duplicatedItems = [
    { code: "0000000000102", name: "コース8品", unit: 10_000, qty: 2, amount: 20_000 },
    { code: "0000000002101", name: "ペアリング", unit: 5_000, qty: 2, amount: 10_000 },
    { code: "0000000000030", name: "プレート", unit: 2_000, qty: 1, amount: 2_000 },
  ];
  day.receipts = [
    {
      no: "6590",
      time: "22:09",
      pay: "クレジット",
      total: 32_000,
      guests: 2,
      items: [{ code: "0000000000101", name: "コース6品", unit: 16_000, qty: 2, amount: 32_000 }],
    },
    {
      no: "6591",
      time: "22:09",
      pay: "食べログ",
      total: 32_000,
      guests: 2,
      items: duplicatedItems,
    },
    {
      no: "6592",
      time: "22:12",
      pay: "クレジット",
      total: 32_000,
      guests: 2,
      items: duplicatedItems,
    },
  ];
  day.groups = 2;
  day.guests = 4;
  day.gross_sales = 64_000;
  day.net_sales = 58_182;
  day.tax = 5_818;

  const [daily] = buildJournalSavedReportsFromPosDays({
    storeKey: "bistrocavacava",
    storeName: "Bistro CAVACAVA",
    storeCode: "1015",
    month: "2026-01",
    days: [day],
  });

  assertEquals(daily.data.sales.map((sale) => sale.no), ["6590", "6592"]);
  assertEquals(daily.data.salesCount, 2);
  assertEquals(daily.data.total, 64_000);
  assertEquals(
    daily.data.sales.reduce((sum, sale) => sum + sale.total, 0),
    64_000,
  );
});

Deno.test("empty or mismatched month data does not create empty reports", () => {
  assertEquals(
    buildJournalSavedReportsFromPosDays({
      storeKey: "bistrocavacava",
      storeName: "Bistro CAVACAVA",
      storeCode: "1015",
      month: "invalid",
      days: [],
    }),
    [],
  );
  assertEquals(
    buildJournalSavedReportsFromPosDays({
      storeKey: "bistrocavacava",
      storeName: "Bistro CAVACAVA",
      storeCode: "1015",
      month: "2026-01",
      days: [sampleDay("2026-02-01", 10_000)],
    }),
    [],
  );
});
