import test from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { PGlite } from "@electric-sql/pglite";

test("real SQL: source preservation, atomic patching, reset, idempotency, permissions and forecast parity", async () => {
  const db = new PGlite();
  try {
    await db.exec(
      `create role anon; create role authenticated; create role service_role;
      create table store_webhook_tables(store_partition_key text primary key);
      insert into store_webhook_tables values ('marugoS'),('sauvage');
      create table line_sales_manual_day(id bigint generated by default as identity primary key,
        store_partition_key text not null,sales_date date not null,gross_sales_yen bigint,tax_amount_yen bigint,
        guest_count bigint,party_count bigint,source text,updated_at timestamptz default now(),
        constraint line_sales_manual_day_store_date_uidx unique(store_partition_key,sales_date));
      create table "line_receipt__marugoS"(receipt_date date,gross_sales_yen bigint,net_sales_yen bigint,
        tax_amount_yen bigint,guest_count bigint,party_count bigint);
      insert into line_sales_manual_day(store_partition_key,sales_date,gross_sales_yen,tax_amount_yen,guest_count,party_count,source)
        values ('marugoS','2026-01-01',1100,100,4,2,'journal'),('sauvage','2026-01-01',700,70,3,2,null);
      insert into "line_receipt__marugoS" values ('2026-01-01',550,500,50,2,1);`,
    );
    await db.exec(
      readFileSync(
        new URL(
          "../supabase/migrations/20260911100000_unified_daily_sales_sources.sql",
          import.meta.url,
        ),
        "utf8",
      ),
    );
    const run = async (kind, rows, store = "marugos") =>
      db.query("select write_daily_sales_source($1,$2,$3::jsonb)", [
        store,
        kind,
        JSON.stringify(rows),
      ]);
    const row = async (store = "marugoS") =>
      (await db.query(
        "select * from line_sales_manual_day where store_partition_key=$1",
        [store],
      )).rows[0];
    const source = (await row()).journal_values;
    assert.equal(source.gross_sales_yen, 1100);
    const other = await row("sauvage");
    await run("manual", [{ sales_date: "2026-01-01", guest_count: 9 }]);
    await run("manual", [{ sales_date: "2026-01-01", gross_sales_yen: 1200 }]);
    await run("journal", [{
      sales_date: "2026-01-01",
      gross_sales_yen: 2200,
      tax_amount_yen: 200,
      guest_count: 8,
      party_count: 4,
    }]);
    const current = await row();
    assert.equal(current.gross_sales_yen, 1200);
    assert.equal(current.guest_count, 9);
    assert.equal(current.party_count, 4);
    assert.equal(current.journal_values.gross_sales_yen, 2200);
    assert.deepEqual(current.manual_values, {
      gross_sales_yen: 1200,
      guest_count: 9,
    });
    const base = (await db.query("select * from foodcourt_base_daily")).rows[0];
    assert.equal(base.sales, 1000);
    assert.equal(base.sales_gross, 1200);
    assert.equal(base.guests, 9);
    await run("manual", [{ sales_date: "2026-01-01", gross_sales_yen: null }]);
    assert.equal((await row()).gross_sales_yen, 2200);
    assert.equal((await row()).guest_count, 9);
    await run("manual", [{ sales_date: "2026-01-01", guest_count: null }]);
    assert.equal((await row()).source, "journal");
    assert.equal((await row()).guest_count, 8);
    const before = await row();
    await run("journal", [{
      sales_date: "2026-01-01",
      gross_sales_yen: 2200,
      tax_amount_yen: 200,
      guest_count: 8,
      party_count: 4,
    }]);
    assert.deepEqual(await row(), before);
    await assert.rejects(run("journal", [
      {
        sales_date: "2026-01-02",
        gross_sales_yen: 2200,
        tax_amount_yen: 200,
        guest_count: 8,
        party_count: 4,
      },
      {
        sales_date: "2026-01-03",
        gross_sales_yen: -1,
        tax_amount_yen: 0,
        guest_count: 0,
        party_count: 0,
      },
    ]));
    assert.equal(
      (await db.query(
        "select count(*)::int n from line_sales_manual_day where sales_date='2026-01-02'",
      )).rows[0].n,
      0,
    );
    await assert.rejects(
      run("manual", [{ sales_date: "2026-02-31", guest_count: 2 }]),
    );
    await assert.rejects(
      run("manual", [{ sales_date: "2026-01-01", guest_count: 2.5 }]),
    );
    await assert.rejects(
      run("manual", [{ sales_date: "2026-01-01", guest_count: 2 }], "missing"),
    );
    assert.deepEqual(await row("sauvage"), other);
    for (const role of ["anon", "authenticated"]) {
      await db.exec("set role " + role);
      await assert.rejects(
        run("manual", [{ sales_date: "2026-01-01", guest_count: 99 }]),
      );
      await db.exec("reset role");
    }
    await db.exec("set role service_role");
    await run("manual", [{ sales_date: "2026-01-01", guest_count: 7 }]);
    await db.exec("reset role");
    assert.equal((await row()).guest_count, 7);
  } finally {
    await db.close();
  }
});
