-- Journal Report: 商品名検索用の月次インデックス。
-- 正本は pos_journal_files.parsed_data。保存レポートではなくジャーナルから構築する。
-- 公開フロントは直接参照せず、admin-api (service_role) 経由のみ。

create extension if not exists pg_trgm with schema public;

create table if not exists public.journal_product_monthly_index (
  id bigint generated by default as identity primary key,
  store_partition_key text not null,
  year_month text not null
    check (year_month ~ '^\d{4}-(0[1-9]|1[0-2])$'),
  product_name_norm text not null check (length(product_name_norm) > 0),
  display_name text not null check (length(btrim(display_name)) > 0),
  product_code text not null default '',
  unit_price integer not null default 0 check (unit_price >= 0),
  qty integer not null default 0 check (qty >= 0),
  amount integer not null default 0 check (amount >= 0),
  day_count integer not null default 0 check (day_count >= 0),
  first_date date,
  last_date date,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint journal_product_monthly_index_date_order
    check (first_date is null or last_date is null or first_date <= last_date),
  constraint journal_product_monthly_index_uidx
    unique (store_partition_key, year_month, product_name_norm, unit_price)
);

create index if not exists journal_product_monthly_index_store_month_idx
  on public.journal_product_monthly_index (store_partition_key, year_month);

create index if not exists journal_product_monthly_index_store_norm_idx
  on public.journal_product_monthly_index (store_partition_key, product_name_norm);

create index if not exists journal_product_monthly_index_norm_trgm_idx
  on public.journal_product_monthly_index
  using gin (product_name_norm public.gin_trgm_ops);

create index if not exists journal_product_monthly_index_display_trgm_idx
  on public.journal_product_monthly_index
  using gin (display_name public.gin_trgm_ops);

comment on table public.journal_product_monthly_index is
  '店舗×年月×正規化商品名×単価の月次商品インデックス。product-search / 初出タイムラインの高速化用。';
comment on column public.journal_product_monthly_index.product_name_norm is
  'admin-api の normalizePosProductSearchText と同一規則（NFKC・小文字・長音→ハイフン・コース→コ-ス 等）。';
comment on column public.journal_product_monthly_index.display_name is
  'その月で点数最大の生の商品名（表示用）。';

alter table public.journal_product_monthly_index enable row level security;
revoke all on table public.journal_product_monthly_index
  from public, anon, authenticated;
grant all on table public.journal_product_monthly_index to service_role;

create or replace function public.set_journal_product_monthly_index_updated_at()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

drop trigger if exists journal_product_monthly_index_updated_at_trg
  on public.journal_product_monthly_index;
create trigger journal_product_monthly_index_updated_at_trg
before update on public.journal_product_monthly_index
for each row execute function public.set_journal_product_monthly_index_updated_at();

-- ジャーナル変更で再構築が必要な (store, year_month) を記録する。
create table if not exists public.journal_product_index_dirty_months (
  store_partition_key text not null,
  year_month text not null
    check (year_month ~ '^\d{4}-(0[1-9]|1[0-2])$'),
  touched_at timestamptz not null default now(),
  primary key (store_partition_key, year_month)
);

alter table public.journal_product_index_dirty_months enable row level security;
revoke all on table public.journal_product_index_dirty_months
  from public, anon, authenticated;
grant all on table public.journal_product_index_dirty_months to service_role;

create or replace function public.mark_journal_product_index_dirty_month()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  target_store text;
  target_month text;
begin
  if tg_op = 'DELETE' then
    target_store := old.store_partition_key;
    target_month := coalesce(
      nullif(btrim(old.year_month), ''),
      to_char(old.business_date, 'YYYY-MM')
    );
  else
    target_store := new.store_partition_key;
    target_month := coalesce(
      nullif(btrim(new.year_month), ''),
      to_char(new.business_date, 'YYYY-MM')
    );
  end if;

  if target_store is null or target_month is null then
    if tg_op = 'DELETE' then return old; end if;
    return new;
  end if;

  insert into public.journal_product_index_dirty_months (
    store_partition_key, year_month, touched_at
  )
  values (target_store, target_month, now())
  on conflict (store_partition_key, year_month) do update
    set touched_at = excluded.touched_at;

  if tg_op = 'DELETE' then
    return old;
  end if;
  return new;
end;
$$;

revoke all on function public.mark_journal_product_index_dirty_month()
  from public, anon, authenticated;

drop trigger if exists pos_journal_files_product_index_dirty_trg
  on public.pos_journal_files;
create trigger pos_journal_files_product_index_dirty_trg
after insert or update of parsed_data, storage_deleted_at, year_month, business_date
  or delete on public.pos_journal_files
for each row execute function public.mark_journal_product_index_dirty_month();
