-- M-talk Web Pushの「Appleへ送信済み」と「端末で受信・表示済み」を分けて診断する。
-- endpoint・本文・購読鍵は保存せず、テストIDと段階・短いエラー分類だけを保持する。

create table if not exists public.chat_push_delivery_diagnostics (
  id bigint generated by default as identity primary key,
  test_id uuid not null,
  user_id uuid not null references public.chat_users(id) on delete cascade,
  subscription_id uuid references public.chat_push_subscriptions(id) on delete set null,
  stage text not null check (
    stage in (
      'server_queued',
      'server_sent',
      'server_failed',
      'sw_received',
      'notification_shown',
      'notification_failed'
    )
  ),
  detail text,
  created_at timestamptz not null default now(),
  constraint chat_push_delivery_diagnostics_test_stage_unique unique (test_id, stage),
  constraint chat_push_delivery_diagnostics_detail_length
    check (detail is null or char_length(detail) <= 500)
);

create index if not exists chat_push_delivery_diagnostics_user_created_idx
  on public.chat_push_delivery_diagnostics (user_id, created_at desc);

create index if not exists chat_push_delivery_diagnostics_test_stage_idx
  on public.chat_push_delivery_diagnostics (test_id, stage, created_at desc);

alter table public.chat_push_delivery_diagnostics enable row level security;
revoke all on table public.chat_push_delivery_diagnostics from public, anon, authenticated;
grant select, insert, update, delete on table public.chat_push_delivery_diagnostics to service_role;
revoke all on sequence public.chat_push_delivery_diagnostics_id_seq from public, anon, authenticated;
grant usage, select on sequence public.chat_push_delivery_diagnostics_id_seq to service_role;

comment on table public.chat_push_delivery_diagnostics is
  'M-talk Web Pushテストのserver_queued/server_sent/server_failed/sw_received/notification_shown/notification_failed診断。endpoint・本文・鍵は保存しない。';
