-- 日別予算の直接入力（手動上書き）テーブル。
-- 予算モーダルの「日別予算」を曜日按分でなく日ごとに直接入力できるようにするための上書き値。
-- 値が入っている日は、その日の自動按分よりこの直接入力を優先する（日次表の予算列・予算差に反映）。
-- 入力を消した日（null/空）はアプリ側で行ごと削除し、その日は自動按分へ戻す。
create table if not exists public.line_sales_manual_day_budget (
  id bigint generated by default as identity primary key,
  store_partition_key text not null,
  sales_date date not null,
  budget_yen bigint not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint line_sales_manual_day_budget_yen_chk check (budget_yen >= 0),
  constraint line_sales_manual_day_budget_store_date_uidx unique (store_partition_key, sales_date)
);

create index if not exists line_sales_manual_day_budget_date_idx
  on public.line_sales_manual_day_budget (store_partition_key, sales_date);

alter table public.line_sales_manual_day_budget enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'line_sales_manual_day_budget'
      and policyname = 'Service role line_sales_manual_day_budget'
  ) then
    create policy "Service role line_sales_manual_day_budget"
      on public.line_sales_manual_day_budget
      for all
      using (auth.jwt() ->> 'role' = 'service_role');
  end if;
end;
$$;
