-- 店舗ごとに Webhook / レシートを独立テーブルへ保存（hocbn 向け）
-- 命名: line_webhook_raw__{store_partition_key}, line_receipt__{store_partition_key}

create table if not exists public.store_webhook_tables (
  store_partition_key text primary key,
  display_name text not null,
  webhook_raw_table text not null,
  receipt_table text not null,
  created_at timestamptz not null default now()
);

comment on table public.store_webhook_tables is
  '店舗別 Webhook 受信テーブルのレジストリ。Edge Function line-webhook/{store_key} が参照する。';

create or replace function public.is_valid_store_partition_key(p_key text)
returns boolean
language sql
immutable
as $$
  select p_key ~ '^[a-zA-Z][a-zA-Z0-9_]*$';
$$;

create or replace function public.store_webhook_raw_table_name(p_key text)
returns text
language plpgsql
immutable
as $$
begin
  if not public.is_valid_store_partition_key(p_key) then
    raise exception 'invalid store_partition_key: %', p_key;
  end if;
  return 'line_webhook_raw__' || p_key;
end;
$$;

create or replace function public.store_receipt_table_name(p_key text)
returns text
language plpgsql
immutable
as $$
begin
  if not public.is_valid_store_partition_key(p_key) then
    raise exception 'invalid store_partition_key: %', p_key;
  end if;
  return 'line_receipt__' || p_key;
end;
$$;

create or replace function public.ensure_store_webhook_tables(p_key text, p_display_name text default null)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  raw_table text;
  receipt_table text;
  display_name text;
begin
  if not public.is_valid_store_partition_key(p_key) then
    raise exception 'invalid store_partition_key: %', p_key;
  end if;

  raw_table := public.store_webhook_raw_table_name(p_key);
  receipt_table := public.store_receipt_table_name(p_key);
  display_name := coalesce(nullif(btrim(p_display_name), ''), p_key);

  execute format($sql$
    create table if not exists public.%I (
      id bigint generated by default as identity primary key,
      webhook_event_id text,
      event_type text not null,
      room_id text,
      user_id text,
      payload jsonb not null,
      received_at timestamptz not null default now()
    )
  $sql$, raw_table);

  execute format(
    'create unique index if not exists %I on public.%I (webhook_event_id) where webhook_event_id is not null',
    raw_table || '_webhook_event_uidx',
    raw_table
  );

  execute format(
    'create index if not exists %I on public.%I (received_at desc)',
    raw_table || '_received_at_idx',
    raw_table
  );

  execute format($sql$
    create table if not exists public.%I (
      id bigint generated by default as identity primary key,
      line_message_id text not null,
      room_id text not null,
      user_id text,
      sender_display_name text,
      store_name text,
      receipt_date_text text,
      receipt_date date,
      net_sales_yen bigint,
      tax_amount_yen bigint,
      gross_sales_yen bigint,
      party_count integer,
      guest_count integer,
      unit_price_yen bigint,
      summary_text text,
      raw_payload jsonb,
      created_at timestamptz not null default now()
    )
  $sql$, receipt_table);

  execute format(
    'create unique index if not exists %I on public.%I (line_message_id)',
    receipt_table || '_line_message_uidx',
    receipt_table
  );

  execute format(
    'create index if not exists %I on public.%I (receipt_date desc)',
    receipt_table || '_receipt_date_idx',
    receipt_table
  );

  execute format(
    'alter table public.%I enable row level security',
    raw_table
  );
  execute format(
    'alter table public.%I enable row level security',
    receipt_table
  );

  insert into public.store_webhook_tables (
    store_partition_key,
    display_name,
    webhook_raw_table,
    receipt_table
  ) values (
    p_key,
    display_name,
    raw_table,
    receipt_table
  )
  on conflict (store_partition_key) do update
    set display_name = excluded.display_name,
        webhook_raw_table = excluded.webhook_raw_table,
        receipt_table = excluded.receipt_table;
end;
$$;

-- pages-config.js の STORE_NAMES と同期
do $$
declare
  row record;
begin
  for row in
    select *
    from (
      values
        ('marugo', 'マルゴ'),
        ('marugosecond', 'マルゴ セカンド'),
        ('marugogrande', 'マルゴ グランデ'),
        ('sannanaichi', 'サンナナイチ バル'),
        ('shenlong', 'シェンロン&クラウディア'),
        ('claudia2', 'クラウディア2'),
        ('sauvage', 'ソバージュ'),
        ('barpelota', 'バルぺロタ'),
        ('briccola', 'トラットリア ブリッコラ'),
        ('violette', 'ヴィオレット'),
        ('marugootto', 'マルゴ オット'),
        ('donaiya', '元祖どないや 新宿三丁目店'),
        ('marugoyotsuya', 'マルゴ 四谷'),
        ('sushikoruri', '鮨こるり'),
        ('bistrocavacava', 'BISTRO CAVA CAVA'),
        ('marugoS', 'マルゴエス'),
        ('marugoshinbashi', 'マルゴ 新橋'),
        ('marugomarunouchi', 'マルゴ丸の内'),
        ('yakinikumarugo', '焼肉マルゴ'),
        ('erics', 'エリックスバイエリックトロション'),
        ('mitan', 'ミタン'),
        ('marugoD', 'マルゴ D')
    ) as t(store_key, display_name)
  loop
    perform public.ensure_store_webhook_tables(row.store_key, row.display_name);
  end loop;
end;
$$;
