-- 店舗ナレッジ: 施策・メニュー等の資料。公開Pagesは直接参照せず admin-api(service_role) 経由のみ。
-- 店舗分離は store_partition_key。他店キーのアクセスはAPI層で拒否する。

create table if not exists public.store_knowledge_documents (
  id bigint generated by default as identity primary key,
  store_partition_key text not null,
  category text not null check (category in
    ('施策','メニュー','価格改定','イベント','マニュアル','その他')),
  title text not null check (length(btrim(title)) > 0),
  summary text not null default '',          -- AIが最初に読む1〜3行
  body_text text not null default '',        -- 貼り付け原文／抽出テキスト
  search_text text not null default '',      -- title+summary+body+tags を正規化した検索用
  period_start date,                         -- null = 期間指定なし（常時有効）
  period_end date,
  tags text[] not null default '{}',
  storage_bucket text not null default 'store-knowledge',
  storage_path text,                         -- 添付なしは null
  original_file_name text,
  mime_type text,
  file_size_bytes bigint check (file_size_bytes is null or file_size_bytes > 0),
  sha256_hex text check (sha256_hex is null or sha256_hex ~ '^[0-9a-f]{64}$'),
  source_type text not null default 'manual'
    check (source_type in ('manual','upload','ai_insight')),
  is_active boolean not null default true,
  created_by text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint store_knowledge_period_order
    check (period_start is null or period_end is null or period_start <= period_end)
);

create index if not exists store_knowledge_store_active_period_idx
  on public.store_knowledge_documents (store_partition_key, is_active, period_start desc);
create index if not exists store_knowledge_store_category_idx
  on public.store_knowledge_documents (store_partition_key, category, is_active);
-- pg_trgm は導入済み。部分一致検索を高速化する
create index if not exists store_knowledge_search_trgm_idx
  on public.store_knowledge_documents using gin (search_text gin_trgm_ops);
create unique index if not exists store_knowledge_active_hash_uidx
  on public.store_knowledge_documents (store_partition_key, sha256_hex)
  where is_active and sha256_hex is not null;

alter table public.store_knowledge_documents enable row level security;
revoke all on table public.store_knowledge_documents from anon, authenticated;
grant select, insert, update, delete on public.store_knowledge_documents to service_role;

comment on table public.store_knowledge_documents is
  'Journal Report 店舗ナレッジ（施策・メニュー資料）。店舗分離は store_partition_key。admin-api 経由のみ。';

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'store-knowledge', 'store-knowledge', false, 20971520,
  array[
    'application/pdf','image/png','image/jpeg','image/webp',
    'text/plain','text/csv','text/markdown',
    'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    'application/octet-stream'
  ]::text[]
)
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;
