-- 天候の恒久保存テーブル（analytics 天気キャッシュ）。
-- これまで line_sales_month_budgets を store_partition_key='weather:{店舗キー}' で流用し
-- store_closed_dates(JSON) に月別保存していたのを、専用テーブルへ移行する。
-- admin-api /weather/daily が Open-Meteo から取得した日次天気（最高気温・降水量）を保存・再利用し、
-- 一度取得した過去天気が消えないように恒久保存する。

create table if not exists public.line_weather_daily (
  id bigint generated by default as identity primary key,
  cache_key text not null,             -- store_partition_key、無い場合は 'lat,lon'
  weather_date date not null,
  temp_max_c numeric(6, 2),            -- temperature_2m_max（℃）
  precipitation_mm numeric(8, 2),      -- precipitation_sum（mm）
  source text,                         -- 'archive' | 'forecast' | 'migrated' 等（任意）
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint line_weather_daily_cache_date_uidx unique (cache_key, weather_date)
);

create index if not exists line_weather_daily_lookup_idx
  on public.line_weather_daily (cache_key, weather_date);

alter table public.line_weather_daily enable row level security;

do $$
begin
  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'line_weather_daily'
      and policyname = 'Service role can do everything on line_weather_daily'
  ) then
    create policy "Service role can do everything on line_weather_daily"
      on public.line_weather_daily
      for all
      using (auth.jwt() ->> 'role' = 'service_role');
  end if;
end;
$$;

comment on table public.line_weather_daily
  is 'analytics 天候キャッシュ（恒久保存）。admin-api /weather/daily が取得した日次天気を cache_key×日付で保存する。';

-- 既存（line_sales_month_budgets の weather:* 流用）キャッシュを新テーブルへ移行（ベストエフォート）。
-- 失敗しても新テーブル作成自体は成功させる（天気は再取得で自己回復するため）。
do $$
begin
  insert into public.line_weather_daily (cache_key, weather_date, temp_max_c, precipitation_mm, source)
  select
    substring(b.store_partition_key from 9) as cache_key,  -- 'weather:' は8文字
    (e.key)::date as weather_date,
    nullif(e.value ->> 'temp', '')::numeric as temp_max_c,
    nullif(e.value ->> 'rain', '')::numeric as precipitation_mm,
    'migrated' as source
  from (
    select store_partition_key, store_closed_dates
    from public.line_sales_month_budgets
    where store_partition_key like 'weather:%'
      and jsonb_typeof(store_closed_dates) = 'object'
  ) b
  cross join lateral jsonb_each(b.store_closed_dates) as e(key, value)
  where e.key ~ '^\d{4}-\d{2}-\d{2}$'
  on conflict (cache_key, weather_date) do nothing;
exception when others then
  raise notice 'weather cache migration skipped: %', sqlerrm;
end;
$$;
