-- フェーズ2・3: RAGチャンク分割テーブル (store_knowledge_chunks) および pgvector 設定

-- pgvector 拡張機能の有効化（使用可能な場合）
create extension if not exists vector with schema extensions;
create extension if not exists pg_trgm with schema extensions;

-- RAG チャンク保持用テーブル
create table if not exists public.store_knowledge_chunks (
  id bigint generated by default as identity primary key,
  document_id bigint not null references public.store_knowledge_documents(id) on delete cascade,
  store_partition_key text not null,
  chunk_index integer not null default 0,
  chunk_text text not null check (length(btrim(chunk_text)) > 0),
  search_text text not null default '',
  embedding extensions.vector(1536),           -- OpenAI / Gemini embedding 互換 (nullable)
  token_count integer not null default 0,
  created_at timestamptz not null default now()
);

-- インデックスの作成
create index if not exists store_knowledge_chunks_doc_idx
  on public.store_knowledge_chunks (store_partition_key, document_id, chunk_index);

create index if not exists store_knowledge_chunks_search_trgm_idx
  on public.store_knowledge_chunks using gin (search_text gin_trgm_ops);

-- RLS 設定
alter table public.store_knowledge_chunks enable row level security;
revoke all on table public.store_knowledge_chunks from anon, authenticated;
grant select, insert, update, delete on public.store_knowledge_chunks to service_role;

comment on table public.store_knowledge_chunks is
  'Journal Report 店舗ナレッジのRAG用テキスト分割チャンク。PDF/画像/長文のAI自動抽出テキストを格納。';
