-- 月次日別売上管理表（Excel/CSV）を LINE にアップロードした際の取込一時保存。
-- 重複（既存レシートあり）や店舗名不一致のときは、確認カード（置き換える/中止）の postback で確定するため
-- 解析結果をここに pending 保存する。新規かつ店舗一致のときは確認なしで即登録するため pending には残さない。
create table if not exists public.pending_daily_sales_imports (
  id bigint generated by default as identity primary key,
  room_id text,
  store_partition_key text,          -- 投入先（そのルームの店舗）
  file_store_name text,              -- ファイル記載の「対象店舗」
  file_name text,
  line_message_id text,
  period text,
  entries jsonb not null,            -- DailySalesImportEntry[]（sales_date/gross_sales_yen/party_count/guest_count）
  day_count integer not null default 0,
  total_gross_yen bigint not null default 0,
  existing_count integer not null default 0,   -- 取込対象日に既にあるレシート件数（重複検出）
  store_matched boolean not null default true, -- ルーム店舗とファイル店舗名(ゆらぎ照合)が一致したか
  status text not null default 'pending',       -- pending | imported | dismissed
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists pending_daily_sales_imports_status_idx
  on public.pending_daily_sales_imports (status, created_at desc);
create index if not exists pending_daily_sales_imports_msg_idx
  on public.pending_daily_sales_imports (line_message_id);

alter table public.pending_daily_sales_imports enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'pending_daily_sales_imports'
      and policyname = 'Service role pending_daily_sales_imports'
  ) then
    create policy "Service role pending_daily_sales_imports"
      on public.pending_daily_sales_imports
      for all
      using (auth.jwt() ->> 'role' = 'service_role');
  end if;
end;
$$;
