-- メディア・予定トーク・売上の検索用アーカイブ（常時記録 / 検索はルーム設定ONのみ）

-- ---------------------------------------------------------------------------
-- Media search archive
-- ---------------------------------------------------------------------------

create table if not exists public.line_room_media_search (
  id bigint generated by default as identity primary key,
  room_id text not null,
  line_message_id text,
  user_id text,
  media_type text not null default 'unknown',
  original_file_name text,
  content_preview text not null default '',
  created_at timestamptz not null default now()
);

comment on table public.line_room_media_search is
  'メディア検索用（1年保持）。常時記録。検索は media_file_access_enabled のルームのみ。';

create unique index if not exists line_room_media_search_line_message_uidx
  on public.line_room_media_search (line_message_id)
  where line_message_id is not null;

create index if not exists line_room_media_search_room_created_idx
  on public.line_room_media_search (room_id, created_at desc);

create index if not exists line_room_media_search_created_idx
  on public.line_room_media_search (created_at desc);

create index if not exists line_room_media_search_preview_trgm_idx
  on public.line_room_media_search using gin (content_preview gin_trgm_ops);

create index if not exists line_room_media_search_filename_trgm_idx
  on public.line_room_media_search using gin (original_file_name gin_trgm_ops);

-- ---------------------------------------------------------------------------
-- Calendar talk archive (structured events remain in line_room_calendar_events)
-- ---------------------------------------------------------------------------

create table if not exists public.line_room_calendar_search (
  id bigint generated by default as identity primary key,
  room_id text not null,
  line_message_id text,
  event_title text not null default '',
  event_description text not null default '',
  starts_at timestamptz,
  source text not null default 'line_talk',
  created_at timestamptz not null default now()
);

comment on table public.line_room_calendar_search is
  '予定検索用トークアーカイブ（1年）。テキストは常時記録。GCal等は line_room_calendar_events と合わせて検索。';

create unique index if not exists line_room_calendar_search_line_message_uidx
  on public.line_room_calendar_search (line_message_id)
  where line_message_id is not null;

create index if not exists line_room_calendar_search_room_created_idx
  on public.line_room_calendar_search (room_id, created_at desc);

create index if not exists line_room_calendar_search_title_trgm_idx
  on public.line_room_calendar_search using gin (event_title gin_trgm_ops);

create index if not exists line_room_calendar_search_desc_trgm_idx
  on public.line_room_calendar_search using gin (event_description gin_trgm_ops);

-- ---------------------------------------------------------------------------
-- Document search archive (library / 2nd stage)
-- ---------------------------------------------------------------------------

create table if not exists public.line_room_document_search (
  id bigint generated by default as identity primary key,
  room_id text not null,
  line_message_id text,
  original_file_name text not null default '',
  extracted_text text not null default '',
  mime_type text,
  created_at timestamptz not null default now()
);

comment on table public.line_room_document_search is
  '資料検索用（1年）。ファイルメッセージを常時記録。検索は message_search_library_enabled のルームのみ。';

create unique index if not exists line_room_document_search_line_message_uidx
  on public.line_room_document_search (line_message_id)
  where line_message_id is not null;

create index if not exists line_room_document_search_room_created_idx
  on public.line_room_document_search (room_id, created_at desc);

create index if not exists line_room_document_search_name_trgm_idx
  on public.line_room_document_search using gin (original_file_name gin_trgm_ops);

create index if not exists line_room_document_search_text_trgm_idx
  on public.line_room_document_search using gin (extracted_text gin_trgm_ops);

-- ---------------------------------------------------------------------------
-- Receipt / sales search archive
-- ---------------------------------------------------------------------------

create table if not exists public.line_room_receipt_search (
  id bigint generated by default as identity primary key,
  room_id text not null,
  store_partition_key text,
  line_message_id text,
  receipt_date date,
  summary_text text not null default '',
  gross_sales_yen bigint,
  net_sales_yen bigint,
  receipt_table text not null,
  receipt_row_id bigint,
  created_at timestamptz not null default now()
);

comment on table public.line_room_receipt_search is
  '売上検索用（1年）。レシート保存時に常時記録。検索は receipt レポート系ONのルームのみ。';

create unique index if not exists line_room_receipt_search_receipt_row_uidx
  on public.line_room_receipt_search (receipt_table, receipt_row_id);

create index if not exists line_room_receipt_search_room_date_idx
  on public.line_room_receipt_search (room_id, receipt_date desc nulls last);

create index if not exists line_room_receipt_search_summary_trgm_idx
  on public.line_room_receipt_search using gin (summary_text gin_trgm_ops);

-- ---------------------------------------------------------------------------
-- Insert helpers
-- ---------------------------------------------------------------------------

create or replace function public.insert_line_room_media_search(
  p_room_id text,
  p_line_message_id text default null,
  p_user_id text default null,
  p_media_type text default 'unknown',
  p_original_file_name text default null,
  p_content_preview text default ''
)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  row_id bigint;
  preview text;
begin
  if not public.is_valid_line_room_id(p_room_id) then
    raise exception 'invalid room_id: %', p_room_id;
  end if;
  preview := coalesce(btrim(p_content_preview), '');
  if preview = '' and coalesce(btrim(p_original_file_name), '') = '' then
    return null;
  end if;
  insert into public.line_room_media_search (
    room_id, line_message_id, user_id, media_type, original_file_name, content_preview
  ) values (
    p_room_id,
    nullif(btrim(p_line_message_id), ''),
    nullif(btrim(p_user_id), ''),
    coalesce(nullif(btrim(p_media_type), ''), 'unknown'),
    nullif(btrim(p_original_file_name), ''),
    coalesce(preview, coalesce(btrim(p_original_file_name), ''))
  )
  on conflict (line_message_id) where line_message_id is not null
  do update set
    content_preview = excluded.content_preview,
    original_file_name = excluded.original_file_name,
    media_type = excluded.media_type
  returning id into row_id;
  return row_id;
end;
$$;

create or replace function public.insert_line_room_calendar_search(
  p_room_id text,
  p_line_message_id text default null,
  p_event_title text default '',
  p_event_description text default '',
  p_starts_at timestamptz default null,
  p_source text default 'line_talk'
)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  row_id bigint;
  title text;
  body text;
begin
  if not public.is_valid_line_room_id(p_room_id) then
    raise exception 'invalid room_id: %', p_room_id;
  end if;
  title := coalesce(btrim(p_event_title), '');
  body := coalesce(btrim(p_event_description), '');
  if title = '' and body = '' then
    return null;
  end if;
  if title = '' then
    title := left(body, 120);
  end if;
  insert into public.line_room_calendar_search (
    room_id, line_message_id, event_title, event_description, starts_at, source
  ) values (
    p_room_id,
    nullif(btrim(p_line_message_id), ''),
    title,
    body,
    p_starts_at,
    coalesce(nullif(btrim(p_source), ''), 'line_talk')
  )
  on conflict (line_message_id) where line_message_id is not null
  do update set
    event_title = excluded.event_title,
    event_description = excluded.event_description,
    starts_at = excluded.starts_at
  returning id into row_id;
  return row_id;
end;
$$;

create or replace function public.insert_line_room_document_search(
  p_room_id text,
  p_line_message_id text default null,
  p_original_file_name text default '',
  p_extracted_text text default '',
  p_mime_type text default null
)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  row_id bigint;
begin
  if not public.is_valid_line_room_id(p_room_id) then
    raise exception 'invalid room_id: %', p_room_id;
  end if;
  insert into public.line_room_document_search (
    room_id, line_message_id, original_file_name, extracted_text, mime_type
  ) values (
    p_room_id,
    nullif(btrim(p_line_message_id), ''),
    coalesce(btrim(p_original_file_name), ''),
    coalesce(btrim(p_extracted_text), ''),
    nullif(btrim(p_mime_type), '')
  )
  on conflict (line_message_id) where line_message_id is not null
  do update set
    original_file_name = excluded.original_file_name,
    extracted_text = excluded.extracted_text,
    mime_type = excluded.mime_type
  returning id into row_id;
  return row_id;
end;
$$;

create or replace function public.upsert_line_room_receipt_search(
  p_room_id text,
  p_store_partition_key text default null,
  p_line_message_id text default null,
  p_receipt_date date default null,
  p_summary_text text default '',
  p_gross_sales_yen bigint default null,
  p_net_sales_yen bigint default null,
  p_receipt_table text default '',
  p_receipt_row_id bigint default null
)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  row_id bigint;
begin
  if not public.is_valid_line_room_id(p_room_id) then
    raise exception 'invalid room_id: %', p_room_id;
  end if;
  if coalesce(btrim(p_receipt_table), '') = '' or p_receipt_row_id is null then
    return null;
  end if;
  insert into public.line_room_receipt_search (
    room_id, store_partition_key, line_message_id, receipt_date, summary_text,
    gross_sales_yen, net_sales_yen, receipt_table, receipt_row_id
  ) values (
    p_room_id,
    nullif(btrim(p_store_partition_key), ''),
    nullif(btrim(p_line_message_id), ''),
    p_receipt_date,
    coalesce(btrim(p_summary_text), ''),
    p_gross_sales_yen,
    p_net_sales_yen,
    btrim(p_receipt_table),
    p_receipt_row_id
  )
  on conflict (receipt_table, receipt_row_id)
  do update set
    summary_text = excluded.summary_text,
    gross_sales_yen = excluded.gross_sales_yen,
    net_sales_yen = excluded.net_sales_yen,
    receipt_date = excluded.receipt_date,
    line_message_id = excluded.line_message_id
  returning id into row_id;
  return row_id;
end;
$$;

-- ---------------------------------------------------------------------------
-- Search: media
-- ---------------------------------------------------------------------------

create or replace function public.search_line_room_media_search(
  p_query text,
  p_room_id text default null,
  p_limit integer default 50,
  p_offset integer default 0
)
returns table (
  id bigint,
  room_id text,
  line_message_id text,
  media_type text,
  original_file_name text,
  content_preview text,
  created_at timestamptz,
  total_count bigint
)
language plpgsql
security definer
set search_path = public
as $$
declare
  q text;
  lim int;
  off int;
  since timestamptz := now() - interval '365 days';
  pattern text;
begin
  q := btrim(coalesce(p_query, ''));
  if length(q) < 1 then raise exception 'query required'; end if;
  lim := greatest(1, least(coalesce(p_limit, 50), 100));
  off := greatest(coalesce(p_offset, 0), 0);
  pattern := '%' || replace(replace(q, '\', '\\'), '%', '\%') || '%';

  return query
  with searchable_rooms as (
    select rs.room_id from public.room_summary_settings rs
    where rs.media_file_access_enabled = true
  ),
  filtered as (
    select m.*
    from public.line_room_media_search m
    inner join searchable_rooms sr on sr.room_id = m.room_id
    where m.created_at >= since
      and (p_room_id is null or btrim(p_room_id) = '' or m.room_id = p_room_id)
      and (
        m.content_preview ilike pattern escape '\'
        or coalesce(m.original_file_name, '') ilike pattern escape '\'
      )
  ),
  counted as (select count(*)::bigint as cnt from filtered)
  select f.id, f.room_id, f.line_message_id, f.media_type, f.original_file_name, f.content_preview, f.created_at, c.cnt
  from filtered f cross join counted c
  order by f.created_at desc limit lim offset off;
end;
$$;

-- ---------------------------------------------------------------------------
-- Search: documents (library)
-- ---------------------------------------------------------------------------

create or replace function public.search_line_room_document_search(
  p_query text,
  p_room_id text default null,
  p_limit integer default 50,
  p_offset integer default 0
)
returns table (
  id bigint,
  room_id text,
  line_message_id text,
  original_file_name text,
  extracted_text text,
  mime_type text,
  created_at timestamptz,
  total_count bigint
)
language plpgsql
security definer
set search_path = public
as $$
declare
  q text;
  lim int;
  off int;
  since timestamptz := now() - interval '365 days';
  pattern text;
begin
  q := btrim(coalesce(p_query, ''));
  if length(q) < 1 then raise exception 'query required'; end if;
  lim := greatest(1, least(coalesce(p_limit, 50), 100));
  off := greatest(coalesce(p_offset, 0), 0);
  pattern := '%' || replace(replace(q, '\', '\\'), '%', '\%') || '%';

  return query
  with searchable_rooms as (
    select rs.room_id from public.room_summary_settings rs
    where rs.message_search_library_enabled = true
  ),
  filtered as (
    select d.*
    from public.line_room_document_search d
    inner join searchable_rooms sr on sr.room_id = d.room_id
    where d.created_at >= since
      and (p_room_id is null or btrim(p_room_id) = '' or d.room_id = p_room_id)
      and (
        d.original_file_name ilike pattern escape '\'
        or d.extracted_text ilike pattern escape '\'
      )
  ),
  counted as (select count(*)::bigint as cnt from filtered)
  select f.id, f.room_id, f.line_message_id, f.original_file_name, f.extracted_text, f.mime_type, f.created_at, c.cnt
  from filtered f cross join counted c
  order by f.created_at desc limit lim offset off;
end;
$$;

-- ---------------------------------------------------------------------------
-- Search: calendar (events + talk archive)
-- ---------------------------------------------------------------------------

create or replace function public.search_line_room_calendar_events(
  p_query text,
  p_room_id text default null,
  p_limit integer default 50,
  p_offset integer default 0
)
returns table (
  id bigint,
  room_id text,
  event_title text,
  event_description text,
  starts_at timestamptz,
  ends_at timestamptz,
  source text,
  external_event_id text,
  created_at timestamptz,
  total_count bigint
)
language plpgsql
security definer
set search_path = public
as $$
declare
  q text;
  lim int;
  off int;
  since timestamptz := now() - interval '365 days';
  pattern text;
begin
  q := btrim(coalesce(p_query, ''));
  if length(q) < 1 then raise exception 'query required'; end if;
  lim := greatest(1, least(coalesce(p_limit, 50), 100));
  off := greatest(coalesce(p_offset, 0), 0);
  pattern := '%' || replace(replace(q, '\', '\\'), '%', '\%') || '%';

  if p_room_id is not null and btrim(p_room_id) <> '' and not public.is_valid_line_room_id(p_room_id) then
    raise exception 'invalid room_id: %', p_room_id;
  end if;

  return query
  with searchable_rooms as (
    select rs.room_id
    from public.room_summary_settings rs
    where rs.calendar_ai_auto_create_enabled = true
       or rs.calendar_silent_auto_register_enabled = true
  ),
  unified as (
    select
      e.id::bigint as id,
      e.room_id,
      e.event_title,
      e.event_description,
      e.starts_at,
      e.ends_at,
      e.source,
      e.external_event_id,
      e.created_at
    from public.line_room_calendar_events e
    inner join searchable_rooms sr on sr.room_id = e.room_id
    where coalesce(e.starts_at, e.created_at) >= since
      and (p_room_id is null or btrim(p_room_id) = '' or e.room_id = p_room_id)
      and (
        e.event_title ilike pattern escape '\'
        or e.event_description ilike pattern escape '\'
      )
    union all
    select
      c.id::bigint,
      c.room_id,
      c.event_title,
      c.event_description,
      c.starts_at,
      null::timestamptz as ends_at,
      c.source,
      null::text as external_event_id,
      c.created_at
    from public.line_room_calendar_search c
    inner join searchable_rooms sr on sr.room_id = c.room_id
    where coalesce(c.starts_at, c.created_at) >= since
      and (p_room_id is null or btrim(p_room_id) = '' or c.room_id = p_room_id)
      and (
        c.event_title ilike pattern escape '\'
        or c.event_description ilike pattern escape '\'
      )
  ),
  filtered as (
    select * from unified
  ),
  counted as (
    select count(*)::bigint as cnt from filtered
  )
  select
    f.id, f.room_id, f.event_title, f.event_description, f.starts_at, f.ends_at, f.source, f.external_event_id, f.created_at, c.cnt
  from filtered f
  cross join counted c
  order by coalesce(f.starts_at, f.created_at) desc nulls last
  limit lim offset off;
end;
$$;

-- ---------------------------------------------------------------------------
-- Search: sales / receipts
-- ---------------------------------------------------------------------------

create or replace function public.search_line_room_receipt_search(
  p_query text,
  p_room_id text default null,
  p_receipt_date date default null,
  p_limit integer default 50,
  p_offset integer default 0
)
returns table (
  id bigint,
  room_id text,
  receipt_date date,
  summary_text text,
  gross_sales_yen bigint,
  net_sales_yen bigint,
  line_message_id text,
  created_at timestamptz,
  total_count bigint
)
language plpgsql
security definer
set search_path = public
as $$
declare
  q text;
  lim int;
  off int;
  since timestamptz := now() - interval '365 days';
  pattern text;
begin
  lim := greatest(1, least(coalesce(p_limit, 50), 100));
  off := greatest(coalesce(p_offset, 0), 0);

  return query
  with searchable_rooms as (
    select rs.room_id
    from public.room_summary_settings rs
    where rs.receipt_midreport_enabled = true
       or rs.receipt_monthend_report_enabled = true
  ),
  filtered as (
    select r.*
    from public.line_room_receipt_search r
    inner join searchable_rooms sr on sr.room_id = r.room_id
    where r.created_at >= since
      and (p_room_id is null or btrim(p_room_id) = '' or r.room_id = p_room_id)
      and (p_receipt_date is null or r.receipt_date = p_receipt_date)
      and (
        p_receipt_date is not null
        or (
          coalesce(btrim(p_query), '') <> ''
          and r.summary_text ilike (
            '%' || replace(replace(btrim(p_query), '\', '\\'), '%', '\%') || '%'
          ) escape '\'
        )
      )
  ),
  counted as (select count(*)::bigint as cnt from filtered)
  select f.id, f.room_id, f.receipt_date, f.summary_text, f.gross_sales_yen, f.net_sales_yen, f.line_message_id, f.created_at, c.cnt
  from filtered f cross join counted c
  order by coalesce(f.receipt_date, f.created_at::date) desc nulls last, f.created_at desc
  limit lim offset off;
end;
$$;

-- ---------------------------------------------------------------------------
-- Purge extension
-- ---------------------------------------------------------------------------

create or replace function public.purge_line_room_messages_older_than(
  p_retention_days integer default 365
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  days int;
  cutoff timestamptz;
  search_deleted bigint := 0;
  calendar_deleted bigint := 0;
  calendar_talk_deleted bigint := 0;
  media_deleted bigint := 0;
  document_deleted bigint := 0;
  receipt_deleted bigint := 0;
  room_deleted bigint := 0;
  rec record;
  n bigint;
begin
  days := greatest(coalesce(p_retention_days, 365), 1);
  cutoff := now() - make_interval(days => days);

  delete from public.line_room_messages_search where created_at < cutoff;
  get diagnostics search_deleted = row_count;

  delete from public.line_room_calendar_events where coalesce(starts_at, created_at) < cutoff;
  get diagnostics calendar_deleted = row_count;

  delete from public.line_room_calendar_search where coalesce(starts_at, created_at) < cutoff;
  get diagnostics calendar_talk_deleted = row_count;

  delete from public.line_room_media_search where created_at < cutoff;
  get diagnostics media_deleted = row_count;

  delete from public.line_room_document_search where created_at < cutoff;
  get diagnostics document_deleted = row_count;

  delete from public.line_room_receipt_search where created_at < cutoff;
  get diagnostics receipt_deleted = row_count;

  for rec in select room_id, message_table from public.line_room_message_tables loop
    execute format('delete from public.%I where created_at < $1', rec.message_table) using cutoff;
    get diagnostics n = row_count;
    room_deleted := room_deleted + coalesce(n, 0);
  end loop;

  return jsonb_build_object(
    'retention_days', days,
    'cutoff', cutoff,
    'search_index_deleted', search_deleted,
    'calendar_deleted', calendar_deleted,
    'calendar_talk_deleted', calendar_talk_deleted,
    'media_deleted', media_deleted,
    'document_deleted', document_deleted,
    'receipt_search_deleted', receipt_deleted,
    'room_tables_deleted', room_deleted
  );
end;
$$;

alter table public.line_room_media_search enable row level security;
alter table public.line_room_calendar_search enable row level security;
alter table public.line_room_document_search enable row level security;
alter table public.line_room_receipt_search enable row level security;
