-- 予約表の手動編集対応:
--   (1) 既存予約（食べログ/一休）の直接編集・店舗振り分けの手動上書き・ソフト削除（非表示）
--   (2) 手入力の新規予約
-- いずれも「追加のみ」で既存の取込・表示の挙動は変えない。
-- ソフト削除は manual_hidden=true（行は物理削除せず残す）→ カレンダー表示からは除外しつつ、
-- キャンセル率などの集計のために記録は保持する。

-- ───────────────────────────────────────────────────────────
-- (1) 既存イベント表へ手動編集用カラムを追加（tabelog / ikyu 共通）
--     - manual_hidden        : ソフト削除（非表示）フラグ
--     - manual_hidden_reason : 'cancel'（キャンセル）/ 'mistake'（誤登録）など任意
--     - manual_store_key     : 店舗振り分けの手動上書き（未分類・誤判定の修正用。null なら従来どおり店名から自動判定）
--     - manual_edited_at     : 最終手動編集時刻（監査用）
-- ───────────────────────────────────────────────────────────
alter table public.tabelog_reservation_visit_events
  add column if not exists manual_hidden boolean not null default false,
  add column if not exists manual_hidden_reason text,
  add column if not exists manual_store_key text,
  add column if not exists manual_edited_at timestamptz;

alter table public.ikyu_reservation_visit_events
  add column if not exists manual_hidden boolean not null default false,
  add column if not exists manual_hidden_reason text,
  add column if not exists manual_store_key text,
  add column if not exists manual_edited_at timestamptz;

-- ───────────────────────────────────────────────────────────
-- (2) 手入力（新規）予約テーブル。既存 *_reservation_visit_events と同形 ＋ 手動カラム。
--     source = "manual" として calendar / search に統合する。
-- ───────────────────────────────────────────────────────────
create table if not exists public.manual_reservation_visit_events (
  id bigint generated by default as identity primary key,
  customer_name text,
  customer_phone text,
  visit_at timestamptz not null,
  reservation_type text,
  reservation_detail text,
  manual_store_key text,
  manual_hidden boolean not null default false,
  manual_hidden_reason text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists manual_reservation_visit_events_visit_at_idx
  on public.manual_reservation_visit_events (visit_at);

create index if not exists manual_reservation_visit_events_customer_idx
  on public.manual_reservation_visit_events (customer_name, customer_phone);

alter table public.manual_reservation_visit_events enable row level security;

-- service_role（Edge Function）のみ全操作可。anon/authenticated はポリシー無し＝遮断。
do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'manual_reservation_visit_events'
      and policyname = 'Service role manual_reservation_visit_events'
  ) then
    create policy "Service role manual_reservation_visit_events"
      on public.manual_reservation_visit_events
      for all
      using (auth.jwt() ->> 'role' = 'service_role');
  end if;
end;
$$;
