-- 予算登録フロー（LINEルームから月次予算を入力する会話）の途中状態だけを保持する専用テーブル。
-- 他テーブル・他処理には一切干渉しない（このフロー専用）。
create table if not exists public.store_budget_entry_pending (
  id bigint generated by default as identity primary key,
  conversation_key text not null,
  room_id text not null,
  user_id text,
  store_partition_key text not null,
  step text not null,
  target_month text,
  expires_at timestamptz not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint store_budget_entry_pending_key_uidx unique (conversation_key),
  constraint store_budget_entry_pending_step_chk check (step in ('await_month', 'await_amount')),
  constraint store_budget_entry_pending_month_chk
    check (target_month is null or target_month ~ '^\d{4}-(0[1-9]|1[0-2])$')
);

create index if not exists store_budget_entry_pending_expires_idx
  on public.store_budget_entry_pending (expires_at);

alter table public.store_budget_entry_pending enable row level security;

do $$
begin
  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'store_budget_entry_pending'
      and policyname = 'Service role can do everything on store_budget_entry_pending'
  ) then
    create policy "Service role can do everything on store_budget_entry_pending"
      on public.store_budget_entry_pending
      for all
      using (auth.jwt() ->> 'role' = 'service_role');
  end if;
end;
$$;
