-- 予約AIキャッシュcronの実行履歴。失敗・長時間未更新を検知し、AI APIが安全にDBへフォールバックする。

create table if not exists public.reservation_ai_cache_runs (
  id bigint generated by default as identity primary key,
  status text not null check (status in ('running', 'success', 'failed')),
  started_at timestamptz not null default now(),
  finished_at timestamptz,
  cutoff_date_jst date,
  store_count integer not null default 0,
  cached_day_count integer not null default 0,
  reservation_row_count integer not null default 0,
  duration_ms integer,
  error_message text,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists reservation_ai_cache_runs_status_started_idx
  on public.reservation_ai_cache_runs (status, started_at desc);

alter table public.reservation_ai_cache_runs enable row level security;
revoke all on table public.reservation_ai_cache_runs from public, anon, authenticated;
grant all on table public.reservation_ai_cache_runs to service_role;

comment on table public.reservation_ai_cache_runs is
  'reservation-ai-cache-cronの実行履歴。最終成功時刻が36時間超ならAI APIはキャッシュを使わずDB直接参照へ退避する。';
