-- 予約スクショ（予約管理アプリの確認画面）をLINEで受信→AI解析→確認カードの「登録」ボタンで確定する仕組みの一時保存。
-- 画像を解析した時点では本登録せず、ここに pending として保存する。確認カードの postback(resv_imp=<id>)
-- が押されたら manual_reservation_visit_events へ本登録する（誤読をその場で確認・防止できる）。
create table if not exists public.pending_reservation_imports (
  id bigint generated by default as identity primary key,
  room_id text,
  store_partition_key text,
  line_message_id text,
  -- AIが抽出した予約内容（visit_at(ISO)/customer_name/customer_phone/party_size/plan/store_name/reservation_type 等）。
  payload jsonb not null,
  status text not null default 'pending',  -- pending | registered | dismissed
  manual_reservation_id bigint,            -- 本登録した manual_reservation_visit_events.id
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists pending_reservation_imports_status_idx
  on public.pending_reservation_imports (status, created_at desc);

-- 同一LINE画像の二重処理を避けるための索引（line_message_id でべき等化に利用）。
create index if not exists pending_reservation_imports_msg_idx
  on public.pending_reservation_imports (line_message_id);

alter table public.pending_reservation_imports enable row level security;

-- service_role（Edge Function）のみ全操作可。anon/authenticated はポリシー無し＝遮断。
do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'pending_reservation_imports'
      and policyname = 'Service role pending_reservation_imports'
  ) then
    create policy "Service role pending_reservation_imports"
      on public.pending_reservation_imports
      for all
      using (auth.jwt() ->> 'role' = 'service_role');
  end if;
end;
$$;
