-- 日次売上の手入力上書きテーブル。
-- 売上分析画面の「日次売上（数値）」表から、各日の 売上・組数・客数 を直接編集できるようにする。
-- 値が入っている日は、その日のレシート集計よりこの手入力を優先する（=日別表示・月間合計に反映）。
-- 列ごとに個別上書き可能（gross だけ／組数だけ等）。未入力(null)の列はレシート集計へフォールバック。
-- 3列すべて null になったらアプリ側で行ごと削除し、その日は完全にレシート集計へ戻す。
create table if not exists public.line_sales_manual_day (
  id bigint generated by default as identity primary key,
  store_partition_key text not null,
  sales_date date not null,
  gross_sales_yen bigint,
  party_count bigint,
  guest_count bigint,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint line_sales_manual_day_gross_chk check (gross_sales_yen is null or gross_sales_yen >= 0),
  constraint line_sales_manual_day_party_chk check (party_count is null or party_count >= 0),
  constraint line_sales_manual_day_guest_chk check (guest_count is null or guest_count >= 0),
  constraint line_sales_manual_day_store_date_uidx unique (store_partition_key, sales_date)
);

create index if not exists line_sales_manual_day_date_idx
  on public.line_sales_manual_day (sales_date desc);

alter table public.line_sales_manual_day enable row level security;

do $$
begin
  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'line_sales_manual_day'
      and policyname = 'Service role line_sales_manual_day'
  ) then
    create policy "Service role line_sales_manual_day"
      on public.line_sales_manual_day
      for all
      using (auth.jwt() ->> 'role' = 'service_role');
  end if;
end;
$$;
