-- 小口現金 LINE取込の会話状態。
--   「経費」と送る → await_image（画像待ち）→ 画像で抽出 → await_confirm（確認待ち）
--   → 確認カードの postback で petty_cash_entries に記録（status=recorded）。
-- 売上/予約/予算フローには干渉しない（このフロー専用）。
create table if not exists public.petty_cash_pending (
  id bigint generated by default as identity primary key,
  conversation_key text not null unique,            -- room::user
  room_id text not null,
  user_id text,
  store_partition_key text,
  status text not null default 'await_image'
    check (status in ('await_image', 'await_confirm', 'recorded', 'dismissed')),
  line_message_id text,                             -- 取込画像のメッセージID（記録時の重複防止に使用）
  spent_on date,
  item text,
  amount_yen integer,                               -- 出金額（合計・税込）
  tax_yen integer,                                  -- うち税額
  handler text,
  store_name text,                                  -- レシートの店名（仕入先）
  category text,
  expires_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists petty_cash_pending_status_idx
  on public.petty_cash_pending (status, updated_at desc);

alter table public.petty_cash_pending enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'petty_cash_pending'
      and policyname = 'Service role petty_cash_pending'
  ) then
    create policy "Service role petty_cash_pending"
      on public.petty_cash_pending
      for all
      using (auth.jwt() ->> 'role' = 'service_role');
  end if;
end;
$$;
