-- 画像（予約スクショ）から登録した予約を、メール予約と同じく
-- 「予約回数」サマリと「過去の予約」履歴（reservation_customer_visit_history）に算入する。
--   - メール予約: tabelog/ikyu の partner として履歴＋サマリへ
--   - 画像予約  : partner='manual' として履歴＋専用サマリ(manual_reservation_visit_summaries)へ
-- 表示用イベント行は従来どおり manual_reservation_visit_events に入る（本変更とは別経路）。

-- 1) 履歴テーブルの partner に 'manual' を許可（既存の tabelog/ikyu に追加）
alter table public.reservation_customer_visit_history
  drop constraint if exists reservation_customer_visit_history_partner_check;
alter table public.reservation_customer_visit_history
  add constraint reservation_customer_visit_history_partner_check
  check (partner in ('tabelog', 'ikyu', 'manual'));

-- 2) 画像/手入力予約用の「予約回数」サマリ（partner サマリと同じ列構成）
create table if not exists public.manual_reservation_visit_summaries (
  id bigint generated by default as identity primary key,
  customer_name text not null,
  customer_phone text not null,
  visit_count integer not null default 0,
  last_visit_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint manual_reservation_visit_summaries_name_phone_uidx
    unique (customer_name, customer_phone)
);

alter table public.manual_reservation_visit_summaries enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'manual_reservation_visit_summaries'
      and policyname = 'Service role manual_reservation_visit_summaries'
  ) then
    create policy "Service role manual_reservation_visit_summaries"
      on public.manual_reservation_visit_summaries
      for all
      using (auth.jwt() ->> 'role' = 'service_role');
  end if;
end;
$$;

-- 3) 画像/手入力予約を履歴＋サマリへ登録する RPC（メールの record_partner_reservation_visit と同じ思想）
--    - p_dedup_key: 重複登録防止キー（例: 'manual:<イベントID>'）。再送・再押下で二重カウントしない。
--    - 氏名・電話の両方が無い予約はカウントしない（メールと同条件）。
--    - キャンセル相当は visit_count を -1（greatest(0,...)）、それ以外は +1。
create or replace function public.record_manual_reservation_visit(
  p_dedup_key text,
  p_customer_name text,
  p_customer_phone text,
  p_visit_at timestamptz default null,
  p_reservation_type text default null,
  p_reservation_detail text default null
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_name text;
  v_phone text;
  v_visit_at timestamptz;
  v_cancelled boolean;
  v_row_count integer;
  v_visit_count integer;
  v_recent jsonb;
  v_type text;
  v_detail text;
begin
  if nullif(trim(p_dedup_key), '') is null then
    return null;
  end if;

  v_name := nullif(trim(p_customer_name), '');
  v_phone := nullif(trim(p_customer_phone), '');
  if v_name is null or v_phone is null then
    return null;
  end if;

  v_visit_at := coalesce(p_visit_at, now());
  v_type := nullif(trim(coalesce(p_reservation_type, '')), '');
  v_detail := nullif(trim(coalesce(p_reservation_detail, '')), '');
  v_cancelled := public.reservation_visit_looks_cancelled(v_type, v_detail);

  insert into public.reservation_customer_visit_history (
    partner, gmail_message_id, customer_name, customer_phone,
    visit_at, reservation_type, reservation_detail, is_cancelled
  ) values (
    'manual', p_dedup_key, v_name, v_phone,
    v_visit_at, v_type, v_detail, v_cancelled
  )
  on conflict (partner, gmail_message_id) do nothing;
  get diagnostics v_row_count = row_count;

  if v_row_count > 0 then
    if v_cancelled then
      insert into public.manual_reservation_visit_summaries (
        customer_name, customer_phone, visit_count, last_visit_at, created_at, updated_at
      ) values (v_name, v_phone, 0, null, now(), now())
      on conflict (customer_name, customer_phone) do update
        set visit_count = greatest(0, manual_reservation_visit_summaries.visit_count - 1),
            updated_at = now();
    else
      insert into public.manual_reservation_visit_summaries (
        customer_name, customer_phone, visit_count, last_visit_at, created_at, updated_at
      ) values (v_name, v_phone, 1, v_visit_at, now(), now())
      on conflict (customer_name, customer_phone) do update
        set visit_count = manual_reservation_visit_summaries.visit_count + 1,
            last_visit_at = greatest(
              coalesce(manual_reservation_visit_summaries.last_visit_at, excluded.last_visit_at),
              excluded.last_visit_at
            ),
            updated_at = now();
    end if;
  end if;

  select visit_count into v_visit_count
  from public.manual_reservation_visit_summaries
  where customer_name = v_name and customer_phone = v_phone
  limit 1;
  v_visit_count := coalesce(v_visit_count, 0);

  v_recent := public.get_reservation_recent_visits_json('manual', v_name, v_phone, p_dedup_key, 5);

  return jsonb_build_object(
    'visit_count', v_visit_count,
    'recent_visits', v_recent
  );
end;
$$;
