-- POS電子ジャーナル: 原本を非公開Storageへ保存し、解析済み日次データを管理API経由で参照する。
-- 公開Pagesはこのテーブル/Storageを直接参照せず、service_roleを使うadmin-apiのみが操作する。

create table if not exists public.pos_journal_files (
  id bigint generated by default as identity primary key,
  store_partition_key text not null,
  store_code text not null,
  business_date date not null,
  year_month text not null,
  original_file_name text not null,
  inner_file_name text,
  storage_bucket text not null default 'pos-journals',
  storage_path text not null,
  mime_type text not null default 'application/x-lzh-compressed',
  file_size_bytes bigint not null check (file_size_bytes > 0),
  sha256_hex text not null check (sha256_hex ~ '^[0-9a-f]{64}$'),
  parsed_data jsonb not null,
  net_sales bigint not null default 0,
  tax_yen bigint not null default 0,
  gross_sales bigint not null default 0,
  groups_count integer not null default 0,
  guests_count integer not null default 0,
  receipts_count integer not null default 0,
  storage_deleted_at timestamptz,
  storage_delete_error text,
  delete_snapshot jsonb,
  uploaded_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint pos_journal_files_store_code_format check (store_code ~ '^[0-9]{4}$'),
  constraint pos_journal_files_year_month_format check (year_month ~ '^[0-9]{4}-(0[1-9]|1[0-2])$'),
  constraint pos_journal_files_month_consistency check (
    year_month = (extract(year from business_date)::integer::text || '-' || lpad(extract(month from business_date)::integer::text, 2, '0'))
  ),
  constraint pos_journal_files_unique_storage_object unique (storage_bucket, storage_path)
);

create index if not exists pos_journal_files_store_month_date_idx
  on public.pos_journal_files (store_partition_key, year_month, business_date desc);
create unique index if not exists pos_journal_files_active_business_day_uidx
  on public.pos_journal_files (store_partition_key, business_date)
  where storage_deleted_at is null;
create unique index if not exists pos_journal_files_active_hash_uidx
  on public.pos_journal_files (store_partition_key, sha256_hex)
  where storage_deleted_at is null;

alter table public.pos_journal_files enable row level security;
revoke all on table public.pos_journal_files from anon, authenticated;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'pos-journals',
  'pos-journals',
  false,
  8388608,
  array['application/x-lzh-compressed', 'application/octet-stream']::text[]
)
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;
