-- 「明日の予約状況」配信機能（Gmail予約通知とは別の権限）
-- 既存の「Gmail予約通知（gmail_reservation_alert_enabled）」はリアルタイム1件ずつ通知。
-- 本機能は別トグルで、対象店舗の「明日の予約」を1日1回・指定時刻に1通のリッチテキスト(Flex)で一括送信する。
--   tomorrow_reservation_alert_enabled : このルームで明日予約の一括配信を行うか
--   tomorrow_reservation_alert_hour    : 送信時刻の時(0-23)。NULL=既定(18時)継承
--   tomorrow_reservation_alert_minute  : 送信時刻の分(0-59)。NULL=既定(0分)継承
-- 対象予約は店舗単位（ルームの receipt_report_store_partition_key と予約のstoreNameを照合）。

alter table public.room_summary_settings
  add column if not exists tomorrow_reservation_alert_enabled boolean not null default false,
  add column if not exists tomorrow_reservation_alert_hour integer,
  add column if not exists tomorrow_reservation_alert_minute integer;

comment on column public.room_summary_settings.tomorrow_reservation_alert_enabled
  is '明日の予約状況を1日1回まとめて配信するか（Gmail予約通知とは別権限）';
comment on column public.room_summary_settings.tomorrow_reservation_alert_hour
  is '明日予約配信の送信時刻 時(0-23)。NULL=既定(18時)継承';
comment on column public.room_summary_settings.tomorrow_reservation_alert_minute
  is '明日予約配信の送信時刻 分(0-59)。NULL=既定(0分)継承';

-- 二重送信防止ログ（ルーム×対象日でユニーク）。送信前に行を確保し、失敗時は取り消す。
create table if not exists public.reservation_tomorrow_alert_logs (
  id bigint generated by default as identity primary key,
  room_id text not null,
  target_date date not null,
  store_partition_key text,
  reservation_count integer not null default 0,
  sent_at timestamptz not null default now(),
  constraint reservation_tomorrow_alert_logs_room_date_uidx unique (room_id, target_date)
);

comment on table public.reservation_tomorrow_alert_logs
  is '明日予約配信の送信済み記録（room_id×target_dateで重複送信を防止）';

create index if not exists reservation_tomorrow_alert_logs_date_idx
  on public.reservation_tomorrow_alert_logs (target_date desc);

alter table public.reservation_tomorrow_alert_logs enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'reservation_tomorrow_alert_logs'
      and policyname = 'Service role reservation_tomorrow_alert_logs'
  ) then
    create policy "Service role reservation_tomorrow_alert_logs"
      on public.reservation_tomorrow_alert_logs
      for all
      using (auth.jwt() ->> 'role' = 'service_role');
  end if;
end;
$$;
