-- M-talk 感情イラストへ追加素材を登録する。

insert into public.chat_stickers (id, label, asset_path, sort_order, is_active) values
  ('otoshidama', 'お年玉', 'stickers/face/181215_otoshidama_1050w.png', 40, true),
  ('diet', 'ダイエット中', 'stickers/face/181217_diet4.png', 41, true),
  ('rain-drop', '雨です', 'stickers/face/1903_rayny_drop1.png', 42, true),
  ('raincoat', '雨の日', 'stickers/face/1903_rayny_raincoat3.png', 43, true),
  ('rain-storm', '大雨', 'stickers/face/1903_rayny_stormy1.png', 44, true),
  ('marry', 'お祝い', 'stickers/face/200315_b_marry_15.png', 45, true),
  ('exam', '勉強中', 'stickers/face/200322_a_exam_07-2.png', 46, true),
  ('sleepy-04', '眠い', 'stickers/face/200330_c_sleeepy_04.png', 47, true),
  ('sleepy-05', '目が覚めた', 'stickers/face/200330_c_sleeepy_05.png', 48, true),
  ('sleepy-07', '眠すぎる', 'stickers/face/200330_c_sleeepy_07.png', 49, true),
  ('hospitality', 'お茶をどうぞ', 'stickers/face/200330_hospitality_03.png', 50, true),
  ('relax', 'リラックス', 'stickers/face/200802_f_relax06.png', 51, true),
  ('summer-aircon', 'エアコン', 'stickers/face/200921_a_summer02.png', 52, true),
  ('summer-watermelon', 'スイカ', 'stickers/face/200921_a_summer07.png', 53, true),
  ('summer-greeting', '残暑お見舞い', 'stickers/face/200921_a_summer11.png', 54, true),
  ('summer-greeting-vertical', '残暑お見舞い', 'stickers/face/200921_a_summer12.png', 55, true),
  ('winter-greeting', '寒中お見舞い', 'stickers/face/200921_b_winter01.png', 56, true),
  ('winter-greeting-vertical', '寒中お見舞い', 'stickers/face/200921_b_winter02.png', 57, true),
  ('hot-weather', '暑い日', 'stickers/face/200921_c_weather01.png', 58, true),
  ('text-favorite', '本命', 'stickers/face/210127_text01_favorite.png', 59, true),
  ('text-obligatory', '義理', 'stickers/face/210127_text02_obligatory.png', 60, true),
  ('text-love', '好きです', 'stickers/face/210127_text03_iloveyou.png', 61, true),
  ('text-sorry', 'ごめんなさい', 'stickers/face/210127_text04_sorry.png', 62, true),
  ('text-thanks', 'ありがとう', 'stickers/face/210127_text05_thankyou.png', 63, true),
  ('text-regards', 'よろしく', 'stickers/face/210127_thankyou.png', 64, true),
  ('text-please', 'お願いします', 'stickers/face/210130_please.png', 65, true),
  ('love-heart', '大好き', 'stickers/face/210131_love01.png', 66, true),
  ('love-wave', 'うれしい', 'stickers/face/210131_love03.png', 67, true),
  ('scissors', 'はさみ', 'stickers/face/210217_scissors_cut02.png', 68, true),
  ('listen', '話を聞きます', 'stickers/face/221218_listen.png', 69, true),
  ('cold', '寒い', 'stickers/face/cold2.png', 70, true),
  ('friends', 'みんなでがんばろう', 'stickers/face/friend-1000x789.png', 71, true),
  ('grape', 'ワインをどうぞ', 'stickers/face/grape-extract.png', 72, true),
  ('hangon-new', 'がんばる', 'stickers/face/hangon.png', 73, true),
  ('sunrise-pose', '初日の出', 'stickers/face/hatsyuhinode2-1-1.png', 74, true),
  ('sunrise', '初日の出', 'stickers/face/hatsyuhinode2.png', 75, true),
  ('health-down', '落ち込み', 'stickers/face/health_a_200224_02.png', 76, true),
  ('health-sick', '体調不良', 'stickers/face/health_c_200224_03.png', 77, true),
  ('health-stock', '常備品', 'stickers/face/health_c_200224_06.png', 78, true),
  ('hot', '暑い', 'stickers/face/hot.png', 79, true),
  ('work-pc', 'パソコン作業中', 'stickers/face/ill_12_s.png', 80, true),
  ('meeting', '会議中', 'stickers/face/ill_16_s.png', 81, true),
  ('chef', '料理中', 'stickers/face/ill_18_s.png', 82, true),
  ('encounter', '一期一会', 'stickers/face/ill_aff005_l-340x450.png', 83, true),
  ('connect', 'みんなつながる', 'stickers/face/ill_aff006_l-430x450.png', 84, true),
  ('iceberg', '氷山の一角', 'stickers/face/ill_aff007_l-450x314.png', 85, true),
  ('worship', '初詣', 'stickers/face/newyear_worship.png', 86, true),
  ('cycling', 'サイクリング', 'stickers/face/olympic_Cycling_BMX_MountainBike_Road_Track_A_Illustration.png', 87, true),
  ('question-11', 'どうしたの？', 'stickers/face/question_Illustration1904_11.png', 88, true),
  ('recommend', 'イチオシ', 'stickers/face/recommend2.png', 89, true),
  ('searching', '検索中', 'stickers/face/search.png', 90, true),
  ('summer-rest', '休憩中', 'stickers/face/summer_Illustration_2.png', 91, true),
  ('train', '電車', 'stickers/face/transport_a_200224_01.png', 92, true),
  ('trial', '試行錯誤', 'stickers/face/trial.png', 93, true)
on conflict (id) do update set
  label = excluded.label,
  asset_path = excluded.asset_path,
  sort_order = excluded.sort_order,
  is_active = excluded.is_active;
