-- 明日の予定配信の時刻をルームごとに設定できるようにする。
-- トグル calendar_tomorrow_reminder_enabled は既存。時刻は未設定なら 19:00（従来の全体既定）。
-- 配信は reservation-today-cron と同じ「毎分ゲート＋関数側で時刻一致」。
-- 対象は line_room_calendar_events の翌日分（M-talk / LINE ルームの予定カレンダー）。

alter table public.room_summary_settings
  add column if not exists calendar_tomorrow_reminder_hour integer,
  add column if not exists calendar_tomorrow_reminder_minute integer;

comment on column public.room_summary_settings.calendar_tomorrow_reminder_hour
  is '明日の予定配信の送信時刻 時(0-23)。NULL=既定(19時)';
comment on column public.room_summary_settings.calendar_tomorrow_reminder_minute
  is '明日の予定配信の送信時刻 分(0-59)。NULL=既定(0分)';

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conname = 'room_summary_settings_calendar_tomorrow_reminder_hour_check'
  ) then
    alter table public.room_summary_settings
      add constraint room_summary_settings_calendar_tomorrow_reminder_hour_check
      check (calendar_tomorrow_reminder_hour is null or (calendar_tomorrow_reminder_hour >= 0 and calendar_tomorrow_reminder_hour <= 23));
  end if;
  if not exists (
    select 1 from pg_constraint
    where conname = 'room_summary_settings_calendar_tomorrow_reminder_minute_check'
  ) then
    alter table public.room_summary_settings
      add constraint room_summary_settings_calendar_tomorrow_reminder_minute_check
      check (calendar_tomorrow_reminder_minute is null or (calendar_tomorrow_reminder_minute >= 0 and calendar_tomorrow_reminder_minute <= 59));
  end if;
end $$;

create table if not exists public.calendar_tomorrow_reminder_logs (
  id bigint generated by default as identity primary key,
  room_id text not null,
  target_date date not null,
  store_partition_key text,
  event_count integer not null default 0,
  sent_at timestamptz not null default now(),
  constraint calendar_tomorrow_reminder_logs_room_date_uidx unique (room_id, target_date)
);

comment on table public.calendar_tomorrow_reminder_logs
  is '明日の予定配信の送信済み記録（room_id×対象日で重複送信を防止。対象日は翌日のJST日付）';

create index if not exists calendar_tomorrow_reminder_logs_date_idx
  on public.calendar_tomorrow_reminder_logs (target_date desc);

alter table public.calendar_tomorrow_reminder_logs enable row level security;
revoke all on table public.calendar_tomorrow_reminder_logs from public, anon, authenticated;
grant select, insert, update, delete on table public.calendar_tomorrow_reminder_logs to service_role;

create or replace function public.invoke_calendar_tomorrow_cron()
returns void
language plpgsql
security definer
set search_path = 'public', 'extensions'
as $$
declare
  v_now_jst timestamp := now() at time zone 'Asia/Tokyo';
begin
  if not exists (
    select 1
    from public.room_summary_settings s
    where s.calendar_tomorrow_reminder_enabled = true
      and coalesce(s.is_enabled, true) = true
      and extract(hour from v_now_jst)::int = coalesce(s.calendar_tomorrow_reminder_hour, 19)
      and extract(minute from v_now_jst)::int = coalesce(s.calendar_tomorrow_reminder_minute, 0)
  ) then
    return;
  end if;

  perform net.http_post(
    url := 'https://hocbnifuactbvmyjraxy.supabase.co/functions/v1/calendar-tomorrow-cron',
    headers := jsonb_build_object(
      'Authorization', 'Bearer ' || public.resolve_edge_cron_auth_token(),
      'Content-Type', 'application/json'
    ),
    body := '{}'::jsonb
  );
end;
$$;

revoke all on function public.invoke_calendar_tomorrow_cron() from public, anon, authenticated;
grant execute on function public.invoke_calendar_tomorrow_cron() to postgres, service_role;

create or replace function public.invoke_high_frequency_dispatcher_cron()
returns void
language plpgsql
security definer
set search_path = 'public', 'extensions', 'cron'
as $$
declare
  v_minute int := extract(minute from (now() at time zone 'Asia/Tokyo'))::int;
begin
  begin
    perform public.invoke_gmail_alert_cron();
  exception when others then
    raise warning 'high-frequency dispatcher: gmail failed: %', sqlerrm;
  end;

  begin
    perform public.invoke_receipt_midreport_cron();
  exception when others then
    raise warning 'high-frequency dispatcher: receipt-midreport failed: %', sqlerrm;
  end;

  begin
    perform public.invoke_reservation_today_cron();
  exception when others then
    raise warning 'high-frequency dispatcher: reservation-today failed: %', sqlerrm;
  end;

  begin
    perform public.invoke_calendar_tomorrow_cron();
  exception when others then
    raise warning 'high-frequency dispatcher: calendar-tomorrow failed: %', sqlerrm;
  end;

  begin
    perform public.invoke_review_alert_cron();
  exception when others then
    raise warning 'high-frequency dispatcher: review-alert failed: %', sqlerrm;
  end;

  begin
    perform public.invoke_tokyo_dome_weekly_cron();
  exception when others then
    raise warning 'high-frequency dispatcher: tokyo-dome-weekly failed: %', sqlerrm;
  end;

  if mod(v_minute, 5) = 0 then
    begin
      perform public.invoke_foodcourt_weekly_report_cron();
    exception when others then
      raise warning 'high-frequency dispatcher: foodcourt-weekly failed: %', sqlerrm;
    end;
  end if;

  if mod(v_minute, 10) = 0 then
    begin
      perform public.invoke_pv_japan_alert_cron();
    exception when others then
      raise warning 'high-frequency dispatcher: pv-japan failed: %', sqlerrm;
    end;
  end if;
end;
$$;
