-- 小口現金（出金/経費）台帳。売上(receipt)・予約とは独立した経費記録。
--   - 手入力（管理画面ページ）と LINE 出金レシート自動記録(source='line_image')の両対応。
--   - 削除は hidden=true の論理削除（行は残す）。

create table if not exists public.petty_cash_entries (
  id bigint generated by default as identity primary key,
  store_partition_key text not null,
  spent_on date not null,                                   -- 出金日
  item text,                                                -- 品目 / 摘要
  category text,                                            -- 勘定科目（消耗品費 等）
  amount_yen integer not null default 0,                    -- 出金額（円・税込）
  handler text,                                             -- 取扱者
  source text not null default 'manual'
    check (source in ('manual', 'line_image')),
  line_message_id text,                                     -- LINE画像取込時の重複防止キー
  note text,
  hidden boolean not null default false,                    -- 論理削除
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists petty_cash_entries_store_date_idx
  on public.petty_cash_entries (store_partition_key, spent_on desc);

-- LINE画像からの二重登録防止（line_message_id があるときのみ一意）
create unique index if not exists petty_cash_entries_line_message_uidx
  on public.petty_cash_entries (line_message_id)
  where line_message_id is not null;

alter table public.petty_cash_entries enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'petty_cash_entries'
      and policyname = 'Service role petty_cash_entries'
  ) then
    create policy "Service role petty_cash_entries"
      on public.petty_cash_entries
      for all
      using (auth.jwt() ->> 'role' = 'service_role');
  end if;
end;
$$;
