-- 売上分析（analytics）用: 予算・手入力・店舗休日（hocbn / admin-api）

create table if not exists public.line_sales_month_budgets (
  id bigint generated by default as identity primary key,
  store_partition_key text not null,
  target_month text not null,
  budget_yen bigint not null,
  weekday_weight numeric(14, 4) not null default 1
    constraint line_sales_month_budgets_weekday_weight_chk check (weekday_weight > 0),
  pre_holiday_weight numeric(14, 4) not null default 1.5
    constraint line_sales_month_budgets_pre_holiday_weight_chk check (pre_holiday_weight > 0),
  holiday_weight numeric(14, 4) not null default 2
    constraint line_sales_month_budgets_holiday_weight_chk check (holiday_weight > 0),
  store_closed_dates jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint line_sales_month_budgets_target_month_chk
    check (target_month ~ '^\d{4}-(0[1-9]|1[0-2])$'),
  constraint line_sales_month_budgets_budget_yen_chk check (budget_yen > 0),
  constraint line_sales_month_budgets_store_month_uidx unique (store_partition_key, target_month)
);

create index if not exists line_sales_month_budgets_month_idx
  on public.line_sales_month_budgets (target_month desc);

alter table public.line_sales_month_budgets enable row level security;

do $$
begin
  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'line_sales_month_budgets'
      and policyname = 'Service role can do everything on line_sales_month_budgets'
  ) then
    create policy "Service role can do everything on line_sales_month_budgets"
      on public.line_sales_month_budgets
      for all
      using (auth.jwt() ->> 'role' = 'service_role');
  end if;
end;
$$;

create table if not exists public.line_sales_month_store_closed_days (
  id bigint generated by default as identity primary key,
  store_partition_key text not null,
  target_month text not null,
  closed_on date not null,
  created_at timestamptz not null default now(),
  constraint line_sales_month_store_closed_days_target_month_chk
    check (target_month ~ '^\d{4}-(0[1-9]|1[0-2])$'),
  constraint line_sales_month_store_closed_days_store_month_date_uidx
    unique (store_partition_key, target_month, closed_on)
);

create index if not exists line_sales_month_store_closed_days_lookup_idx
  on public.line_sales_month_store_closed_days (store_partition_key, target_month);

alter table public.line_sales_month_store_closed_days enable row level security;

do $$
begin
  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'line_sales_month_store_closed_days'
      and policyname = 'Service role can do everything on line_sales_month_store_closed_days'
  ) then
    create policy "Service role can do everything on line_sales_month_store_closed_days"
      on public.line_sales_month_store_closed_days
      for all
      using (auth.jwt() ->> 'role' = 'service_role');
  end if;
end;
$$;

create table if not exists public.line_sales_manual_month_gross (
  id bigint generated by default as identity primary key,
  store_partition_key text not null,
  sales_month text not null,
  gross_sales_yen bigint not null,
  party_count bigint,
  guest_count bigint,
  operating_days_count bigint,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint line_sales_manual_month_fmt_chk
    check (sales_month ~ '^\d{4}-(0[1-9]|1[0-2])$'),
  constraint line_sales_manual_gross_yen_chk check (gross_sales_yen >= 0),
  constraint line_sales_manual_party_count_chk check (party_count is null or party_count >= 0),
  constraint line_sales_manual_guest_count_chk check (guest_count is null or guest_count >= 0),
  constraint line_sales_manual_operating_days_chk check (operating_days_count is null or operating_days_count > 0),
  constraint line_sales_manual_month_store_month_uidx unique (store_partition_key, sales_month)
);

create index if not exists line_sales_manual_month_sales_month_idx
  on public.line_sales_manual_month_gross (sales_month desc);

alter table public.line_sales_manual_month_gross enable row level security;

do $$
begin
  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'line_sales_manual_month_gross'
      and policyname = 'Service role line_sales_manual_month_gross'
  ) then
    create policy "Service role line_sales_manual_month_gross"
      on public.line_sales_manual_month_gross
      for all
      using (auth.jwt() ->> 'role' = 'service_role');
  end if;
end;
$$;
