-- Journal Report 店舗ナレッジ: 施策・メニュー等の資料を店舗ごとに登録し、AI分析の文脈として使う。
-- 公開Pagesは直接参照せず、service_role を使う admin-api のみが操作する（pos_journal_files と同方針）。
-- 店舗分離は store_partition_key。他店キーのアクセスは API 層で拒否する。

create table if not exists public.store_knowledge_documents (
  id bigint generated by default as identity primary key,
  store_partition_key text not null,
  category text not null check (category in
    ('施策', 'メニュー', '価格改定', 'イベント', 'マニュアル', 'その他')),
  title text not null check (length(btrim(title)) > 0),
  summary text not null default '',
  body_text text not null default '',
  search_text text not null default '',
  period_start date,
  period_end date,
  tags text[] not null default '{}',
  storage_bucket text not null default 'store-knowledge',
  storage_path text,
  original_file_name text,
  mime_type text,
  file_size_bytes bigint check (file_size_bytes is null or file_size_bytes > 0),
  sha256_hex text check (sha256_hex is null or sha256_hex ~ '^[0-9a-f]{64}$'),
  source_type text not null default 'manual'
    check (source_type in ('manual', 'upload', 'ai_insight')),
  is_active boolean not null default true,
  created_by text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint store_knowledge_period_order
    check (period_start is null or period_end is null or period_start <= period_end)
);

-- 期間の重なり判定（対象期間の施策を必ず添付する）で使う
create index if not exists store_knowledge_store_active_period_idx
  on public.store_knowledge_documents (store_partition_key, is_active, period_start desc);
create index if not exists store_knowledge_store_category_idx
  on public.store_knowledge_documents (store_partition_key, category, is_active);
-- pg_trgm は導入済み。フリーワード検索（部分一致）を高速化する
create index if not exists store_knowledge_search_trgm_idx
  on public.store_knowledge_documents using gin (search_text public.gin_trgm_ops);
-- 同じ添付ファイルの二重登録を防ぐ（pos_journal_files と同じ手法）
create unique index if not exists store_knowledge_active_hash_uidx
  on public.store_knowledge_documents (store_partition_key, sha256_hex)
  where is_active and sha256_hex is not null;

alter table public.store_knowledge_documents enable row level security;
revoke all on table public.store_knowledge_documents from anon, authenticated;
grant select, insert, update, delete on public.store_knowledge_documents to service_role;

comment on table public.store_knowledge_documents is
  'Journal Report 店舗ナレッジ（施策・メニュー資料）。店舗分離は store_partition_key。admin-api 経由のみ。';
comment on column public.store_knowledge_documents.period_start is
  '施策・メニューの適用開始日。null は期間指定なし（常時有効）として全期間の質問に添付する。';
comment on column public.store_knowledge_documents.search_text is
  'title + summary + body_text + tags を小文字正規化した検索用テキスト。API 側で組み立てる。';
comment on column public.store_knowledge_documents.source_type is
  'manual=手入力 / upload=ファイル添付 / ai_insight=AIが生成した施策効果メモ（フェーズ3）。';

-- 資料原本の保管先（非公開バケット）
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'store-knowledge',
  'store-knowledge',
  false,
  20971520,
  array[
    'application/pdf',
    'image/png',
    'image/jpeg',
    'image/webp',
    'text/plain',
    'text/csv',
    'text/markdown',
    'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    'application/octet-stream'
  ]::text[]
)
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;
