-- ルーム別トーク保存・1年保持・全文断片検索（pg_trgm）・横断検索インデックス

create extension if not exists pg_trgm;

-- ---------------------------------------------------------------------------
-- Registry: room_id → per-room message table
-- ---------------------------------------------------------------------------

create table if not exists public.line_room_message_tables (
  room_id text primary key,
  message_table text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

comment on table public.line_room_message_tables is
  'LINE room_id ごとのトーク保存テーブル名レジストリ（line_messages__*）';

create or replace function public.is_valid_line_room_id(p_room_id text)
returns boolean
language sql
immutable
as $$
  select coalesce(p_room_id, '') ~ '^[A-Za-z0-9][A-Za-z0-9_-]{0,120}$';
$$;

create or replace function public.line_room_message_table_name(p_room_id text)
returns text
language sql
immutable
as $$
  select 'line_messages__r' || substr(md5(p_room_id), 1, 16);
$$;

-- ---------------------------------------------------------------------------
-- Global search index (room-scoped + cross-room queries)
-- ---------------------------------------------------------------------------

create table if not exists public.line_room_messages_search (
  id bigint generated by default as identity primary key,
  room_id text not null,
  room_message_id bigint not null,
  message_table text not null,
  line_message_id text,
  webhook_event_id text,
  user_id text,
  message_type text not null default 'unknown',
  text_content text not null default '',
  created_at timestamptz not null default now()
);

comment on table public.line_room_messages_search is
  '会話検索用インデックス（最大1年）。ルーム別テーブルと二重書き込み。';

create unique index if not exists line_room_messages_search_room_msg_uidx
  on public.line_room_messages_search (message_table, room_message_id);

create index if not exists line_room_messages_search_room_created_idx
  on public.line_room_messages_search (room_id, created_at desc);

create index if not exists line_room_messages_search_created_idx
  on public.line_room_messages_search (created_at desc);

create index if not exists line_room_messages_search_text_trgm_idx
  on public.line_room_messages_search using gin (text_content gin_trgm_ops);

-- ---------------------------------------------------------------------------
-- Room calendar events (LINE/Google 予定のルーム別検索用)
-- ---------------------------------------------------------------------------

create table if not exists public.line_room_calendar_events (
  id bigint generated by default as identity primary key,
  room_id text not null,
  event_title text not null default '',
  event_description text not null default '',
  starts_at timestamptz,
  ends_at timestamptz,
  source text not null default 'google_calendar',
  external_event_id text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

comment on table public.line_room_calendar_events is
  'ルーム単位の予定検索用（会話から登録されたカレンダーイベント等）';

create index if not exists line_room_calendar_events_room_starts_idx
  on public.line_room_calendar_events (room_id, starts_at desc nulls last);

create index if not exists line_room_calendar_events_created_idx
  on public.line_room_calendar_events (created_at desc);

create index if not exists line_room_calendar_events_title_trgm_idx
  on public.line_room_calendar_events using gin (event_title gin_trgm_ops);

create index if not exists line_room_calendar_events_desc_trgm_idx
  on public.line_room_calendar_events using gin (event_description gin_trgm_ops);

create unique index if not exists line_room_calendar_events_room_external_uidx
  on public.line_room_calendar_events (room_id, source, external_event_id)
  where external_event_id is not null;

-- ---------------------------------------------------------------------------
-- Ensure per-room table + RLS
-- ---------------------------------------------------------------------------

create or replace function public.ensure_line_room_message_table(p_room_id text)
returns text
language plpgsql
security definer
set search_path = public
as $$
declare
  tbl text;
  existing text;
begin
  if not public.is_valid_line_room_id(p_room_id) then
    raise exception 'invalid room_id: %', p_room_id;
  end if;

  select message_table into existing
  from public.line_room_message_tables
  where room_id = p_room_id;

  if existing is not null then
    return existing;
  end if;

  tbl := public.line_room_message_table_name(p_room_id);

  execute format($sql$
    create table if not exists public.%I (
      id bigint generated by default as identity primary key,
      line_message_id text,
      webhook_event_id text,
      user_id text,
      message_type text not null default 'unknown',
      text_content text not null default '',
      payload jsonb,
      created_at timestamptz not null default now()
    )
  $sql$, tbl);

  execute format(
    'create unique index if not exists %I on public.%I (line_message_id) where line_message_id is not null',
    tbl || '_line_message_uidx',
    tbl
  );

  execute format(
    'create index if not exists %I on public.%I (created_at desc)',
    tbl || '_created_at_idx',
    tbl
  );

  execute format(
    'create index if not exists %I on public.%I using gin (text_content gin_trgm_ops)',
    tbl || '_text_trgm_idx',
    tbl
  );

  execute format('alter table public.%I enable row level security', tbl);

  insert into public.line_room_message_tables (room_id, message_table, updated_at)
  values (p_room_id, tbl, now())
  on conflict (room_id) do update
    set updated_at = excluded.updated_at;

  return tbl;
end;
$$;

-- ---------------------------------------------------------------------------
-- Insert message (room table + search index)
-- ---------------------------------------------------------------------------

create or replace function public.insert_line_room_message(
  p_room_id text,
  p_line_message_id text default null,
  p_webhook_event_id text default null,
  p_user_id text default null,
  p_message_type text default 'unknown',
  p_text_content text default '',
  p_payload jsonb default null
)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  tbl text;
  room_row_id bigint;
  search_id bigint;
  content text;
begin
  if not public.is_valid_line_room_id(p_room_id) then
    raise exception 'invalid room_id: %', p_room_id;
  end if;

  content := coalesce(btrim(p_text_content), '');
  if content = '' then
    return null;
  end if;

  tbl := public.ensure_line_room_message_table(p_room_id);

  execute format($sql$
    insert into public.%I (
      line_message_id, webhook_event_id, user_id, message_type, text_content, payload
    ) values ($1, $2, $3, $4, $5, $6)
    on conflict do nothing
    returning id
  $sql$, tbl)
  into room_row_id
  using
    nullif(btrim(p_line_message_id), ''),
    nullif(btrim(p_webhook_event_id), ''),
    nullif(btrim(p_user_id), ''),
    coalesce(nullif(btrim(p_message_type), ''), 'unknown'),
    content,
    p_payload;

  if room_row_id is null and nullif(btrim(p_line_message_id), '') is not null then
    execute format(
      'select id from public.%I where line_message_id = $1 limit 1',
      tbl
    )
    into room_row_id
    using nullif(btrim(p_line_message_id), '');
  end if;

  if room_row_id is null then
    execute format($sql$
      insert into public.%I (
        line_message_id, webhook_event_id, user_id, message_type, text_content, payload
      ) values ($1, $2, $3, $4, $5, $6)
      returning id
    $sql$, tbl)
    into room_row_id
    using
      nullif(btrim(p_line_message_id), ''),
      nullif(btrim(p_webhook_event_id), ''),
      nullif(btrim(p_user_id), ''),
      coalesce(nullif(btrim(p_message_type), ''), 'unknown'),
      content,
      p_payload;
  end if;

  insert into public.line_room_messages_search (
    room_id,
    room_message_id,
    message_table,
    line_message_id,
    webhook_event_id,
    user_id,
    message_type,
    text_content,
    created_at
  )
  select
    p_room_id,
    room_row_id,
    tbl,
    nullif(btrim(p_line_message_id), ''),
    nullif(btrim(p_webhook_event_id), ''),
    nullif(btrim(p_user_id), ''),
    coalesce(nullif(btrim(p_message_type), ''), 'unknown'),
    content,
    now()
  on conflict (message_table, room_message_id) do update
    set text_content = excluded.text_content,
        message_type = excluded.message_type,
        user_id = excluded.user_id
  returning id into search_id;

  return search_id;
end;
$$;

-- ---------------------------------------------------------------------------
-- Search (1 year window, fragment match via ILIKE + trgm index)
-- ---------------------------------------------------------------------------

create or replace function public.search_line_room_messages(
  p_query text,
  p_room_id text default null,
  p_limit integer default 50,
  p_offset integer default 0
)
returns table (
  id bigint,
  room_id text,
  room_message_id bigint,
  line_message_id text,
  user_id text,
  message_type text,
  text_content text,
  created_at timestamptz,
  total_count bigint
)
language plpgsql
security definer
set search_path = public
as $$
declare
  q text;
  lim int;
  off int;
  since timestamptz := now() - interval '365 days';
begin
  q := btrim(coalesce(p_query, ''));
  if length(q) < 1 then
    raise exception 'query required';
  end if;

  lim := greatest(1, least(coalesce(p_limit, 50), 100));
  off := greatest(coalesce(p_offset, 0), 0);

  if p_room_id is not null and btrim(p_room_id) <> '' and not public.is_valid_line_room_id(p_room_id) then
    raise exception 'invalid room_id: %', p_room_id;
  end if;

  return query
  with filtered as (
    select s.*
    from public.line_room_messages_search s
    where s.created_at >= since
      and (p_room_id is null or btrim(p_room_id) = '' or s.room_id = p_room_id)
      and s.text_content ilike '%' || replace(replace(q, '\', '\\'), '%', '\%') || '%' escape '\'
  ),
  counted as (
    select count(*)::bigint as cnt from filtered
  )
  select
    f.id,
    f.room_id,
    f.room_message_id,
    f.line_message_id,
    f.user_id,
    f.message_type,
    f.text_content,
    f.created_at,
    c.cnt
  from filtered f
  cross join counted c
  order by f.created_at desc
  limit lim
  offset off;
end;
$$;

create or replace function public.search_line_room_calendar_events(
  p_query text,
  p_room_id text default null,
  p_limit integer default 50,
  p_offset integer default 0
)
returns table (
  id bigint,
  room_id text,
  event_title text,
  event_description text,
  starts_at timestamptz,
  ends_at timestamptz,
  source text,
  external_event_id text,
  created_at timestamptz,
  total_count bigint
)
language plpgsql
security definer
set search_path = public
as $$
declare
  q text;
  lim int;
  off int;
  since timestamptz := now() - interval '365 days';
begin
  q := btrim(coalesce(p_query, ''));
  if length(q) < 1 then
    raise exception 'query required';
  end if;

  lim := greatest(1, least(coalesce(p_limit, 50), 100));
  off := greatest(coalesce(p_offset, 0), 0);

  if p_room_id is not null and btrim(p_room_id) <> '' and not public.is_valid_line_room_id(p_room_id) then
    raise exception 'invalid room_id: %', p_room_id;
  end if;

  return query
  with filtered as (
    select e.*
    from public.line_room_calendar_events e
    where coalesce(e.starts_at, e.created_at) >= since
      and (p_room_id is null or btrim(p_room_id) = '' or e.room_id = p_room_id)
      and (
        e.event_title ilike '%' || replace(replace(q, '\', '\\'), '%', '\%') || '%' escape '\'
        or e.event_description ilike '%' || replace(replace(q, '\', '\\'), '%', '\%') || '%' escape '\'
      )
  ),
  counted as (
    select count(*)::bigint as cnt from filtered
  )
  select
    f.id,
    f.room_id,
    f.event_title,
    f.event_description,
    f.starts_at,
    f.ends_at,
    f.source,
    f.external_event_id,
    f.created_at,
    c.cnt
  from filtered f
  cross join counted c
  order by coalesce(f.starts_at, f.created_at) desc nulls last
  limit lim
  offset off;
end;
$$;

-- Upsert calendar event (for future LINE/GCal writers)
create or replace function public.upsert_line_room_calendar_event(
  p_room_id text,
  p_event_title text,
  p_event_description text default '',
  p_starts_at timestamptz default null,
  p_ends_at timestamptz default null,
  p_source text default 'google_calendar',
  p_external_event_id text default null
)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  evt_id bigint;
begin
  if not public.is_valid_line_room_id(p_room_id) then
    raise exception 'invalid room_id: %', p_room_id;
  end if;

  if nullif(btrim(p_external_event_id), '') is not null then
    insert into public.line_room_calendar_events (
      room_id, event_title, event_description, starts_at, ends_at, source, external_event_id, updated_at
    ) values (
      p_room_id,
      coalesce(btrim(p_event_title), ''),
      coalesce(btrim(p_event_description), ''),
      p_starts_at,
      p_ends_at,
      coalesce(nullif(btrim(p_source), ''), 'google_calendar'),
      btrim(p_external_event_id),
      now()
    )
    on conflict (room_id, source, external_event_id)
    do update set
      event_title = excluded.event_title,
      event_description = excluded.event_description,
      starts_at = excluded.starts_at,
      ends_at = excluded.ends_at,
      updated_at = now()
    returning id into evt_id;
    return evt_id;
  end if;

  insert into public.line_room_calendar_events (
    room_id, event_title, event_description, starts_at, ends_at, source, external_event_id, updated_at
  ) values (
    p_room_id,
    coalesce(btrim(p_event_title), ''),
    coalesce(btrim(p_event_description), ''),
    p_starts_at,
    p_ends_at,
    coalesce(nullif(btrim(p_source), ''), 'google_calendar'),
    null,
    now()
  )
  returning id into evt_id;

  return evt_id;
end;
$$;

-- ---------------------------------------------------------------------------
-- Retention: delete rows older than 1 year
-- ---------------------------------------------------------------------------

create or replace function public.purge_line_room_messages_older_than(
  p_retention_days integer default 365
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  days int;
  cutoff timestamptz;
  search_deleted bigint := 0;
  calendar_deleted bigint := 0;
  room_deleted bigint := 0;
  rec record;
  n bigint;
begin
  days := greatest(coalesce(p_retention_days, 365), 1);
  cutoff := now() - make_interval(days => days);

  delete from public.line_room_messages_search
  where created_at < cutoff;
  get diagnostics search_deleted = row_count;

  delete from public.line_room_calendar_events
  where coalesce(starts_at, created_at) < cutoff;
  get diagnostics calendar_deleted = row_count;

  for rec in
    select room_id, message_table
    from public.line_room_message_tables
  loop
    execute format(
      'delete from public.%I where created_at < $1',
      rec.message_table
    )
    using cutoff;
    get diagnostics n = row_count;
    room_deleted := room_deleted + coalesce(n, 0);
  end loop;

  return jsonb_build_object(
    'retention_days', days,
    'cutoff', cutoff,
    'search_index_deleted', search_deleted,
    'calendar_deleted', calendar_deleted,
    'room_tables_deleted', room_deleted
  );
end;
$$;

-- get_room_overview: include new message index stats
drop function if exists public.get_room_overview(text);

create function public.get_room_overview(p_admin_surface text default 'legacy')
returns table (
  room_id text,
  room_name text,
  total_messages bigint,
  pending_messages bigint,
  last_message_at timestamptz,
  last_pending_at timestamptz,
  settings_enabled boolean,
  settings_delivery_hours integer[],
  settings_updated_at timestamptz
)
language sql
security definer
set search_path = public
as $$
with legacy_stats as (
    select
        lm.room_id,
        count(*)::bigint as total_messages,
        count(*) filter (where lm.processed = false)::bigint as pending_messages,
        max(lm.created_at) as last_message_at,
        max(lm.created_at) filter (where lm.processed = false) as last_pending_at
    from public.line_messages lm
    group by lm.room_id
),
search_stats as (
    select
        s.room_id,
        count(*)::bigint as total_messages,
        0::bigint as pending_messages,
        max(s.created_at) as last_message_at,
        null::timestamptz as last_pending_at
    from public.line_room_messages_search s
    group by s.room_id
),
message_stats as (
    select
        u.room_id,
        sum(u.total_messages)::bigint as total_messages,
        sum(u.pending_messages)::bigint as pending_messages,
        max(u.last_message_at) as last_message_at,
        max(u.last_pending_at) as last_pending_at
    from (
        select * from legacy_stats
        union all
        select * from search_stats
    ) u
    group by u.room_id
),
all_room_ids as (
    select room_id from message_stats
    union
    select room_id from public.room_summary_settings
    union
    select room_id from public.line_room_names
),
surface as (
    select coalesce(nullif(btrim(p_admin_surface), ''), 'legacy') as admin_surface
)
select
    r.room_id,
    coalesce(rs.room_name, rn.room_name, r.room_id) as room_name,
    coalesce(ms.total_messages, 0)::bigint as total_messages,
    coalesce(ms.pending_messages, 0)::bigint as pending_messages,
    ms.last_message_at,
    ms.last_pending_at,
    coalesce(rs.is_enabled, true) as settings_enabled,
    rs.delivery_hours as settings_delivery_hours,
    rs.updated_at as settings_updated_at
from all_room_ids r
cross join surface s
left join message_stats ms on ms.room_id = r.room_id
left join public.room_summary_settings rs on rs.room_id = r.room_id
left join public.line_room_names rn on rn.room_id = r.room_id
where not exists (
  select 1
  from public.line_room_dismissed d
  where d.room_id = r.room_id
    and d.admin_surface = s.admin_surface
)
order by coalesce(ms.last_message_at, rs.updated_at, rn.updated_at) desc nulls last, r.room_id asc;
$$;

alter table public.line_room_message_tables enable row level security;
alter table public.line_room_messages_search enable row level security;
alter table public.line_room_calendar_events enable row level security;
